use std::collections::HashSet;

use once_cell::sync::Lazy;
use regex::Regex;
use sonic_rs::{Index, JsonContainerTrait, JsonValueTrait, Value};

use crate::types::{joined_text, ContentBlock, Entry, EntryMeta};
use crate::value::{field, field_bool, field_str};

/// The well-known filter specs the `show` command serves and the parse+filter
/// bench reuses: `--signal` keeps conversational turns minus junk, `--no-junk`
/// (`builders.NOISE_SPEC` in Python) drops structural noise. The one source of
/// truth; `tests/test_show_specs.py` pins Python's `NOISE_SPEC` to `NOISE_SPEC_JSON`.
pub const SIGNAL_SPEC_JSON: &str = r#"{"clauses":[{"predicate":{"kind":"KindIs","kinds":["assistant","user"]},"action":"drop","applies_to":[],"negate":true,"label":null},{"predicate":{"kind":"TextMatchesAny","groups":[["xml_tags","<(?:system[_-](?:instruction|reminder)|local-command-(?:stdout|stderr|caveat)|command-(?:name|message|args)|task-notification|persisted-output|output-file)\\b"],["local_command_caveat","Caveat: The messages below were generated by the user while running local commands\\."],["remaining_tasks_ack","REMAINING_TASKS_ACKNOWLEDGED"],["angle_token","<<[a-z][a-z0-9-]*>>"],["skill_base_dir","^Base directory for this skill:"],["hash_banner","(?:###\\s+[\\w][\\w \\-]{0,30}\\s+){3,}###"],["xml_tags_extra","\\A\\s*<(?:teammate-message|scheduled-task|agent-message|cross-session-message)(?:[\\s/>]|$)"],["relay_preamble","\\A\\s*Another Claude sess(?-i:[Ii])on sent a message:"],["augment_agent","\\A\\s*# Augment Agent(?:\\s|$)"],["role_reminder","\\A\\s*\\[Role Rem(?-i:[Ii])nder(?:[\\s:\\]]|$)"],["command_echo","\\A\\s*<bash-(?:input|stdout|stderr)\\b"]],"ignore_case":true},"action":"drop","applies_to":["user"],"negate":false,"label":null},{"predicate":{"kind":"ModelIs","models":["<synthetic>"]},"action":"drop","applies_to":["assistant"],"negate":false,"label":null},{"predicate":{"kind":"MetaFlag","flag":"is_sidechain"},"action":"drop","applies_to":[],"negate":false,"label":null},{"predicate":{"kind":"TextEmpty","consider_tool_use":false},"action":"drop","applies_to":["user"],"negate":false,"label":null},{"predicate":{"kind":"TextEmpty","consider_tool_use":true},"action":"drop","applies_to":["assistant"],"negate":false,"label":null}]}"#;
pub const NOISE_SPEC_JSON: &str = r#"{"clauses":[{"predicate":{"kind":"TextMatchesAny","groups":[["xml_tags","<(?:system[_-](?:instruction|reminder)|local-command-(?:stdout|stderr|caveat)|command-(?:name|message|args)|task-notification|persisted-output|output-file)\\b"],["local_command_caveat","Caveat: The messages below were generated by the user while running local commands\\."],["remaining_tasks_ack","REMAINING_TASKS_ACKNOWLEDGED"],["angle_token","<<[a-z][a-z0-9-]*>>"],["skill_base_dir","^Base directory for this skill:"],["hash_banner","(?:###\\s+[\\w][\\w \\-]{0,30}\\s+){3,}###"]],"ignore_case":true},"action":"drop","applies_to":["user"],"negate":false,"label":null}]}"#;

pub static SIGNAL_SPEC: Lazy<CompiledSpec> =
    Lazy::new(|| compile_spec(SIGNAL_SPEC_JSON).expect("SIGNAL_SPEC compiles"));
pub static NOISE_SPEC: Lazy<CompiledSpec> =
    Lazy::new(|| compile_spec(NOISE_SPEC_JSON).expect("NOISE_SPEC compiles"));

#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum Kind {
    User,
    Assistant,
    System,
    Mode,
    Other,
    Attachment,
}

pub struct CompiledSpec {
    clauses: Vec<CompiledClause>,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Action {
    Drop,
    Tag,
}

struct CompiledClause {
    predicate: CompiledPredicate,
    applies_to: Vec<Kind>,
    negate: bool,
    action: Action,
    label: Option<String>,
}

enum CompiledPredicate {
    KindIs(Vec<Kind>),
    MetaFlag(fn(&EntryMeta) -> bool),
    EntrypointIn(HashSet<String>),
    ModelIs(HashSet<String>),
    TextEmpty {
        consider_tool_use: bool,
    },
    TextMatchesAny(Regex),
    TextInSet {
        phrases: HashSet<String>,
        strip_trailing: String,
    },
    WordCountAtMost(usize),
}

fn parse_kind(name: &str) -> Result<Kind, String> {
    match name {
        "user" => Ok(Kind::User),
        "assistant" => Ok(Kind::Assistant),
        "system" => Ok(Kind::System),
        "mode" => Ok(Kind::Mode),
        "other" => Ok(Kind::Other),
        "attachment" => Ok(Kind::Attachment),
        other => Err(format!("unknown event kind: {other}")),
    }
}

fn parse_action(name: &str) -> Result<Action, String> {
    match name {
        "drop" => Ok(Action::Drop),
        "tag" => Ok(Action::Tag),
        other => Err(format!("unknown clause action: {other}")),
    }
}

fn meta_flag(flag: &str) -> Result<fn(&EntryMeta) -> bool, String> {
    match flag {
        "is_sidechain" => Ok(|meta| meta.is_sidechain),
        "is_meta" => Ok(|meta| meta.is_meta),
        "is_compact_summary" => Ok(|meta| meta.is_compact_summary),
        "is_visible_in_transcript_only" => Ok(|meta| meta.is_visible_in_transcript_only),
        other => Err(format!("unknown meta flag: {other}")),
    }
}

fn str_set(predicate: &Value, key: &str) -> HashSet<String> {
    field(predicate, key)
        .and_then(JsonContainerTrait::as_array)
        .into_iter()
        .flatten()
        .filter_map(JsonValueTrait::as_str)
        .map(String::from)
        .collect()
}

fn kind_array(predicate: &Value, key: &str) -> Result<Vec<Kind>, String> {
    field(predicate, key)
        .and_then(JsonContainerTrait::as_array)
        .into_iter()
        .flatten()
        .filter_map(JsonValueTrait::as_str)
        .map(parse_kind)
        .collect()
}

fn compile_regex(predicate: &Value) -> Result<Regex, String> {
    let groups = field(predicate, "groups")
        .and_then(JsonContainerTrait::as_array)
        .ok_or("TextMatchesAny missing 'groups'")?;
    compile_group_array(groups, field_bool(predicate, "ignore_case"))
}

/// Joins ``(name, pattern)`` group pairs into one alternation, matching the Python
/// ``compile_groups`` (so the score executor's regex stages share its semantics).
pub fn compile_group_array(groups: &sonic_rs::Array, ignore_case: bool) -> Result<Regex, String> {
    let joined = groups
        .iter()
        .filter_map(|group| {
            1usize
                .value_index_into(group)
                .and_then(JsonValueTrait::as_str)
        })
        .map(|pattern| format!("(?:{pattern})"))
        .collect::<Vec<_>>()
        .join("|");
    let pattern = if ignore_case {
        format!("(?i){joined}")
    } else {
        joined
    };
    Regex::new(&pattern).map_err(|e| format!("invalid regex {pattern:?}: {e}"))
}

fn compile_predicate(predicate: &Value) -> Result<CompiledPredicate, String> {
    match field_str(predicate, "kind").ok_or("predicate missing 'kind'")? {
        "KindIs" => Ok(CompiledPredicate::KindIs(kind_array(predicate, "kinds")?)),
        "MetaFlag" => Ok(CompiledPredicate::MetaFlag(meta_flag(
            field_str(predicate, "flag").ok_or("MetaFlag missing 'flag'")?,
        )?)),
        "EntrypointIn" => Ok(CompiledPredicate::EntrypointIn(str_set(
            predicate,
            "entrypoints",
        ))),
        "ModelIs" => Ok(CompiledPredicate::ModelIs(str_set(predicate, "models"))),
        "TextEmpty" => Ok(CompiledPredicate::TextEmpty {
            consider_tool_use: field_bool(predicate, "consider_tool_use"),
        }),
        "TextMatchesAny" => Ok(CompiledPredicate::TextMatchesAny(compile_regex(predicate)?)),
        "TextInSet" => Ok(CompiledPredicate::TextInSet {
            phrases: str_set(predicate, "phrases"),
            strip_trailing: field_str(predicate, "strip_trailing")
                .unwrap_or("")
                .to_string(),
        }),
        "WordCountAtMost" => Ok(CompiledPredicate::WordCountAtMost(
            field(predicate, "n")
                .and_then(JsonValueTrait::as_u64)
                .ok_or("WordCountAtMost missing 'n'")? as usize,
        )),
        other => Err(format!("unknown predicate kind: {other}")),
    }
}

fn compile_clause(clause: &Value) -> Result<CompiledClause, String> {
    Ok(CompiledClause {
        predicate: compile_predicate(
            field(clause, "predicate").ok_or("clause missing 'predicate'")?,
        )?,
        applies_to: kind_array(clause, "applies_to")?,
        negate: field_bool(clause, "negate"),
        action: parse_action(field_str(clause, "action").ok_or("clause missing 'action'")?)?,
        label: field_str(clause, "label").map(String::from),
    })
}

/// Compiles the JSON contract emitted by ``cc_transcript.filterspec.spec_to_json``.
/// Every clause is compiled; ``spec_keep`` reads the ``DROP`` clauses and
/// ``spec_labels`` reads the ``TAG`` clauses.
pub fn compile_spec(spec_json: &str) -> Result<CompiledSpec, String> {
    let root: Value =
        sonic_rs::from_str(spec_json).map_err(|e| format!("invalid filter spec json: {e}"))?;
    let clauses = field(&root, "clauses")
        .and_then(JsonContainerTrait::as_array)
        .ok_or("spec missing 'clauses' array")?
        .iter()
        .map(compile_clause)
        .collect::<Result<Vec<_>, _>>()?;
    Ok(CompiledSpec { clauses })
}

fn entry_kind(entry: &Entry) -> Kind {
    match entry {
        Entry::User(_) => Kind::User,
        Entry::Assistant(_) => Kind::Assistant,
        Entry::System(_) => Kind::System,
        Entry::Mode(_) => Kind::Mode,
        Entry::Other(_) => Kind::Other,
        Entry::Attachment(_) => Kind::Attachment,
    }
}

pub(crate) fn entry_text(entry: &Entry) -> String {
    match entry {
        Entry::User(user) => user.content.text(),
        Entry::Assistant(assistant) => joined_text(&assistant.blocks),
        _ => String::new(),
    }
}

/// Parity: filterspec.event_kind — the string kind tag the renderer and stats key on.
pub fn event_kind(entry: &Entry) -> &'static str {
    match entry {
        Entry::User(_) => "user",
        Entry::Assistant(_) => "assistant",
        Entry::System(_) => "system",
        Entry::Mode(_) => "mode",
        Entry::Other(_) => "other",
        Entry::Attachment(_) => "attachment",
    }
}

pub fn normalize_bare(text: &str, strip_trailing: &str) -> String {
    text.trim()
        .trim_end_matches(|c: char| strip_trailing.contains(c))
        .trim()
        .to_lowercase()
}

fn predicate_matches(predicate: &CompiledPredicate, entry: &Entry, kind: Kind, text: &str) -> bool {
    match predicate {
        CompiledPredicate::KindIs(kinds) => kinds.contains(&kind),
        CompiledPredicate::ModelIs(models) => {
            matches!(entry, Entry::Assistant(assistant) if models.contains(&assistant.model))
        }
        CompiledPredicate::TextEmpty { consider_tool_use } => match entry {
            Entry::Assistant(assistant) if *consider_tool_use => {
                text.trim().is_empty()
                    && !assistant
                        .blocks
                        .iter()
                        .any(|b| matches!(b, ContentBlock::ToolUse(_)))
            }
            Entry::User(_) | Entry::Assistant(_) => text.trim().is_empty(),
            _ => false,
        },
        CompiledPredicate::TextMatchesAny(re) => re.is_match(text),
        CompiledPredicate::TextInSet {
            phrases,
            strip_trailing,
        } => phrases.contains(&normalize_bare(text, strip_trailing)),
        CompiledPredicate::WordCountAtMost(n) => text.split_whitespace().count() <= *n,
        CompiledPredicate::MetaFlag(flag) => entry.meta().is_some_and(flag),
        CompiledPredicate::EntrypointIn(set) => entry
            .meta()
            .is_some_and(|meta| meta.entrypoint.as_deref().is_some_and(|e| set.contains(e))),
    }
}

fn clause_matches(clause: &CompiledClause, entry: &Entry, kind: Kind, text: &str) -> bool {
    if !clause.applies_to.is_empty() && !clause.applies_to.contains(&kind) {
        return false;
    }
    predicate_matches(&clause.predicate, entry, kind, text) != clause.negate
}

/// Returns whether ``entry`` survives every ``DROP`` clause of ``spec``.
pub fn spec_keep(spec: &CompiledSpec, entry: &Entry) -> bool {
    let kind = entry_kind(entry);
    let text = entry_text(entry);
    !spec
        .clauses
        .iter()
        .any(|clause| clause.action == Action::Drop && clause_matches(clause, entry, kind, &text))
}

/// Returns the labels every matching ``TAG`` clause of ``spec`` records for ``entry``,
/// in clause order (mirrors ``cc_transcript.filterspec.labels_for``).
pub fn spec_labels<'a>(spec: &'a CompiledSpec, entry: &Entry) -> Vec<&'a str> {
    let kind = entry_kind(entry);
    let text = entry_text(entry);
    spec.clauses
        .iter()
        .filter(|clause| clause.action == Action::Tag)
        .filter_map(|clause| {
            clause
                .label
                .as_deref()
                .filter(|_| clause_matches(clause, entry, kind, &text))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::parse_entry;

    fn parse(raw: &str) -> Entry {
        parse_entry(sonic_rs::from_str(raw).unwrap()).unwrap()
    }

    fn pushback_spec() -> CompiledSpec {
        compile_spec(
            r#"{"clauses":[
                {"predicate":{"kind":"KindIs","kinds":["user"]},"action":"drop","applies_to":[],"negate":true,"label":null},
                {"predicate":{"kind":"MetaFlag","flag":"is_meta"},"action":"drop","applies_to":[],"negate":false,"label":null},
                {"predicate":{"kind":"TextMatchesAny","groups":[["interrupt","^\\s*\\[Request interrupted by user"]],"ignore_case":true},"action":"drop","applies_to":["user"],"negate":false,"label":null},
                {"predicate":{"kind":"TextInSet","phrases":["ok","go ahead"],"strip_trailing":".!?,;:"},"action":"drop","applies_to":["user"],"negate":false,"label":null},
                {"predicate":{"kind":"WordCountAtMost","n":2},"action":"drop","applies_to":["user"],"negate":false,"label":null}
            ]}"#,
        )
        .unwrap()
    }

    fn user(text: &str) -> Entry {
        parse(&format!(
            r#"{{"type":"user","uuid":"u","sessionId":"s","timestamp":"2026-01-01T00:00:00Z","message":{{"role":"user","content":{}}}}}"#,
            sonic_rs::to_string(&text).unwrap()
        ))
    }

    #[test]
    fn keeps_real_pushback_drops_noise() {
        let spec = pushback_spec();
        assert!(spec_keep(
            &spec,
            &user("please refactor the parser carefully")
        ));
        assert!(!spec_keep(&spec, &user("ok")));
        assert!(!spec_keep(&spec, &user("go ahead.")));
        assert!(!spec_keep(&spec, &user("fix it"))); // two words -> dropped
        assert!(
            spec_keep(
                &spec,
                &user("[Request interrupted by user] no, do it this way")
            ) == false
        );
        assert!(spec_keep(
            &spec,
            &user("she quoted [Request interrupted by user] mid-text here")
        )); // head-anchored: mid-text marker kept
    }

    #[test]
    fn negate_kind_drops_non_users() {
        let spec = pushback_spec();
        let assistant = parse(
            r#"{"type":"assistant","uuid":"a","sessionId":"s","timestamp":"2026-01-01T00:00:00Z","message":{"model":"m","content":[{"type":"text","text":"hello there friend"}]}}"#,
        );
        assert!(!spec_keep(&spec, &assistant));
    }

    #[test]
    fn meta_flag_drops_meta_user() {
        let spec = pushback_spec();
        let meta_user = parse(
            r#"{"type":"user","uuid":"u","sessionId":"s","timestamp":"2026-01-01T00:00:00Z","isMeta":true,"message":{"role":"user","content":"a long real prompt here please"}}"#,
        );
        assert!(!spec_keep(&spec, &meta_user));
    }

    #[test]
    fn unknown_predicate_is_an_error() {
        assert!(compile_spec(r#"{"clauses":[{"predicate":{"kind":"Nope"},"action":"drop","applies_to":[],"negate":false}]}"#).is_err());
    }

    #[test]
    fn wellknown_specs_compile() {
        assert!(!super::SIGNAL_SPEC.clauses.is_empty());
        assert!(!super::NOISE_SPEC.clauses.is_empty());
    }

    fn tag_spec() -> CompiledSpec {
        compile_spec(
            r#"{"clauses":[
                {"predicate":{"kind":"TextInSet","phrases":["go ahead"],"strip_trailing":""},"action":"tag","applies_to":["user"],"negate":false,"label":"resume"},
                {"predicate":{"kind":"WordCountAtMost","n":5},"action":"tag","applies_to":["user"],"negate":false,"label":"short"},
                {"predicate":{"kind":"MetaFlag","flag":"is_sidechain"},"action":"drop","applies_to":[],"negate":false,"label":null}
            ]}"#,
        )
        .unwrap()
    }

    #[test]
    fn spec_labels_records_matching_tags_in_clause_order() {
        let spec = tag_spec();
        let event = user("go ahead");
        // TAG clauses never drop; the DROP clause does not fire on a non-sidechain user.
        assert!(spec_keep(&spec, &event));
        assert_eq!(spec_labels(&spec, &event), vec!["resume", "short"]);
        // A long, non-phrase message matches neither TAG clause.
        assert_eq!(
            spec_labels(
                &spec,
                &user("this message runs well past the five word ceiling here today")
            ),
            Vec::<&str>::new()
        );
    }

    #[test]
    fn tag_clauses_never_drop_but_drop_clauses_still_drop() {
        let spec = tag_spec();
        // "go ahead" fires two TAG clauses yet survives.
        assert!(spec_keep(&spec, &user("go ahead")));
        let sidechain = parse(
            r#"{"type":"user","uuid":"u","sessionId":"s","timestamp":"2026-01-01T00:00:00Z","isSidechain":true,"message":{"role":"user","content":"go ahead"}}"#,
        );
        assert!(!spec_keep(&spec, &sidechain));
    }
}
