"""The cc-family session-activity platform.

One spine: parse Claude Code transcript JSONL into typed events, lift them
into a :class:`~cc_transcript.activity.SessionActivity` of turns, tool calls,
and edits — and every higher capability (context windows, evidence harvest,
queries, the decision ledger, LLM judging) is a pure function or thin store
over that spine.

Parsing is native: :func:`parse` turns one source into a
:class:`~cc_transcript.models.Transcript` view and :func:`stream` fans a batch
of paths across the native parse pool, with ``drop`` specs applied before any
Python object materializes.

The package root is lazy (PEP 562): importing ``cc_transcript.ids`` pulls the
standard library only, so a hook's digest-only hot path pays nothing for the
parser extension or any heavy dependency.
"""

from __future__ import annotations

from importlib import import_module

EXPORTS: dict[str, str] = {
    name: module
    for module, names in {
        "cc_transcript.ids": (
            "EventRef",
            "EventUuid",
            "SessionId",
            "ToolDigest",
            "ToolUseId",
            "canonical_json",
            "tool_digest",
        ),
        "cc_transcript.tools": (
            "TOOL_ALIASES",
            "AskUserQuestionResult",
            "BashCall",
            "BashResult",
            "EditCall",
            "EditResult",
            "EditSpan",
            "ExitPlanModeCall",
            "GlobCall",
            "GrepCall",
            "Hunk",
            "MultiEditCall",
            "NotebookEditCall",
            "OtherCall",
            "OtherResult",
            "QuestionAnnotation",
            "ReadCall",
            "ReadResult",
            "SkillCall",
            "SkillResult",
            "SpanEditCall",
            "TaskCall",
            "TaskCreateCall",
            "TaskLaunchResult",
            "TaskResult",
            "TaskUpdateCall",
            "TextResult",
            "ToolCall",
            "ToolCallBase",
            "ToolInputError",
            "ToolResult",
            "ToolResultBase",
            "ToolResultError",
            "WorkflowCall",
            "WriteCall",
            "WriteResult",
            "expand_tool_names",
            "file_path_of",
            "hunks_of",
            "matches_names",
            "mcp_access",
            "mcp_parts",
            "parse_tool_call",
            "parse_tool_result",
            "register_mcp_tool",
            "tool_name_matches",
            "unregister_mcp_tool",
        ),
        "cc_transcript.command": (
            "Command",
            "CommandLine",
            "CommandLineQuery",
            "Occurrence",
            "Redirect",
            "Word",
            "command_prefixes",
            "parse_command_line",
        ),
        "cc_transcript.models": (
            "ApiError",
            "AssistantEvent",
            "AsyncHookResponse",
            "AttachmentDetail",
            "AttachmentEvent",
            "Attribution",
            "CacheCreation",
            "CcVersion",
            "CompactBoundary",
            "ContentBlock",
            "EntryMeta",
            "EventList",
            "FallbackBlock",
            "HookAdditionalContext",
            "HookBlockingError",
            "HookCancelled",
            "HookInfo",
            "HookNonBlockingError",
            "HookSuccess",
            "InitInfo",
            "McpServer",
            "ModelRefusalFallback",
            "ModeEvent",
            "ModelUsage",
            "OtherAttachment",
            "OtherBlock",
            "OtherEvent",
            "OtherSystemDetail",
            "Plugin",
            "PreservedMessages",
            "PreservedSegment",
            "PrintMessage",
            "PrintResult",
            "Question",
            "QueuedCommand",
            "ServerToolUse",
            "StopHookSummary",
            "SystemDetail",
            "SystemEvent",
            "TextBlock",
            "ThinkingBlock",
            "ToolResultBlock",
            "ToolUseBlock",
            "Transcript",
            "TranscriptEvent",
            "TurnDuration",
            "Usage",
            "UserEvent",
            "thinking_chars",
            "tool_uses",
        ),
        "cc_transcript.parser": (
            "parse",
            "parse_event",
            "parse_events",
            "parse_events_from_bytes",
            "parse_print_result",
            "stream",
        ),
        "cc_transcript.synthetic": (
            "assistant_line",
            "meta_fields",
            "mode_line",
            "other_line",
            "synthetic_assistant_event",
            "synthetic_user_event",
            "system_line",
            "text_block",
            "thinking_block",
            "tool_result",
            "tool_use",
            "user_line",
        ),
        "cc_transcript.cost": (
            "PRICING",
            "CostBreakdown",
            "ModelPricing",
            "cost_of",
            "cost_of_assistant",
            "resolve_pricing",
        ),
        "cc_transcript.discovery": (
            "CLAUDE_PROJECTS_DIR",
            "TranscriptExpiredError",
            "discover",
            "find_in",
            "resolve",
            "subagent_paths",
        ),
        "cc_transcript.codex": (
            "CodexPendingItem",
            "CodexRollout",
            "CodexSessionInfo",
            "CodexUsage",
            "Lifecycle",
        ),
        "cc_transcript.activity": (
            "Edit",
            "SessionActivity",
            "ToolUse",
            "Turn",
            "UserClassifier",
            "hunk_overlap",
            "native_user_classifier",
            "result_index",
        ),
        "cc_transcript.facts": (
            "ToolFact",
            "command_prefix_counts",
            "mcp_summary",
            "tool_facts",
        ),
        "cc_transcript.evidence": (
            "CandidatePair",
            "GitFix",
            "git_corrections",
            "harvest_pairs",
            "match_corrections",
            "record_harvest",
        ),
        "cc_transcript.corrections": (
            "CORRECTIONS_DDL",
            "Correction",
            "CorrectionLog",
            "Origin",
        ),
        "cc_transcript.context": (
            "ContextWindow",
            "Fidelity",
            "HydratedWindow",
            "SchemaError",
            "TurnRef",
            "capture_window",
        ),
        "cc_transcript.render": ("Budget", "render_session", "render_tool_call", "render_turn"),
        "cc_transcript.notifications": ("Notifications",),
        "cc_transcript.query": ("FileRef", "Session", "SubagentIndex", "SubagentSession", "ToolCallQuery"),
        "cc_transcript.decisions": ("DECISIONS_DDL", "Action", "Decision", "DecisionLog"),
        "cc_transcript.disktruth": (
            "AttributionRange",
            "DiskTruth",
            "FileAttribution",
            "TreeTurn",
            "export_activity",
            "load_export",
        ),
        "cc_transcript.filterspec": (
            "ASSISTANTS",
            "JUNK_USER_MESSAGE_RE",
            "RESUME_PHRASE_SET",
            "STRUCTURAL_NOISE_RE",
            "TRIVIAL_ACK_SET",
            "USERS",
            "FilterSpec",
            "annotate_spec",
            "apply_spec",
            "keep",
            "labels_for",
        ),
        "cc_transcript.builders": (
            "NOISE_SPEC",
            "build_spec",
            "drop_compacted",
            "drop_empty",
            "drop_entrypoints",
            "drop_junk",
            "drop_meta_flag",
            "drop_phrases",
            "drop_short",
            "drop_sidechain",
            "drop_synthetic",
            "keep_only",
        ),
        "cc_transcript.watch": ("WatchEvent", "Watcher"),
    }.items()
    for name in names
}

__all__ = sorted(EXPORTS)


def __getattr__(name: str) -> object:
    if module := EXPORTS.get(name):
        return getattr(import_module(module), name)
    raise AttributeError(f"module 'cc_transcript' has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(EXPORTS)
