# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from cc_transcript import command
from cc_transcript import ids
from cc_transcript import models
from cc_transcript import tools
import collections.abc
import datetime
import os
import pathlib
import typing
__all__ = [
    "ApiError",
    "AskUserQuestionResult",
    "AssistantEvent",
    "AsyncHookResponse",
    "AttachmentEvent",
    "Attribution",
    "BashCall",
    "BashResult",
    "CacheCreation",
    "CompactBoundary",
    "EditCall",
    "EditResult",
    "EditSpan",
    "EntryMeta",
    "EventList",
    "ExitPlanModeCall",
    "FallbackBlock",
    "GlobCall",
    "GrepCall",
    "HookAdditionalContext",
    "HookBlockingError",
    "HookCancelled",
    "HookInfo",
    "HookNonBlockingError",
    "HookSuccess",
    "Hunk",
    "InitInfo",
    "McpServer",
    "ModeEvent",
    "ModelRefusalFallback",
    "ModelUsage",
    "MultiEditCall",
    "NotebookEditCall",
    "OtherAttachment",
    "OtherBlock",
    "OtherCall",
    "OtherEvent",
    "OtherResult",
    "OtherSystemDetail",
    "ParseStream",
    "Plugin",
    "PreservedMessages",
    "PreservedSegment",
    "PrintMessage",
    "PrintResult",
    "Question",
    "QuestionAnnotation",
    "QueuedCommand",
    "ReadCall",
    "ReadResult",
    "RustCorrectionLog",
    "ServerToolUse",
    "SkillCall",
    "SkillResult",
    "StopHookSummary",
    "SystemEvent",
    "TaskCall",
    "TaskCreateCall",
    "TaskLaunchResult",
    "TaskResult",
    "TaskResultBase",
    "TaskUpdateCall",
    "TextBlock",
    "TextResult",
    "ThinkingBlock",
    "ToolCallBase",
    "ToolResultBase",
    "ToolResultBlock",
    "ToolUseBlock",
    "Transcript",
    "TurnDuration",
    "Usage",
    "UserEvent",
    "WatchTailer",
    "WorkflowCall",
    "WriteCall",
    "WriteResult",
    "activity_hunk_overlap",
    "activity_lift",
    "bucket_events",
    "command_parse",
    "command_prefixes",
    "context_capture_window",
    "context_render_preview",
    "context_roundtrip",
    "cost_of_json",
    "discovery_find_in",
    "discovery_find_transcript",
    "discovery_find_transcripts",
    "discovery_is_subagent_path",
    "discovery_subagent_paths",
    "discovery_subagent_transcripts",
    "embedded_literals",
    "expand_tool_names",
    "file_path_of",
    "hunks_of",
    "ids_canonical_json",
    "ids_tool_digest",
    "lexicon_has_hit",
    "lexicon_overrides",
    "lexicon_polarity",
    "lexicon_tokenize",
    "matches_names",
    "mcp_access",
    "mcp_parts",
    "mine_events",
    "nlp_analyze",
    "notifications_replay",
    "parse_bytes",
    "parse_print_result",
    "query_session",
    "render_compact_lines",
    "render_haystacks",
    "render_stats",
    "render_tool_call",
    "score_post_process",
    "score_short_circuit",
    "session_activity_probe",
    "stream_parse",
    "tool_facts",
    "tool_name_matches",
    "toolcall_parse",
    "toolcall_parse_view",
    "toolresult_parse",
    "toolresult_parse_view",
]

@typing.final
class ApiError:
    r"""
    The upstream API error an assistant turn failed with.
    
    Present on an :class:`AssistantEvent` only when the entry's
    ``isApiErrorMessage`` flag is set; each component is independently optional.
    
    Attributes:
        error: The error kind the API reported, e.g. ``rate_limit``, or None.
        status: The HTTP status of the failed request, e.g. ``429``, or None.
        details: The free-text error detail, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def error(self) -> typing.Optional[builtins.str]: ...
    @property
    def status(self) -> typing.Optional[builtins.int]: ...
    @property
    def details(self) -> typing.Optional[builtins.str]: ...

@typing.final
class AskUserQuestionResult(ToolResultBase):
    r"""
    An AskUserQuestion result: the rounds, the answers, and any annotations.
    
    Attributes:
        questions: The rounds echoed in the payload, lifted via
            :func:`~models.parse_questions`.
        answers: A mapping from each round's question text to the chosen answer.
            Non-string answer values are dropped, mirroring the Rust lift.
        annotations: A mapping from question text to the reviewer's
            :class:`QuestionAnnotation`, present only for annotated rounds.
            Non-string preview/notes leaves read as None, mirroring the Rust lift.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def answers(self) -> collections.abc.Mapping[str, str]: ...
    @property
    def annotations(self) -> collections.abc.Mapping[str, QuestionAnnotation]: ...
    @property
    def questions(self) -> tuple[Question, ...]:
        r"""
        The AskUserQuestion rounds echoed in the result payload.
        """

@typing.final
class AssistantEvent:
    r"""
    An assistant turn.
    
    Attributes:
        meta: The entry envelope metadata.
        model: The model that produced the turn, e.g. ``<synthetic>``.
        text: The joined text of the turn.
        blocks: The parsed content blocks, including thinking and tool uses.
        stop_reason: The model's stop reason, when present.
        usage: Token usage for the turn, or None when the entry carries no usage
            (older transcripts, API-error messages).
        request_id: The API request id that produced the turn, or None.
        forked_from: The id of the message this turn was forked from, or None.
        attribution: The plugin/skill/MCP attribution for the turn, or None when the
            entry carries no attribution field.
        api_error: The upstream API error the turn failed with, or None when the
            entry is not an API-error message.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def meta(self) -> EntryMeta: ...
    @property
    def model(self) -> builtins.str: ...
    @property
    def text(self) -> builtins.str: ...
    @property
    def blocks(self) -> tuple[models.ContentBlock, ...]: ...
    @property
    def stop_reason(self) -> typing.Optional[builtins.str]: ...
    @property
    def usage(self) -> typing.Optional[Usage]: ...
    @property
    def request_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def forked_from(self) -> typing.Optional[builtins.str]: ...
    @property
    def attribution(self) -> typing.Optional[Attribution]: ...
    @property
    def api_error(self) -> typing.Optional[ApiError]: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class AsyncHookResponse:
    r"""
    The result of an asynchronously-executed hook, matched back by process id.
    
    Attributes:
        hook_name: The hook matcher that fired, or None.
        hook_event: The lifecycle event that triggered it, or None.
        process_id: The async execution's process id, or None.
        stdout: The hook's captured stdout, or None.
        stderr: The hook's captured stderr, or None.
        exit_code: The hook's exit status, or None.
        response: The verbatim ``response`` payload, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def hook_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def hook_event(self) -> typing.Optional[builtins.str]: ...
    @property
    def process_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def stdout(self) -> typing.Optional[builtins.str]: ...
    @property
    def stderr(self) -> typing.Optional[builtins.str]: ...
    @property
    def exit_code(self) -> typing.Optional[builtins.int]: ...
    @property
    def response(self) -> collections.abc.Mapping[str, typing.Any] | None: ...

@typing.final
class AttachmentEvent:
    r"""
    A harness attachment record — a hook firing, a queued command, or an
    informational injection — carrying the full envelope it was written with.
    
    Recognized attachment types carry their typed :class:`AttachmentDetail`;
    every other type carries the full record verbatim under
    :class:`OtherAttachment`, so no attachment is lossy.
    
    Attributes:
        meta: The entry envelope metadata.
        attachment_type: The raw ``attachment.type`` string, e.g. ``hook_success``.
        detail: The typed attachment payload.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def meta(self) -> EntryMeta: ...
    @property
    def attachment_type(self) -> builtins.str: ...
    @property
    def detail(self) -> models.AttachmentDetail: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class Attribution:
    r"""
    The plugin, skill, or MCP tool an assistant turn is attributed to.
    
    Present on an :class:`AssistantEvent` only when the entry carries at least one
    of the four attribution fields; each component is independently optional.
    
    Attributes:
        plugin: The plugin the turn is attributed to, or None.
        skill: The skill the turn is attributed to, or None.
        mcp_server: The MCP server the turn is attributed to, or None.
        mcp_tool: The MCP tool the turn is attributed to, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def plugin(self) -> typing.Optional[builtins.str]: ...
    @property
    def skill(self) -> typing.Optional[builtins.str]: ...
    @property
    def mcp_server(self) -> typing.Optional[builtins.str]: ...
    @property
    def mcp_tool(self) -> typing.Optional[builtins.str]: ...

@typing.final
class BashCall(ToolCallBase):
    r"""
    A Bash/Execute shell invocation.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def command(self) -> builtins.str: ...
    @property
    def timeout(self) -> int | None: ...
    @property
    def description(self) -> str | None: ...
    @property
    def run_in_background(self) -> bool | None: ...
    @property
    def command_line(self) -> command.CommandLine:
        r"""
        The command parsed into a :class:`~command.CommandLine`.
        """

@typing.final
class BashResult(ToolResultBase):
    r"""
    A Bash/Execute execution result.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def stdout(self) -> str | None: ...
    @property
    def stderr(self) -> str | None: ...
    @property
    def interrupted(self) -> bool: ...
    @property
    def is_image(self) -> bool: ...
    @property
    def no_output_expected(self) -> bool: ...
    @property
    def background_task_id(self) -> str | None: ...
    @property
    def return_code_interpretation(self) -> str | None: ...

@typing.final
class CacheCreation:
    r"""
    The split of cache-creation input tokens by TTL bucket.
    
    Attributes:
        ephemeral_5m_input_tokens: Cache-creation tokens written to the 5-minute TTL bucket.
        ephemeral_1h_input_tokens: Cache-creation tokens written to the 1-hour TTL bucket.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def ephemeral_5m_input_tokens(self) -> builtins.int: ...
    @property
    def ephemeral_1h_input_tokens(self) -> builtins.int: ...

@typing.final
class CompactBoundary:
    r"""
    The typed detail of a ``compact_boundary`` system entry.
    
    Attributes:
        trigger: What triggered the compaction, such as ``manual`` or ``auto``.
        pre_tokens: The context token count before compaction.
        post_tokens: The context token count after compaction.
        duration_ms: The compaction's wall-clock duration in milliseconds.
        cumulative_dropped_tokens: The session's running total of tokens dropped
            by compactions.
        pre_compact_discovered_tools: The tool names discovered before compaction.
        preserved_segment: The head/anchor/tail segment preserved, when recorded.
        preserved_messages: The preserved message uuids, when recorded.
        logical_parent_uuid: The uuid the post-compaction thread logically
            continues from.
        precomputed: Whether the compaction was precomputed, when recorded.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def trigger(self) -> typing.Optional[builtins.str]: ...
    @property
    def pre_tokens(self) -> typing.Optional[builtins.int]: ...
    @property
    def post_tokens(self) -> typing.Optional[builtins.int]: ...
    @property
    def duration_ms(self) -> typing.Optional[builtins.int]: ...
    @property
    def cumulative_dropped_tokens(self) -> typing.Optional[builtins.int]: ...
    @property
    def pre_compact_discovered_tools(self) -> tuple[str, ...]: ...
    @property
    def preserved_segment(self) -> typing.Optional[PreservedSegment]: ...
    @property
    def preserved_messages(self) -> typing.Optional[PreservedMessages]: ...
    @property
    def logical_parent_uuid(self) -> ids.EventUuid | None: ...
    @property
    def precomputed(self) -> typing.Optional[builtins.bool]: ...

@typing.final
class EditCall(ToolCallBase):
    r"""
    An Edit replacement of ``old`` with ``new`` in one file.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def file_path(self) -> builtins.str: ...
    @property
    def old(self) -> builtins.str: ...
    @property
    def new(self) -> builtins.str: ...
    @property
    def replace_all(self) -> bool: ...

@typing.final
class EditResult(ToolResultBase):
    r"""
    An Edit result: the applied replacement and its structured patch.
    
    ``structured_patch`` and ``original_file`` are kept verbatim — the patch as
    the raw hunk list Claude Code emits, the original file as its full text.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def old_string(self) -> str | None: ...
    @property
    def new_string(self) -> str | None: ...
    @property
    def replace_all(self) -> bool: ...
    @property
    def user_modified(self) -> bool: ...
    @property
    def stale_recovered(self) -> bool: ...
    @property
    def structured_patch(self) -> list[typing.Any] | None: ...
    @property
    def original_file(self) -> str | None: ...

@typing.final
class EditSpan:
    r"""
    One replacement within a MultiEdit call, in application order.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def old(self) -> builtins.str: ...
    @property
    def new(self) -> builtins.str: ...
    @property
    def replace_all(self) -> builtins.bool: ...
    def __new__(cls, old: builtins.str, new: builtins.str, replace_all: builtins.bool = False) -> EditSpan: ...

@typing.final
class EntryMeta:
    r"""
    Envelope metadata shared by the conversational transcript events.
    
    Attributes:
        uuid: The entry's unique identifier.
        parent_uuid: The parent entry's id, or None for roots.
        session_id: The session this entry belongs to.
        timestamp: The entry's timezone-aware timestamp.
        cwd: The working directory recorded for the entry.
        git_branch: The git branch recorded for the entry.
        cc_version: The Claude Code version that wrote the entry.
        is_sidechain: Whether the entry belongs to a subagent sidechain.
        is_meta: Whether the entry is a meta entry injected by the client.
        entrypoint: The entrypoint that produced the entry, e.g. ``cli``.
        is_compact_summary: Whether the entry is a compaction summary.
        is_visible_in_transcript_only: Whether the entry is transcript-only.
        user_type: The ``userType`` recorded for the entry, e.g. ``external``, or None when absent.
        slug: The session slug recorded for the entry, or None when absent.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def uuid(self) -> ids.EventUuid: ...
    @property
    def parent_uuid(self) -> ids.EventUuid | None: ...
    @property
    def session_id(self) -> ids.SessionId: ...
    @property
    def timestamp(self) -> datetime.datetime: ...
    @property
    def cwd(self) -> typing.Optional[builtins.str]: ...
    @property
    def git_branch(self) -> typing.Optional[builtins.str]: ...
    @property
    def cc_version(self) -> models.CcVersion | None: ...
    @property
    def is_sidechain(self) -> builtins.bool: ...
    @property
    def is_meta(self) -> builtins.bool: ...
    @property
    def entrypoint(self) -> typing.Optional[builtins.str]: ...
    @property
    def is_compact_summary(self) -> builtins.bool: ...
    @property
    def is_visible_in_transcript_only(self) -> builtins.bool: ...
    @property
    def user_type(self) -> typing.Optional[builtins.str]: ...
    @property
    def slug(self) -> typing.Optional[builtins.str]: ...

@typing.final
class EventList(collections.abc.Sequence[models.TranscriptEvent]):
    r"""
    A lazily-materializing sequence of transcript events over one parse output.
    
    Implements the immutable ``collections.abc.Sequence`` interface — indexing,
    slicing, iteration, ``len``, ``in``, :func:`reversed`, ``index``, and
    ``count`` — and is registered as a virtual ``Sequence``. ``copy()`` returns a
    plain ``list``, and ``==`` is elementwise against any list, tuple, or
    ``EventList`` (``list(events) == events``). Views materialize fresh on each
    access, so identity across accesses is not guaranteed by design
    (``events[0] is events[0]`` is False). ``copy.copy`` and ``copy.deepcopy``
    return the immutable list itself; pickle is unsupported. Like the
    :class:`Transcript` it comes from, retaining any event pins the whole parse.
    """
    def __len__(self) -> builtins.int: ...
    @typing.overload
    def __getitem__(self, index: int) -> models.TranscriptEvent: ...
    @typing.overload
    def __getitem__(self, index: slice) -> list[models.TranscriptEvent]: ...
    def __reversed__(self) -> collections.abc.Iterator[models.TranscriptEvent]: ...
    def index(self, value: models.TranscriptEvent, start: builtins.int = 0, stop: typing.Optional[builtins.int] = None) -> builtins.int: ...
    def count(self, value: models.TranscriptEvent) -> builtins.int: ...
    def copy(self) -> list[models.TranscriptEvent]: ...
    def __eq__(self, other: typing.Any) -> typing.Any: ...

@typing.final
class ExitPlanModeCall(ToolCallBase):
    r"""
    An ExitPlanMode/ExitSpecMode plan submission.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def plan(self) -> builtins.str: ...

@typing.final
class FallbackBlock:
    r"""
    A marker that the assistant turn fell back from one model to another.
    
    Claude Code records this when a turn switches models mid-stream; it carries
    no message content, only the two model names.
    
    Attributes:
        from_model: The model the turn started on.
        to_model: The model the turn fell back to.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def from_model(self) -> builtins.str: ...
    @property
    def to_model(self) -> builtins.str: ...

@typing.final
class GlobCall(ToolCallBase):
    r"""
    A Glob file-pattern search.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def pattern(self) -> builtins.str: ...
    @property
    def path(self) -> str | None: ...

@typing.final
class GrepCall(ToolCallBase):
    r"""
    A Grep content search.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def pattern(self) -> builtins.str: ...
    @property
    def path(self) -> str | None: ...
    @property
    def glob(self) -> str | None: ...
    @property
    def file_type(self) -> str | None: ...
    @property
    def output_mode(self) -> str | None: ...

@typing.final
class HookAdditionalContext:
    r"""
    Context a hook injected into the turn without blocking it.
    
    Attributes:
        hook_name: The hook matcher that fired, or None.
        hook_event: The lifecycle event that triggered it, or None.
        tool_use_id: The tool-use the hook ran against, or None.
        content: The injected context lines, in order.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def hook_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def hook_event(self) -> typing.Optional[builtins.str]: ...
    @property
    def tool_use_id(self) -> ids.ToolUseId | None: ...
    @property
    def content(self) -> tuple[str, ...]: ...

@typing.final
class HookBlockingError:
    r"""
    A hook that blocked the turn, carrying the structured blocking payload.
    
    Attributes:
        hook_name: The hook matcher that fired, or None.
        hook_event: The lifecycle event that triggered it, or None.
        tool_use_id: The tool-use the hook ran against, or None.
        blocking_error: The verbatim ``blockingError`` payload, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def hook_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def hook_event(self) -> typing.Optional[builtins.str]: ...
    @property
    def tool_use_id(self) -> ids.ToolUseId | None: ...
    @property
    def blocking_error(self) -> collections.abc.Mapping[str, typing.Any] | None: ...

@typing.final
class HookCancelled:
    r"""
    A hook the harness cancelled, typically on timeout.
    
    Attributes:
        hook_name: The hook matcher that fired, or None.
        hook_event: The lifecycle event that triggered it, or None.
        tool_use_id: The tool-use the hook ran against, or None.
        command: The hook command line, or None.
        duration_ms: How long it ran before cancellation, or None.
        timed_out: Whether the cancellation was a timeout, or None.
        timeout_ms: The configured timeout in milliseconds, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def hook_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def hook_event(self) -> typing.Optional[builtins.str]: ...
    @property
    def tool_use_id(self) -> ids.ToolUseId | None: ...
    @property
    def command(self) -> typing.Optional[builtins.str]: ...
    @property
    def duration_ms(self) -> typing.Optional[builtins.int]: ...
    @property
    def timed_out(self) -> typing.Optional[builtins.bool]: ...
    @property
    def timeout_ms(self) -> typing.Optional[builtins.int]: ...

@typing.final
class HookInfo:
    r"""
    One hook invocation recorded in a stop-hook summary.
    
    Attributes:
        command: The hook command that ran.
        duration_ms: The hook's wall-clock duration in milliseconds, when recorded.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def command(self) -> builtins.str: ...
    @property
    def duration_ms(self) -> typing.Optional[builtins.int]: ...

@typing.final
class HookNonBlockingError:
    r"""
    A hook that failed without blocking the turn.
    
    Attributes:
        hook_name: The hook matcher that fired, or None.
        hook_event: The lifecycle event that triggered it, or None.
        tool_use_id: The tool-use the hook ran against, or None.
        command: The hook command line, or None.
        stdout: The hook's captured stdout, or None.
        stderr: The hook's captured stderr, or None.
        exit_code: The hook's exit status, or None.
        duration_ms: The hook's wall-clock duration in milliseconds, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def hook_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def hook_event(self) -> typing.Optional[builtins.str]: ...
    @property
    def tool_use_id(self) -> ids.ToolUseId | None: ...
    @property
    def command(self) -> typing.Optional[builtins.str]: ...
    @property
    def stdout(self) -> typing.Optional[builtins.str]: ...
    @property
    def stderr(self) -> typing.Optional[builtins.str]: ...
    @property
    def exit_code(self) -> typing.Optional[builtins.int]: ...
    @property
    def duration_ms(self) -> typing.Optional[builtins.int]: ...

@typing.final
class HookSuccess:
    r"""
    A hook that fired and exited cleanly, attached to the turn it ran on.
    
    Attributes:
        hook_name: The hook matcher that fired, e.g. ``PostToolUse:Bash``, or None.
        hook_event: The lifecycle event that triggered it, e.g. ``PostToolUse``, or None.
        tool_use_id: The tool-use the hook ran against, or None for lifecycle hooks.
        command: The hook command line, or None.
        content: The additional context the hook injected, or None.
        stdout: The hook's captured stdout, or None.
        stderr: The hook's captured stderr, or None.
        exit_code: The hook's exit status, or None.
        duration_ms: The hook's wall-clock duration in milliseconds, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def hook_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def hook_event(self) -> typing.Optional[builtins.str]: ...
    @property
    def tool_use_id(self) -> ids.ToolUseId | None: ...
    @property
    def command(self) -> typing.Optional[builtins.str]: ...
    @property
    def content(self) -> typing.Optional[builtins.str]: ...
    @property
    def stdout(self) -> typing.Optional[builtins.str]: ...
    @property
    def stderr(self) -> typing.Optional[builtins.str]: ...
    @property
    def exit_code(self) -> typing.Optional[builtins.int]: ...
    @property
    def duration_ms(self) -> typing.Optional[builtins.int]: ...

@typing.final
class Hunk:
    r"""
    A before/after content pair lowered from an edit-shaped tool call.
    
    Attributes:
        old: The content replaced; empty for pure additions such as Write.
        new: The content written.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def old(self) -> builtins.str: ...
    @property
    def new(self) -> builtins.str: ...
    def __new__(cls, old: builtins.str, new: builtins.str) -> Hunk: ...

@typing.final
class InitInfo:
    r"""
    The session init snapshot from a -p system/init element.
    
    Attributes:
        mcp_servers: The MCP servers configured for the session.
        plugins: The plugins loaded for the session.
        tools: The tool names available to the session.
        skills: The skill names available to the session.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def mcp_servers(self) -> tuple[McpServer, ...]: ...
    @property
    def plugins(self) -> tuple[Plugin, ...]: ...
    @property
    def tools(self) -> tuple[str, ...]: ...
    @property
    def skills(self) -> tuple[str, ...]: ...

@typing.final
class McpServer:
    r"""
    An MCP server entry from the -p init element.
    
    Attributes:
        name: The configured name of the MCP server.
        status: The connection status reported for the server.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def status(self) -> builtins.str: ...

@typing.final
class ModeEvent:
    r"""
    A mode or permission-mode change marker.
    
    These entries carry only a session id on disk — no uuid, timestamp, or
    other envelope fields — so they hold a :attr:`session_id` directly rather
    than an :class:`EntryMeta`.
    
    Attributes:
        session_id: The session whose mode changed.
        channel: Which mode channel changed.
        value: The new mode value.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def session_id(self) -> ids.SessionId: ...
    @property
    def channel(self) -> typing.Literal["mode", "permission-mode"]: ...
    @property
    def value(self) -> builtins.str: ...

@typing.final
class ModelRefusalFallback:
    r"""
    The typed detail of a ``model_refusal_fallback`` system entry.
    
    Attributes:
        api_refusal_category: The refusal category the API reported, when present.
        api_refusal_explanation: The refusal explanation the API reported, when present.
        trigger: What triggered the fallback.
        direction: The fallback direction.
        original_model: The model that refused.
        fallback_model: The model fallen back to.
        retracted_message_uuids: The uuids of messages retracted by the fallback.
        refused_user_message_uuid: The user message uuid that drew the refusal,
            when present.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def api_refusal_category(self) -> typing.Optional[builtins.str]: ...
    @property
    def api_refusal_explanation(self) -> typing.Optional[builtins.str]: ...
    @property
    def trigger(self) -> typing.Optional[builtins.str]: ...
    @property
    def direction(self) -> typing.Optional[builtins.str]: ...
    @property
    def original_model(self) -> typing.Optional[builtins.str]: ...
    @property
    def fallback_model(self) -> typing.Optional[builtins.str]: ...
    @property
    def retracted_message_uuids(self) -> tuple[ids.EventUuid, ...]: ...
    @property
    def refused_user_message_uuid(self) -> ids.EventUuid | None: ...

@typing.final
class ModelUsage:
    r"""
    Per-model token usage and cost from a -p (print mode) result's modelUsage map.
    
    Attributes:
        input_tokens: The number of input tokens consumed by the model.
        output_tokens: The number of output tokens produced by the model.
        cache_read_input_tokens: The number of input tokens served from the cache.
        cache_creation_input_tokens: The flat total of input tokens written to the cache.
        web_search_requests: The number of server-side web-search requests billed to the model.
        cost_usd: The cost in USD attributed to the model.
        context_window: The model's context window size in tokens.
        max_output_tokens: The model's maximum output token budget.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def input_tokens(self) -> builtins.int: ...
    @property
    def output_tokens(self) -> builtins.int: ...
    @property
    def cache_read_input_tokens(self) -> builtins.int: ...
    @property
    def cache_creation_input_tokens(self) -> builtins.int: ...
    @property
    def web_search_requests(self) -> builtins.int: ...
    @property
    def cost_usd(self) -> builtins.float: ...
    @property
    def context_window(self) -> builtins.int: ...
    @property
    def max_output_tokens(self) -> builtins.int: ...

@typing.final
class MultiEditCall(ToolCallBase):
    r"""
    A MultiEdit applying ``edits`` to one file, in order.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def file_path(self) -> builtins.str: ...
    @property
    def edits(self) -> tuple[EditSpan, ...]: ...

@typing.final
class NotebookEditCall(ToolCallBase):
    r"""
    A NotebookEdit replacing a cell's source.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def notebook_path(self) -> builtins.str: ...
    @property
    def new_source(self) -> builtins.str: ...
    @property
    def cell_id(self) -> str | None: ...
    @property
    def edit_mode(self) -> str | None: ...

@typing.final
class OtherAttachment:
    r"""
    Any attachment whose type has no typed detail, carried verbatim.
    
    Covers the many informational attachment types (skill/tool/agent listings,
    reminders, plan-mode markers, file references, and anything future) whose
    shape is not further decomposed, mirroring :class:`OtherSystemDetail`.
    
    Attributes:
        raw: The attachment entry's full decoded payload.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def raw(self) -> collections.abc.Mapping[str, typing.Any]: ...

@typing.final
class OtherBlock:
    r"""
    Any assistant content block whose ``type`` is not yet modeled.
    
    The escape hatch that keeps an unrecognized block from crashing the parser
    as Claude Code's transcript format evolves, mirroring :class:`OtherEvent`.
    
    Attributes:
        type: The block's ``type`` field.
        raw: The block's full decoded payload.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def type(self) -> builtins.str: ...
    @property
    def raw(self) -> collections.abc.Mapping[str, typing.Any]: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: typing.Any) -> typing.Any: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class OtherCall(ToolCallBase):
    r"""
    A tool the platform does not type: unknown names, MCP tools, and — under
    ``on_error='other'`` — known tools whose input failed to parse.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...

@typing.final
class OtherEvent:
    r"""
    Any recognized entry without a guaranteed conversational envelope.
    
    Covers ai-title, last-prompt, summary, queue-operation,
    file-history-snapshot, and similar entry types whose shape carries no
    :class:`EntryMeta`. Attachments are typed separately as
    :class:`AttachmentEvent`.
    
    Attributes:
        type: The entry's ``type`` field.
        raw: The entry's full decoded payload.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def type(self) -> builtins.str: ...
    @property
    def raw(self) -> collections.abc.Mapping[str, typing.Any]: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: typing.Any) -> typing.Any: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class OtherResult(ToolResultBase):
    r"""
    A tool result the platform does not type: unknown tools, untyped tools
    (such as TodoWrite), and known tools whose payload shape did not match.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...

@typing.final
class OtherSystemDetail:
    r"""
    The catch-all detail for a system entry without a typed subtype.
    
    Carries the entry's full decoded payload verbatim, so no system entry is
    lossy regardless of subtype.
    
    Attributes:
        raw: The entry's full decoded payload.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def raw(self) -> collections.abc.Mapping[str, typing.Any]: ...

@typing.final
class ParseStream:
    def recv(self) -> Transcript | None: ...
    def recv_many(self, max: builtins.int) -> list[Transcript]: ...

@typing.final
class Plugin:
    r"""
    A plugin entry from the -p init element.
    
    Attributes:
        name: The plugin's name.
        path: The filesystem path the plugin was loaded from.
        source: The source the plugin was installed from.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def path(self) -> builtins.str: ...
    @property
    def source(self) -> builtins.str: ...

@typing.final
class PreservedMessages:
    r"""
    The message uuids preserved across a compaction.
    
    Attributes:
        anchor_uuid: The anchor event's uuid.
        uuids: The uuids of the preserved messages, in order.
        all_uuids: The uuids of every message considered for preservation,
            in order.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def anchor_uuid(self) -> ids.EventUuid | None: ...
    @property
    def uuids(self) -> tuple[ids.EventUuid, ...]: ...
    @property
    def all_uuids(self) -> tuple[ids.EventUuid, ...]: ...

@typing.final
class PreservedSegment:
    r"""
    The head/anchor/tail uuids of the segment preserved across a compaction.
    
    Attributes:
        head_uuid: The first preserved event's uuid.
        anchor_uuid: The anchor event's uuid.
        tail_uuid: The last preserved event's uuid.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def head_uuid(self) -> ids.EventUuid | None: ...
    @property
    def anchor_uuid(self) -> ids.EventUuid | None: ...
    @property
    def tail_uuid(self) -> ids.EventUuid | None: ...

@typing.final
class PrintMessage:
    r"""
    A conversational message lifted from a -p (print mode) result.
    
    Unlike on-disk events it carries no EntryMeta — the -p element shape lacks
    timestamp/parentUuid — so it holds only role, model, text, blocks, and the ids
    that are present.
    
    Attributes:
        role: The author of the message, either "user" or "assistant".
        model: The model that produced the message, when present.
        text: The flattened text of the message.
        blocks: The structured content blocks of the message.
        uuid: The message's event uuid, when present.
        session_id: The session the message belongs to.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def role(self) -> typing.Literal["user", "assistant"]: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    @property
    def text(self) -> builtins.str: ...
    @property
    def blocks(self) -> tuple[models.ContentBlock, ...]: ...
    @property
    def uuid(self) -> ids.EventUuid | None: ...
    @property
    def session_id(self) -> ids.SessionId: ...

@typing.final
class PrintResult:
    r"""
    A parsed 'claude -p --output-format json' result.
    
    Holds the billing/usage/structured-output payload, the init snapshot, and the
    conversational messages. Reuses the shared Usage model; not a TranscriptEvent.
    
    Attributes:
        total_cost_usd: The total cost in USD for the run.
        model_usage: Per-model usage and cost, keyed by model name.
        usage: The aggregate token usage for the run.
        structured_output: The structured output payload, when present.
        num_turns: The number of turns in the run.
        is_error: Whether the run ended in an error.
        result: The final result text, when present.
        session_id: The session the run belongs to.
        fast_mode_state: The fast-mode state reported for the run, when present.
        stop_reason: The reason the run stopped, when present.
        permission_denials: The permission denials recorded during the run.
        init: The session init snapshot, when present.
        messages: The conversational messages of the run.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def total_cost_usd(self) -> builtins.float: ...
    @property
    def model_usage(self) -> collections.abc.Mapping[str, ModelUsage]: ...
    @property
    def usage(self) -> Usage: ...
    @property
    def structured_output(self) -> collections.abc.Mapping[str, typing.Any] | None: ...
    @property
    def num_turns(self) -> builtins.int: ...
    @property
    def is_error(self) -> builtins.bool: ...
    @property
    def result(self) -> typing.Optional[builtins.str]: ...
    @property
    def session_id(self) -> ids.SessionId: ...
    @property
    def fast_mode_state(self) -> typing.Optional[builtins.str]: ...
    @property
    def stop_reason(self) -> typing.Optional[builtins.str]: ...
    @property
    def permission_denials(self) -> tuple[collections.abc.Mapping[str, typing.Any], ...]: ...
    @property
    def init(self) -> typing.Optional[InitInfo]: ...
    @property
    def messages(self) -> tuple[PrintMessage, ...]: ...

@typing.final
class Question:
    r"""
    One AskUserQuestion round lifted from a tool-use input's ``questions`` array.
    
    Attributes:
        question: The prompt text shown to the user.
        header: The round's short header, or None when the input omits one.
        multi_select: Whether the round accepted more than one selection.
        labels: The option labels offered, in presentation order.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def question(self) -> builtins.str: ...
    @property
    def header(self) -> typing.Optional[builtins.str]: ...
    @property
    def multi_select(self) -> builtins.bool: ...
    @property
    def labels(self) -> tuple[str, ...]: ...
    def __new__(cls, question: builtins.str, header: typing.Optional[builtins.str], multi_select: builtins.bool, labels: typing.Sequence[builtins.str]) -> Question: ...

@typing.final
class QuestionAnnotation:
    r"""
    A reviewer's annotation on one answered AskUserQuestion round.
    
    Attributes:
        preview: The short preview the picker rendered under the answer, if any.
        notes: The free-text note the reviewer attached, if any.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def preview(self) -> typing.Optional[builtins.str]: ...
    @property
    def notes(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, preview: typing.Optional[builtins.str] = None, notes: typing.Optional[builtins.str] = None) -> QuestionAnnotation: ...

@typing.final
class QueuedCommand:
    r"""
    A user command queued for delivery to the agent, replayed as an attachment.
    
    Attributes:
        prompt: The queued command's prompt text, or None when it carries no
            plain-string prompt (e.g. an image-paste payload).
        command_mode: How the command was queued, e.g. ``prompt`` or
            ``task-notification``, or None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def prompt(self) -> typing.Optional[builtins.str]: ...
    @property
    def command_mode(self) -> typing.Optional[builtins.str]: ...

@typing.final
class ReadCall(ToolCallBase):
    r"""
    A Read of a file, optionally windowed.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def file_path(self) -> builtins.str: ...
    @property
    def offset(self) -> int | None: ...
    @property
    def limit(self) -> int | None: ...

@typing.final
class ReadResult(ToolResultBase):
    r"""
    A Read result: the file payload and its content type.
    
    ``file`` is kept verbatim — the raw mapping (``filePath``, ``content``,
    ``numLines``, …) Claude Code emits for the read window.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def file(self) -> collections.abc.Mapping[str, typing.Any] | None: ...
    @property
    def type(self) -> str | None: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: typing.Any) -> typing.Any: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class RustCorrectionLog:
    def __new__(cls, path: builtins.str) -> RustCorrectionLog: ...
    def append(self, ts_ms: builtins.int, session_id: builtins.str, source: builtins.str, anchor_uuid: builtins.str, incorrect_digest: typing.Optional[builtins.str], incorrect_file: builtins.str, incorrect_old: builtins.str, incorrect_new: builtins.str, correction_origin: typing.Optional[builtins.str], correction_file: typing.Optional[builtins.str], correction_old: typing.Optional[builtins.str], correction_new: typing.Optional[builtins.str], correction_commit: typing.Optional[builtins.str], correction_text: typing.Optional[builtins.str], overlap: builtins.float, detail: typing.Any) -> None: ...
    def for_session(self, session_id: builtins.str) -> list[dict[str, typing.Any]]: ...
    def for_repo(self, repo: builtins.str) -> list[dict[str, typing.Any]]: ...
    def since(self, ts_ms: builtins.int, source: typing.Optional[builtins.str] = None) -> list[dict[str, typing.Any]]: ...
    def for_anchor(self, session_id: builtins.str, anchor_uuid: builtins.str) -> list[dict[str, typing.Any]]: ...
    def by_digest(self, session_id: builtins.str, incorrect_digest: builtins.str) -> list[dict[str, typing.Any]]: ...
    def sql(self, statement: builtins.str) -> list[dict[str, typing.Any]]: ...

@typing.final
class ServerToolUse:
    r"""
    Server-side tool invocation counts billed within a turn.
    
    Attributes:
        web_search_requests: The number of server-side web-search requests.
        web_fetch_requests: The number of server-side web-fetch requests.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def web_search_requests(self) -> builtins.int: ...
    @property
    def web_fetch_requests(self) -> builtins.int: ...

@typing.final
class SkillCall(ToolCallBase):
    r"""
    A Skill invocation.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def skill(self) -> builtins.str: ...
    @property
    def args(self) -> str | None: ...

@typing.final
class SkillResult(ToolResultBase):
    r"""
    A Skill invocation result.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def command_name(self) -> str | None: ...
    @property
    def success(self) -> bool: ...
    @property
    def allowed_tools(self) -> tuple[str, ...] | None: ...

@typing.final
class StopHookSummary:
    r"""
    The typed detail of a ``stop_hook_summary`` system entry.
    
    Attributes:
        hook_count: The number of hooks that ran.
        hook_infos: The per-hook command and duration records.
        hook_errors: The error strings raised by hooks.
        hook_additional_context: The extra context strings hooks contributed.
        prevented_continuation: Whether a hook blocked the turn from continuing.
        stop_reason: The reason the turn stopped, when recorded.
        has_output: Whether the hooks produced output.
        tool_use_id: The tool-use id the summary is tied to, when present.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def hook_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def hook_infos(self) -> tuple[HookInfo, ...]: ...
    @property
    def hook_errors(self) -> tuple[str, ...]: ...
    @property
    def hook_additional_context(self) -> tuple[str, ...]: ...
    @property
    def prevented_continuation(self) -> builtins.bool: ...
    @property
    def stop_reason(self) -> typing.Optional[builtins.str]: ...
    @property
    def has_output(self) -> builtins.bool: ...
    @property
    def tool_use_id(self) -> ids.ToolUseId | None: ...

@typing.final
class SystemEvent:
    r"""
    A system entry, such as a hook summary or notice.
    
    Attributes:
        meta: The entry envelope metadata.
        subtype: The system entry's subtype.
        content: The entry's text content, when present.
        level: The entry's severity level, when present.
        detail: The typed detail for the subtype — a :class:`StopHookSummary`,
            :class:`CompactBoundary`, :class:`TurnDuration`, or
            :class:`ModelRefusalFallback` when recognized, else an
            :class:`OtherSystemDetail` carrying the full payload. Always set.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def meta(self) -> EntryMeta: ...
    @property
    def subtype(self) -> builtins.str: ...
    @property
    def content(self) -> typing.Optional[builtins.str]: ...
    @property
    def level(self) -> typing.Optional[builtins.str]: ...
    @property
    def detail(self) -> models.SystemDetail: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class TaskCall(ToolCallBase):
    r"""
    An Agent/Task subagent dispatch.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def prompt(self) -> builtins.str: ...
    @property
    def agent_type(self) -> str | None: ...
    @property
    def model(self) -> str | None: ...
    @property
    def agent_name(self) -> str | None: ...
    @property
    def run_in_background(self) -> bool | None: ...

@typing.final
class TaskCreateCall(ToolCallBase):
    r"""
    A TaskCreate tracker entry.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def subject(self) -> builtins.str: ...
    @property
    def description(self) -> str | None: ...

@typing.final
class TaskLaunchResult(TaskResultBase):
    r"""
    An in-flight Agent/Task launch (async or backgrounded subagent).
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def agent_id(self) -> str | None: ...
    @property
    def output_file(self) -> str | None: ...
    @property
    def is_async(self) -> bool: ...
    @property
    def can_read_output_file(self) -> bool: ...
    @property
    def description(self) -> str | None: ...
    @property
    def prompt(self) -> str | None: ...
    @property
    def status(self) -> str | None: ...
    @property
    def resolved_model(self) -> str | None: ...

@typing.final
class TaskResult(TaskResultBase):
    r"""
    A completed Agent/Task subagent run.
    
    ``tool_stats``, ``usage``, and ``content`` are kept verbatim — the raw
    per-tool stats, usage mapping, and final content-block list the subagent
    returned.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def agent_id(self) -> str | None: ...
    @property
    def agent_type(self) -> str | None: ...
    @property
    def status(self) -> str | None: ...
    @property
    def total_duration_ms(self) -> int | None: ...
    @property
    def total_tokens(self) -> int | None: ...
    @property
    def total_tool_use_count(self) -> int | None: ...
    @property
    def tool_stats(self) -> collections.abc.Mapping[str, typing.Any] | None: ...
    @property
    def usage(self) -> collections.abc.Mapping[str, typing.Any] | None: ...
    @property
    def content(self) -> list[typing.Any] | None: ...
    @property
    def prompt(self) -> str | None: ...
    @property
    def resolved_model(self) -> str | None: ...

class TaskResultBase(ToolResultBase):
    r"""
    The Agent/Task result family head; :meth:`from_raw` picks the variant.
    
    A terminal run (``totalDurationMs``/``usage`` present) becomes a
    :class:`TaskResult`; an in-flight launch (``outputFile`` present) becomes a
    :class:`TaskLaunchResult`; a payload matching neither shape degrades to
    :class:`OtherResult` rather than an all-None variant.
    """
    ...

@typing.final
class TaskUpdateCall(ToolCallBase):
    r"""
    A TaskUpdate tracker change.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def task_id(self) -> builtins.str: ...
    @property
    def status(self) -> str | None: ...
    @property
    def subject(self) -> str | None: ...
    @property
    def description(self) -> str | None: ...

@typing.final
class TextBlock:
    r"""
    A text content block from a user or assistant message.
    
    Attributes:
        text: The block's literal text.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def text(self) -> builtins.str: ...

@typing.final
class TextResult(ToolResultBase):
    r"""
    A plain-string tool result — denials and other unstructured payloads.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def text(self) -> builtins.str: ...

@typing.final
class ThinkingBlock:
    r"""
    An extended-thinking content block emitted by the assistant.
    
    Attributes:
        thinking: The model's thinking text.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def thinking(self) -> builtins.str: ...

class ToolCallBase:
    r"""
    Common shape of every typed tool call.
    
    Attributes:
        name: The tool name exactly as invoked (aliases are not normalized —
            the digest must match what the hook saw).
        raw: The verbatim input mapping; the only digest substrate.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def raw(self) -> collections.abc.Mapping[str, typing.Any]: ...
    @property
    def digest(self) -> ids.ToolDigest:
        r"""
        The cross-language content digest of this call.
        """

class ToolResultBase:
    r"""
    Common shape of every typed tool result.
    
    Attributes:
        name: The tool name exactly as invoked (aliases are not normalized).
        raw: The verbatim ``toolUseResult`` payload — a mapping for structured
            results, a plain string for denials, or None when the record carried
            none. Excluded from equality and repr.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def raw(self) -> collections.abc.Mapping[str, typing.Any] | str | None: ...

@typing.final
class ToolResultBlock:
    r"""
    The result of a tool invocation, delivered in a user turn.
    
    Attributes:
        tool_use_id: The id of the originating tool-use block.
        content: The result text, flattened from string or block content.
        is_error: Whether the tool reported a failure.
        is_async: Whether the originating tool ran asynchronously — computed at
            the parse layer from :attr:`tool_use_result`'s ``isAsync`` marker,
            then stored (like :attr:`UserEvent.interrupted`).
        tool_use_result: The record-level ``toolUseResult`` payload verbatim — a
            mapping for structured results, a plain string for denials, or None
            when the record carried none. Pass a tool name and this payload to
            :func:`~tools.parse_tool_result` for the typed result.
            v14: a structured payload is a read-only
            :class:`~models.ReadOnlyDict`, like :attr:`ToolUseBlock.input`.
        denial_kind: The tool-denial kind, computed at the parse layer — the
            record-level ``toolDenialKind`` (``user-rejected`` for a human
            rejection, ``permission-rule`` for a hook/guard block) when present,
            else ``user-rejected`` when this error block carries the legacy denial
            banner, else None.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def tool_use_id(self) -> ids.ToolUseId: ...
    @property
    def content(self) -> builtins.str: ...
    @property
    def is_error(self) -> builtins.bool: ...
    @property
    def is_async(self) -> builtins.bool: ...
    @property
    def tool_use_result(self) -> collections.abc.Mapping[str, typing.Any] | str | None: ...
    @property
    def denial_kind(self) -> typing.Optional[builtins.str]: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class ToolUseBlock:
    r"""
    An assistant request to invoke a tool.
    
    Attributes:
        id: The tool-use identifier referenced by the matching result.
        name: The tool's name.
        input: The tool's input arguments, preserved verbatim. v14: a read-only
            :class:`~models.ReadOnlyDict` — the view is immutable, so
            the input cannot be mutated out of step with :attr:`call`/:attr:`digest`.
            It stays a ``dict`` (serializes and canonicalizes like one); only the top
            level is frozen, so nested containers keep their plain-JSON types.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def id(self) -> ids.ToolUseId: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def input(self) -> collections.abc.Mapping[str, typing.Any]:
        r"""
        The tool's input arguments, as a read-only mapping (v14: immutable view).
        """
    @property
    def call(self) -> tools.ToolCall:
        r"""
        The block parsed into the typed tool-call hierarchy.
        
        Strict: a known tool whose input is malformed raises
        :class:`~tools.ToolInputError`.
        """
    @property
    def digest(self) -> ids.ToolDigest:
        r"""
        The cross-language content digest of this call.
        """
    @property
    def file_path(self) -> typing.Optional[builtins.str]:
        r"""
        The raw ``file_path`` input argument when it is a string, else None.
        
        Mirrors the Rust parse-layer lift in ``rust/crates/core/src/parse.rs``: the value is
        read verbatim from the input for every tool, and a non-object input or a
        non-string value reads as None. Mining denial evidence consumes this uniform
        lift rather than the type-dispatched :func:`~tools.file_path_of`.
        """
    @property
    def questions(self) -> tuple[Question, ...] | None:
        r"""
        The AskUserQuestion rounds lifted from the ``questions`` input array, or None.
        
        Delegates to :func:`parse_questions`, which mirrors the Rust parse layer; a
        non-object input reads as None.
        """
    def __hash__(self) -> builtins.int: ...

@typing.final
class Transcript:
    r"""
    The parsed events of a single transcript file, backed by the native parse
    output; ``events`` materializes lazy views on access.
    
    One parse owns one ``Arc<Vec<Entry>>`` that every event and nested view shares,
    so retaining any single view keeps that whole parse's entries alive; keeping one
    event from each of several parses retains all of their entries. The live
    :class:`~watch.WatchEvent` stream is exempt — its tailer builds a
    one-entry Arc per yielded event, so a held watch event pins only itself.
    
    Attributes:
        path: The transcript's path on disk; None for a bytes parse.
        mtime: The transcript's modification time when parsed.
        events: The parsed events, in file order.
    """
    @property
    def path(self) -> typing.Optional[pathlib.Path]: ...
    @property
    def mtime(self) -> builtins.float: ...
    @property
    def events(self) -> EventList: ...

@typing.final
class TurnDuration:
    r"""
    The typed detail of a ``turn_duration`` system entry.
    
    Attributes:
        duration_ms: The turn's wall-clock duration in milliseconds.
        message_count: The number of messages in the turn.
        pending_workflow_count: The workflows still pending, when recorded.
        pending_background_agent_count: The background agents still pending, when
            recorded.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def duration_ms(self) -> typing.Optional[builtins.int]: ...
    @property
    def message_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def pending_workflow_count(self) -> typing.Optional[builtins.int]: ...
    @property
    def pending_background_agent_count(self) -> typing.Optional[builtins.int]: ...

@typing.final
class Usage:
    r"""
    Token usage and cache accounting for a single assistant turn or a -p (print mode) result.
    
    Exposes both the flat cache_creation_input_tokens and the per-TTL cache_creation
    split, faithfully and without opinion.
    
    Attributes:
        input_tokens: The number of input tokens consumed by the turn.
        output_tokens: The number of output tokens produced by the turn.
        cache_read_input_tokens: The number of input tokens served from the cache.
        cache_creation_input_tokens: The flat total of input tokens written to the cache.
        cache_creation: The per-TTL split of cache-creation tokens, when present.
        service_tier: The service tier that billed the turn, when present.
        inference_geo: The inference geography that served the turn, when present.
        server_tool_use: Server-side tool invocation counts, when present.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def input_tokens(self) -> builtins.int: ...
    @property
    def output_tokens(self) -> builtins.int: ...
    @property
    def cache_read_input_tokens(self) -> builtins.int: ...
    @property
    def cache_creation_input_tokens(self) -> builtins.int: ...
    @property
    def cache_creation(self) -> typing.Optional[CacheCreation]: ...
    @property
    def service_tier(self) -> typing.Optional[builtins.str]: ...
    @property
    def inference_geo(self) -> typing.Optional[builtins.str]: ...
    @property
    def server_tool_use(self) -> typing.Optional[ServerToolUse]: ...

@typing.final
class UserEvent:
    r"""
    A user turn.
    
    Attributes:
        meta: The entry envelope metadata.
        text: The joined text of the turn.
        blocks: The parsed content blocks, including tool results.
        interrupted: Whether the turn is a user interruption.
        is_agent_injected: Whether the turn is an agent-injected relay banner —
            a teammate-message digest, scheduled-task banner, or foreign-agent
            header — rather than an authored prompt.
        prompt_id: The client-assigned id of the prompt this turn belongs to, or None.
        prompt_source: How the prompt was submitted, e.g. ``typed``, ``queued``,
            ``system``, or ``sdk``, or None when absent.
        queue_priority: The queue priority recorded for a queued prompt, or None.
        image_paste_ids: The paste ids of images attached to the turn, or None when
            the turn carries no image-paste marker.
        source_tool_use_id: The id of the tool-use that produced this turn, when the
            turn originates from a tool result, else None.
        source_tool_assistant_uuid: The uuid of the assistant entry whose tool produced
            this turn, else None.
        mcp_meta: The verbatim ``mcpMeta`` payload attached to the turn, or None.
        permission_mode: The permission mode in effect for the turn, or None.
        interrupted_message_id: The API message id (``msg_...``) of the assistant
            turn this interruption cut short, or None. Set from the raw
            ``interruptedMessageId`` field; it names the interrupted assistant's
            API message, not a transcript event uuid.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def meta(self) -> EntryMeta: ...
    @property
    def text(self) -> builtins.str: ...
    @property
    def blocks(self) -> tuple[models.ContentBlock, ...]: ...
    @property
    def interrupted(self) -> builtins.bool: ...
    @property
    def is_agent_injected(self) -> builtins.bool: ...
    @property
    def prompt_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def prompt_source(self) -> typing.Optional[builtins.str]: ...
    @property
    def queue_priority(self) -> typing.Optional[builtins.str]: ...
    @property
    def image_paste_ids(self) -> tuple[int, ...] | None: ...
    @property
    def source_tool_use_id(self) -> ids.ToolUseId | None: ...
    @property
    def source_tool_assistant_uuid(self) -> ids.EventUuid | None: ...
    @property
    def mcp_meta(self) -> collections.abc.Mapping[str, typing.Any] | None: ...
    @property
    def permission_mode(self) -> typing.Optional[builtins.str]: ...
    @property
    def interrupted_message_id(self) -> typing.Optional[builtins.str]: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class WatchTailer:
    r"""
    A stateful tail over the transcript tree: one `tick` per poll, holding the
    per-file cursors between calls. The Python facade wraps it in the async
    poll-forever loop.
    """
    def __new__(cls) -> WatchTailer: ...
    def tick(self, roots: typing.Sequence[builtins.str], from_start: builtins.bool = False) -> list[tuple[str, str, bool, models.TranscriptEvent]]:
        r"""
        Run one poll step over `roots`, returning `(path, session_id,
        is_sidechain, event)` tuples for each freshly appended entry.
        """
    def snapshot(self) -> dict[str, typing.Any]:
        r"""
        The whole cursor state: `{"primed": bool, "cursors": {path: {offset,
        size, mtime, session_id, seen}}}`, the Python `TailState` projection.
        """

@typing.final
class WorkflowCall(ToolCallBase):
    r"""
    A Workflow dynamic-orchestration dispatch.
    
    Attributes:
        script: The inline workflow script, when passed directly.
        script_path: Path to a script file on disk, when passed instead of
            ``script``.
        workflow_name: A predefined workflow's name (``raw["name"]`` — distinct
            from :attr:`ToolCallBase.name`, the tool name).
        args: The value exposed to the script as its ``args`` global.
        resume_from_run_id: A prior run to resume from.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def script(self) -> str | None: ...
    @property
    def script_path(self) -> str | None: ...
    @property
    def workflow_name(self) -> str | None: ...
    @property
    def args(self) -> typing.Any: ...
    @property
    def resume_from_run_id(self) -> str | None: ...

@typing.final
class WriteCall(ToolCallBase):
    r"""
    A Write/Create of a whole file.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def file_path(self) -> builtins.str: ...
    @property
    def content(self) -> builtins.str: ...

@typing.final
class WriteResult(ToolResultBase):
    r"""
    A Write/Create result: the written content and its structured patch.
    """
    __match_args__: typing.ClassVar[tuple[str, ...]]
    @property
    def name(self) -> builtins.str: ...
    @property
    def content(self) -> str | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def original_file(self) -> str | None: ...
    @property
    def structured_patch(self) -> list[typing.Any] | None: ...
    @property
    def user_modified(self) -> bool: ...

def activity_hunk_overlap(a_old: builtins.str, a_new: builtins.str, b_old: builtins.str, b_new: builtins.str) -> builtins.float: ...

def activity_lift(path: builtins.str, max_events: builtins.int) -> dict[str, typing.Any]: ...

def bucket_events(raw: bytes) -> list[dict[str, typing.Any]]: ...

def command_parse(command: builtins.str) -> dict[str, typing.Any]: ...

def command_prefixes(commands: typing.Sequence[builtins.str]) -> builtins.list[builtins.list[builtins.str]]: ...

def context_capture_window(raw: bytes, session_id: builtins.str, anchor_uuid: builtins.str, anchor_tool_use_id: typing.Optional[builtins.str], before: builtins.int, after: builtins.int, preview_chars: builtins.int) -> builtins.str: ...

def context_render_preview(data: builtins.str, turn_chars: builtins.int) -> builtins.str: ...

def context_roundtrip(data: builtins.str) -> builtins.str: ...

def cost_of_json(usage_json: builtins.str, model: builtins.str) -> dict[str, float]: ...

def discovery_find_in(directory: builtins.str | os.PathLike | pathlib.Path, name_contains: typing.Optional[builtins.str] = None, limit: typing.Optional[builtins.int] = None, known_mtimes: dict[str, float] | None = None) -> builtins.list[tuple[pathlib.Path, builtins.float]]: ...

def discovery_find_transcript(root: builtins.str | os.PathLike | pathlib.Path, session_id: builtins.str) -> typing.Optional[pathlib.Path]: ...

def discovery_find_transcripts(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def discovery_is_subagent_path(path: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...

def discovery_subagent_paths(path: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def discovery_subagent_transcripts(path: builtins.str | os.PathLike | pathlib.Path) -> dict[str, pathlib.Path]: ...

def embedded_literals() -> dict[str, str | float | list[str]]: ...

def expand_tool_names(spec: builtins.str) -> frozenset[str]:
    r"""
    Expand a pipe-separated tool spec to include alias and MCP bare spellings.
    """

def file_path_of(call: tools.ToolCall | tools.FallbackCall) -> typing.Optional[builtins.str]:
    r"""
    The file a call targets, when it targets one.
    """

def hunks_of(call: tools.ToolCall | tools.FallbackCall) -> tuple[Hunk, ...]:
    r"""
    Lower an edit-shaped call to before/after hunks; ``()`` for the rest.
    
    MultiEdit yields one hunk per span in application order — never just the
    first. Write and NotebookEdit are pure additions with an empty old side.
    """

def ids_canonical_json(value_json: builtins.str) -> builtins.str: ...

def ids_tool_digest(name: builtins.str, input_json: builtins.str) -> builtins.str: ...

def lexicon_has_hit(text: builtins.str, want_negative: builtins.bool) -> builtins.bool: ...

def lexicon_overrides() -> builtins.list[tuple[builtins.str, builtins.int]]: ...

def lexicon_polarity(token: builtins.str) -> builtins.int: ...

def lexicon_tokenize(text: builtins.str) -> builtins.list[builtins.str]: ...

def matches_names(actual: builtins.str, names: collections.abc.Container[str]) -> builtins.bool:
    r"""
    Whether ``actual`` is one of ``names``, exactly or as an MCP tool suffix.
    
    True when ``actual`` is in ``names``, or when it splits as
    ``mcp__<server>__<tool>`` on the first two ``__`` and ``<tool>`` — or its
    :data:`MCP_TOOL_ALIASES` builtin equivalent — is in ``names``. That alias
    closes the edit-gate bypass where cc-context's ``ccx_code_edit`` /
    ``ccx_code_replace`` write through the MCP under names no ``Edit``/``Write``
    gate would catch. Harness-rename aliases are not closed over — ``names`` is
    taken verbatim; pre-expand with :func:`expand_tool_names` for those.
    
    Example:
        >>> matches_names("mcp__github__Grep", {"Grep"})
        True
        >>> matches_names("mcp__cc-context__ccx_code_edit", {"Edit"})
        True
        >>> matches_names("Execute", {"Bash"})
        False
    """

def mcp_access(tool: builtins.str) -> typing.Literal["read", "write"]:
    r"""
    Classify an MCP tool segment as ``"read"`` or ``"write"`` by its verbs.
    
    Returns ``"read"`` when ``tool`` starts with, or has an underscore-delimited
    token equal to, a read verb (``get``, ``list``, ``search``, …); otherwise
    ``"write"``. The token check catches namespaced names like ``ccx_read``.
    
    Example:
        >>> mcp_access("search")
        'read'
        >>> mcp_access("ccx_read")
        'read'
        >>> mcp_access("deploy")
        'write'
    """

def mcp_parts(name: builtins.str) -> tuple[str, str] | None:
    r"""
    Split an ``mcp__server__tool`` name into ``(server, tool)``, else ``None``.
    
    Example:
        >>> mcp_parts("mcp__semble__search")
        ('semble', 'search')
        >>> mcp_parts("Bash") is None
        True
    """

def mine_events(events: list[models.TranscriptEvent], spec_json: builtins.str, callable_formats: typing.Sequence[tuple[builtins.str, typing.Any, typing.Any]]) -> list[dict[str, typing.Any]]: ...

def nlp_analyze(text: builtins.str) -> builtins.list[tuple[builtins.str, builtins.str, builtins.str, builtins.str, builtins.int, builtins.int, builtins.int, builtins.bool]]:
    r"""
    Analyze `text` with the embedded UDPipe model. Returns, per token,
    `(form, lower, lemma, upos, char_start, char_end, polarity, negated)` where
    polarity is the surface-keyed lexicon score and offsets are codepoint indices.
    """

def notifications_replay(raw: bytes) -> dict[str, list[str]]: ...

def parse_bytes(raw: bytes, spec_json: typing.Optional[builtins.str] = None) -> Transcript: ...

def parse_print_result(raw: bytes) -> PrintResult: ...

def query_session(path: builtins.str, max_events: builtins.int) -> dict[str, typing.Any]: ...

def render_compact_lines(raw: bytes, width: builtins.int, thinking: builtins.bool, uuids: builtins.bool) -> builtins.list[builtins.str]: ...

def render_haystacks(raw: bytes, wheres: typing.Sequence[builtins.str]) -> builtins.list[builtins.str]: ...

def render_stats(raws: list[bytes]) -> builtins.str: ...

def render_tool_call(name: builtins.str, input_json: builtins.str, turn_chars: builtins.int, tool_chars: builtins.int) -> builtins.str: ...

def score_post_process(spec_json: builtins.str, buckets: typing.Sequence[typing.Sequence[builtins.str]], raw: typing.Sequence[builtins.int]) -> builtins.list[builtins.int]: ...

def score_short_circuit(spec_json: builtins.str, buckets: typing.Sequence[typing.Sequence[builtins.str]]) -> builtins.list[typing.Optional[builtins.int]]: ...

def session_activity_probe(path: builtins.str, waiting_tools: list[str] | None = None, human_facing_tools: list[str] | None = None) -> dict[str, typing.Any]: ...

def stream_parse(paths: typing.Sequence[tuple[builtins.str, builtins.float]], prefetch: builtins.int, spec_json: typing.Optional[builtins.str] = None) -> ParseStream: ...

def tool_facts(paths: typing.Sequence[builtins.str], max_events: builtins.int) -> list[dict[str, typing.Any]]: ...

def tool_name_matches(actual: builtins.str, spec: builtins.str) -> builtins.bool:
    r"""
    Whether ``actual`` matches a pipe spec, honoring aliases and MCP suffixes.
    
    Example:
        >>> tool_name_matches("Execute", "Bash|Grep")
        True
        >>> tool_name_matches("mcp__github__Grep", "Grep")
        True
    """

def toolcall_parse(name: builtins.str, input_json: builtins.str, on_error: typing.Optional[builtins.str] = None) -> dict[str, typing.Any]: ...

def toolcall_parse_view(name: builtins.str, input_json: builtins.str, on_error: typing.Optional[builtins.str] = None) -> tools.ToolCall:
    r"""
    Parse a tool's name and raw input (as a JSON document) into the typed view
    hierarchy; the ``cc_transcript.tools`` facade owns the public signature.
    """

def toolresult_parse(name: builtins.str, payload_json: builtins.str) -> dict[str, typing.Any]: ...

def toolresult_parse_view(name: builtins.str, payload_json: builtins.str) -> tools.ToolResult:
    r"""
    Parse a tool's name and ``toolUseResult`` payload (as a JSON document) into
    the typed view hierarchy; the ``cc_transcript.tools`` facade owns the public
    signature.
    """

