"""Declarative, both-backend filtering of a transcript event stream.

A :class:`FilterSpec` is an ordered list of :class:`Clause` rules — *filters as
data*. The same spec is interpreted by the Python interpreter here and, when
:func:`is_portable` holds, serialized via :func:`spec_to_json` and executed by
the Rust backend, which drops events before ever materializing a Python object.

Presets compose named building blocks: the junk regex is split into named groups
(:data:`STRUCTURAL_NOISE_GROUPS` / :data:`INTERRUPT_MARKER_GROUPS` /
:data:`STOP_HOOK_GROUPS`) so a consumer can drop structural noise while keeping
interrupt and stop-hook corrections.

Example:
    >>> from cc_transcript import apply_spec, PUSHBACK_SPEC
    >>> kept = list(apply_spec(events, PUSHBACK_SPEC))
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from functools import cache
from typing import TYPE_CHECKING, Literal

import orjson

from cc_transcript.models import AssistantEvent, ModeEvent, OtherEvent, SystemEvent, ToolUseBlock, UserEvent

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator
    from typing import Any

    from cc_transcript.models import EntryMeta, TranscriptEvent

EventKind = Literal["user", "assistant", "system", "mode", "other"]
MetaFlagName = Literal["is_sidechain", "is_meta", "is_compact_summary", "is_visible_in_transcript_only"]

TRAILING_PUNCT = ".!?…,;:"

STRUCTURAL_TAG_GROUP: tuple[str, str] = (
    "xml_tags",
    r"<(?:system[_-](?:instruction|reminder)"
    r"|local-command-(?:stdout|caveat)"
    r"|command-(?:name|message|args)"
    r"|task-notification"
    r"|persisted-output"
    r"|output-file)\b",
)

SENTIMENT_STRUCTURAL_GROUPS: tuple[tuple[str, str], ...] = (
    STRUCTURAL_TAG_GROUP,
    ("local_command_caveat", r"Caveat: The messages below were generated by the user while running local commands\."),
    ("remaining_tasks_ack", r"REMAINING_TASKS_ACKNOWLEDGED"),
    ("angle_token", r"<<[a-z][a-z0-9-]*>>"),
    ("skill_base_dir", r"^Base directory for this skill:"),
    ("hash_banner", r"(?:###\s+[\w][\w \-]{0,30}\s+){3,}###"),
)

# cc-pushback's additions, merged up so the superset lives here.
PUSHBACK_STRUCTURAL_EXTRA_GROUPS: tuple[tuple[str, str], ...] = (
    ("xml_tags_extra", r"<(?:teammate-message|scheduled-task)\b"),
    ("augment_agent", r"^# Augment Agent\b"),
)

INTERRUPT_MARKER_GROUPS: tuple[tuple[str, str], ...] = (("interrupt", r"\[Request interrupted by user"),)
STOP_HOOK_GROUPS: tuple[tuple[str, str], ...] = (("stop_hook", r"Stop hook feedback:"),)

# The superset of structural noise (cc-transcript ∪ cc-pushback), WITHOUT
# interrupt/stop-hook — those carry pushback and must never live here.
STRUCTURAL_NOISE_GROUPS: tuple[tuple[str, str], ...] = SENTIMENT_STRUCTURAL_GROUPS + PUSHBACK_STRUCTURAL_EXTRA_GROUPS

# The sentiment junk set: structural (narrow) + interrupt + stop-hook. This
# reproduces the historical monolithic JUNK_USER_MESSAGE_RE behavior.
SENTIMENT_JUNK_GROUPS: tuple[tuple[str, str], ...] = (
    SENTIMENT_STRUCTURAL_GROUPS + INTERRUPT_MARKER_GROUPS + STOP_HOOK_GROUPS
)

FRUSTRATION_GROUPS: tuple[tuple[str, str], ...] = (
    (
        "frustration",
        r"\b("
        r"wtf|wth|ffs|omfg|"
        r"fuck(?:ing)?\s*(?:broken|useless|stupid|terrible|awful|horrible|piece\s*of\s*shit)|"
        r"fuck\s*(?:you|this|it|off)|"
        r"screw\s*(?:you|this)|"
        r"piece\s*of\s*(?:shit|crap|junk)|"
        r"dumbass|"
        r"you'?re\s*(?:fucking\s*)?(?:useless|stupid|broken|terrible|awful)|"
        r"this\s*(?:is\s*)?(?:fucking\s*)?(?:terrible|awful|horrible|useless|garbage)|"
        r"stop\s+(?:guessing|making\s+(?:things|stuff|shit)\s*up|hallucinating|inventing|assuming"
        r"|pretending|being\s+lazy|making\s+excuses|lying)|"
        r"just\s+stop\s+(?:it|already)|"
        r"completely\s*useless|"
        r"i\s*give\s*up|giving\s*up"
        r")\b",
    ),
)

MILD_IMPATIENCE_GROUPS: tuple[tuple[str, str], ...] = (
    (
        "mild_impatience",
        r"\b("
        r"and\s+again|"
        r"yet\s+again|"
        r"once\s+again|"
        r"for\s+the\s+(?:second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|umpteenth|hundredth|nth)\s+time"
        r")\b",
    ),
)

PORTABLE_GROUP_NAMES: frozenset[str] = frozenset(
    name
    for name, _ in (
        *STRUCTURAL_NOISE_GROUPS,
        *INTERRUPT_MARKER_GROUPS,
        *STOP_HOOK_GROUPS,
        *FRUSTRATION_GROUPS,
        *MILD_IMPATIENCE_GROUPS,
    )
)

RESUME_PHRASE_SET: frozenset[str] = frozenset(
    {
        "continue",
        "continues",
        "continue please",
        "please continue",
        "resume",
        "resume please",
        "please resume",
        "go ahead",
        "keep going",
        "carry on",
        "proceed",
        "go on",
        "keep at it",
        "ok continue",
        "ok resume",
        "ok go ahead",
        "okay continue",
        "okay resume",
        "okay go ahead",
        "continue from where you left off",
        "continue where you left off",
        "continue your previous task",
        "[context restored] resume",
        "[context restored] continue",
        "[context restored] pick up the conversation",
    }
)

TRIVIAL_ACK_SET: frozenset[str] = frozenset(
    {
        "ok",
        "okay",
        "k",
        "kk",
        "yes",
        "yep",
        "yeah",
        "yup",
        "sure",
        "thanks",
        "thank you",
        "thx",
        "ty",
        "great",
        "perfect",
        "nice",
        "cool",
        "awesome",
        "done",
        "good",
        "lgtm",
        "got it",
        "sounds good",
        "looks good",
        "makes sense",
        "approved",
    }
)

SHORT_MESSAGE_MAX_WORDS = 3

CONVERSATIONAL: frozenset[EventKind] = frozenset({"user", "assistant"})
USERS: frozenset[EventKind] = frozenset({"user"})
ASSISTANTS: frozenset[EventKind] = frozenset({"assistant"})


class Action(Enum):
    """What a matching :class:`Clause` does to an event."""

    DROP = "drop"
    TAG = "tag"


@dataclass(frozen=True, slots=True)
class KindIs:
    """Matches events whose kind is in ``kinds``."""

    kinds: frozenset[EventKind]


@dataclass(frozen=True, slots=True)
class MetaFlag:
    """Matches when an :class:`~cc_transcript.models.EntryMeta` boolean is set."""

    flag: MetaFlagName


@dataclass(frozen=True, slots=True)
class EntrypointIn:
    """Matches when ``meta.entrypoint`` is in ``entrypoints``."""

    entrypoints: frozenset[str]


@dataclass(frozen=True, slots=True)
class ModelIs:
    """Matches assistant events whose ``model`` is in ``models``."""

    models: frozenset[str]


@dataclass(frozen=True, slots=True)
class TextEmpty:
    """Matches events with blank text.

    Attributes:
        consider_tool_use: When true, an assistant event with a tool-use block
            is not considered empty even with blank text.
    """

    consider_tool_use: bool = True


@dataclass(frozen=True, slots=True)
class TextMatchesAny:
    """Matches when the event text matches any of the named regex ``groups``.

    Attributes:
        groups: Ordered ``(name, pattern)`` pairs; names label composable,
            individually includable building blocks.
        ignore_case: Whether to compile case-insensitively.
    """

    groups: tuple[tuple[str, str], ...]
    ignore_case: bool = True


@dataclass(frozen=True, slots=True)
class TextInSet:
    """Matches when the normalized event text is in ``phrases``.

    Normalization mirrors a bare-message check: strip, drop trailing
    punctuation, strip again, lowercase.
    """

    phrases: frozenset[str]
    strip_trailing: str = TRAILING_PUNCT


@dataclass(frozen=True, slots=True)
class WordCountAtMost:
    """Matches when the event text has at most ``n`` whitespace-split words."""

    n: int


Predicate = KindIs | MetaFlag | EntrypointIn | ModelIs | TextEmpty | TextMatchesAny | TextInSet | WordCountAtMost


@dataclass(frozen=True, slots=True)
class Clause:
    """One filter rule: when ``predicate`` holds, apply ``action``.

    Attributes:
        predicate: The condition tested against an event.
        action: ``DROP`` removes the event (first drop wins, stops evaluation);
            ``TAG`` records ``label`` on a surviving event and continues.
        applies_to: When non-empty, the clause is only evaluated for these kinds.
        negate: Invert the predicate match.
        label: The label recorded by a ``TAG`` clause.
    """

    predicate: Predicate
    action: Action = Action.DROP
    applies_to: frozenset[EventKind] = frozenset()
    negate: bool = False
    label: str | None = None


@dataclass(frozen=True, slots=True)
class FilterSpec:
    """An ordered list of :class:`Clause` rules applied to an event stream."""

    clauses: tuple[Clause, ...]


@cache
def compile_groups(groups: tuple[tuple[str, str], ...], ignore_case: bool) -> re.Pattern[str]:
    return re.compile("|".join(f"(?:{pattern})" for _, pattern in groups), re.IGNORECASE if ignore_case else 0)


def event_kind(event: TranscriptEvent) -> EventKind:
    match event:
        case UserEvent():
            return "user"
        case AssistantEvent():
            return "assistant"
        case SystemEvent():
            return "system"
        case ModeEvent():
            return "mode"
        case OtherEvent():
            return "other"


def event_text(event: TranscriptEvent) -> str:
    match event:
        case UserEvent(text=text) | AssistantEvent(text=text):
            return text
        case _:
            return ""


def event_meta(event: TranscriptEvent) -> EntryMeta | None:
    match event:
        case UserEvent(meta=meta) | AssistantEvent(meta=meta) | SystemEvent(meta=meta):
            return meta
        case _:
            return None


def normalize_bare(text: str, strip_trailing: str = TRAILING_PUNCT) -> str:
    return text.strip().rstrip(strip_trailing).strip().lower()


def predicate_matches(predicate: Predicate, event: TranscriptEvent, kind: EventKind) -> bool:
    match predicate:
        case KindIs(kinds):
            return kind in kinds
        case ModelIs(models):
            return isinstance(event, AssistantEvent) and event.model in models
        case TextEmpty(consider_tool_use=consider_tool_use):
            match event:
                case AssistantEvent() if consider_tool_use:
                    return not event.text.strip() and not any(isinstance(b, ToolUseBlock) for b in event.blocks)
                case UserEvent() | AssistantEvent():
                    return not event.text.strip()
                case _:
                    return False
        case TextMatchesAny(groups=groups, ignore_case=ignore_case):
            return compile_groups(groups, ignore_case).search(event_text(event)) is not None
        case TextInSet(phrases=phrases, strip_trailing=strip_trailing):
            return normalize_bare(event_text(event), strip_trailing) in phrases
        case WordCountAtMost(n):
            return len(event_text(event).split()) <= n
        case MetaFlag(flag):
            return (meta := event_meta(event)) is not None and meta_flag(meta, flag)
        case EntrypointIn(entrypoints):
            return (meta := event_meta(event)) is not None and meta.entrypoint in entrypoints


def meta_flag(meta: EntryMeta, flag: MetaFlagName) -> bool:
    match flag:
        case "is_sidechain":
            return meta.is_sidechain
        case "is_meta":
            return meta.is_meta
        case "is_compact_summary":
            return meta.is_compact_summary
        case "is_visible_in_transcript_only":
            return meta.is_visible_in_transcript_only


def clause_matches(clause: Clause, event: TranscriptEvent, kind: EventKind) -> bool:
    if clause.applies_to and kind not in clause.applies_to:
        return False
    return predicate_matches(clause.predicate, event, kind) is not clause.negate


def keep(event: TranscriptEvent, spec: FilterSpec) -> bool:
    """Returns whether ``event`` survives every ``DROP`` clause of ``spec``."""
    kind = event_kind(event)
    return not any(
        clause.action is Action.DROP and clause_matches(clause, event, kind) for clause in spec.clauses
    )


def labels_for(event: TranscriptEvent, spec: FilterSpec) -> tuple[str, ...]:
    kind = event_kind(event)
    return tuple(
        clause.label
        for clause in spec.clauses
        if clause.action is Action.TAG
        if clause.label is not None
        if clause_matches(clause, event, kind)
    )


def apply_spec(events: Iterable[TranscriptEvent], spec: FilterSpec) -> Iterator[TranscriptEvent]:
    """Yields the events that survive every ``DROP`` clause of ``spec``."""
    return (event for event in events if keep(event, spec))


def annotate_spec(
    events: Iterable[TranscriptEvent], spec: FilterSpec
) -> Iterator[tuple[TranscriptEvent, tuple[str, ...]]]:
    """Yields ``(event, labels)`` for events surviving ``spec``, with TAG labels."""
    return ((event, labels_for(event, spec)) for event in events if keep(event, spec))


def is_portable(spec: FilterSpec) -> bool:
    """Returns whether every clause is executable by the Rust interpreter.

    A spec is portable when each :class:`TextMatchesAny` uses only group names
    proven to match identically under the Rust ``regex`` crate; non-portable
    specs fall back to the Python interpreter.
    """
    return all(clause_portable(clause) for clause in spec.clauses)


def clause_portable(clause: Clause) -> bool:
    match clause.predicate:
        case TextMatchesAny(groups=groups):
            return all(name in PORTABLE_GROUP_NAMES for name, _ in groups)
        case _:
            return True


def spec_to_json(spec: FilterSpec) -> str:
    """Serializes ``spec`` to the JSON contract consumed by the Rust backend."""
    return orjson.dumps({"clauses": [clause_to_dict(clause) for clause in spec.clauses]}).decode()


def clause_to_dict(clause: Clause) -> dict[str, Any]:
    return {
        "predicate": predicate_to_dict(clause.predicate),
        "action": clause.action.value,
        "applies_to": sorted(clause.applies_to),
        "negate": clause.negate,
        "label": clause.label,
    }


def predicate_to_dict(predicate: Predicate) -> dict[str, Any]:
    match predicate:
        case KindIs(kinds):
            return {"kind": "KindIs", "kinds": sorted(kinds)}
        case MetaFlag(flag):
            return {"kind": "MetaFlag", "flag": flag}
        case EntrypointIn(entrypoints):
            return {"kind": "EntrypointIn", "entrypoints": sorted(entrypoints)}
        case ModelIs(models):
            return {"kind": "ModelIs", "models": sorted(models)}
        case TextEmpty(consider_tool_use=consider_tool_use):
            return {"kind": "TextEmpty", "consider_tool_use": consider_tool_use}
        case TextMatchesAny(groups=groups, ignore_case=ignore_case):
            return {"kind": "TextMatchesAny", "groups": [list(group) for group in groups], "ignore_case": ignore_case}
        case TextInSet(phrases=phrases, strip_trailing=strip_trailing):
            return {"kind": "TextInSet", "phrases": sorted(phrases), "strip_trailing": strip_trailing}
        case WordCountAtMost(n):
            return {"kind": "WordCountAtMost", "n": n}


SENTIMENT_SPEC = FilterSpec(
    clauses=(
        Clause(KindIs(CONVERSATIONAL), negate=True),
        Clause(ModelIs(frozenset({"<synthetic>"})), applies_to=ASSISTANTS),
        Clause(TextEmpty(consider_tool_use=True), applies_to=ASSISTANTS),
        Clause(TextEmpty(consider_tool_use=False), applies_to=USERS),
        Clause(TextMatchesAny(SENTIMENT_JUNK_GROUPS), applies_to=USERS),
        # cc-sentiment's parser drops sidechains only for user turns; sidechain
        # assistant turns are kept (they never form buckets without users).
        Clause(MetaFlag("is_sidechain"), applies_to=USERS),
        Clause(MetaFlag("is_compact_summary")),
        Clause(MetaFlag("is_visible_in_transcript_only")),
        Clause(EntrypointIn(frozenset({"sdk-cli"}))),
    )
)

PUSHBACK_SPEC = FilterSpec(
    clauses=(
        Clause(KindIs(USERS), negate=True),
        Clause(MetaFlag("is_sidechain")),
        Clause(MetaFlag("is_meta")),
        Clause(MetaFlag("is_compact_summary")),
        Clause(MetaFlag("is_visible_in_transcript_only")),
        Clause(TextEmpty(consider_tool_use=False), applies_to=USERS),
        Clause(TextMatchesAny(STRUCTURAL_NOISE_GROUPS), applies_to=USERS),
        Clause(TextInSet(TRIVIAL_ACK_SET | RESUME_PHRASE_SET), applies_to=USERS),
        Clause(WordCountAtMost(2), applies_to=USERS),
    )
)


STRUCTURAL_NOISE_RE = compile_groups(STRUCTURAL_NOISE_GROUPS, True)
INTERRUPT_MARKER_RE = compile_groups(INTERRUPT_MARKER_GROUPS, True)
STOP_HOOK_RE = compile_groups(STOP_HOOK_GROUPS, True)
