"""Declarative filtering of a transcript event stream.

A :class:`FilterSpec` is an ordered list of :class:`Clause` rules — *filters as
data*. Parse-time filtering runs in Rust: :func:`spec_to_json` serializes the spec to
the JSON contract the Rust backend executes, dropping events during parsing before
they ever materialize (pass a spec to
:meth:`~cc_transcript.TranscriptParser.stream_transcripts`). Already-materialized
events — a list the caller already holds — are filtered with :func:`apply_spec` or
:func:`keep`.

Consumers compose specs from the builders in :mod:`cc_transcript.builders` over
named building blocks: the junk regex is split into categories
(:data:`JUNK_CATEGORIES`: ``structural`` / ``agent_injection`` / ``interrupt`` /
``stop_hook``) so a consumer can drop structural noise while keeping interrupt and
stop-hook corrections.

Example:
    >>> from cc_transcript import apply_spec, build_spec, keep_only, drop_junk
    >>> spec = build_spec(keep_only("user"), drop_junk("structural"))
    >>> kept = list(apply_spec(events, spec))
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from functools import cache
from typing import TYPE_CHECKING, Literal

import orjson

from cc_transcript.models import (
    AssistantEvent,
    AttachmentEvent,
    ModeEvent,
    OtherEvent,
    SystemEvent,
    ToolUseBlock,
    UserEvent,
)

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator, Sequence
    from typing import Any

    from cc_transcript.models import EntryMeta, SessionId, ToolUseId, TranscriptEvent

EventKind = Literal["user", "assistant", "system", "mode", "other", "attachment"]
MetaFlagName = Literal["is_sidechain", "is_meta", "is_compact_summary", "is_visible_in_transcript_only"]

TRAILING_PUNCT = ".!?…,;:"

STRUCTURAL_TAG_GROUP: tuple[str, str] = (
    "xml_tags",
    r"<(?:system[_-](?:instruction|reminder)"
    r"|local-command-(?:stdout|stderr|caveat)"
    r"|command-(?:name|message|args)"
    r"|task-notification"
    r"|persisted-output"
    r"|output-file)\b",
)

STRUCTURAL_GROUPS: tuple[tuple[str, str], ...] = (
    STRUCTURAL_TAG_GROUP,
    ("local_command_caveat", r"Caveat: The messages below were generated by the user while running local commands\."),
    ("remaining_tasks_ack", r"REMAINING_TASKS_ACKNOWLEDGED"),
    ("angle_token", r"<<[a-z][a-z0-9-]*>>"),
    ("skill_base_dir", r"^Base directory for this skill:"),
    ("hash_banner", r"(?:###\s+[\w][\w \-]{0,30}\s+){3,}###"),
)

# Start-anchored so a mid-text mention is not a banner.
# Dialect-hardened for Rust-regex parity — see cc-notes doc "rust-regex-dialect-parity".
AGENT_INJECTION_GROUPS: tuple[tuple[str, str], ...] = (
    ("xml_tags_extra", r"\A\s*<(?:teammate-message|scheduled-task)(?:[\s/>]|$)"),
    ("augment_agent", r"\A\s*# Augment Agent(?:\s|$)"),
    ("role_reminder", r"\A\s*\[Role Rem(?-i:[Ii])nder(?:[\s:\]]|$)"),
)

# The leading "i" of "interrupted" is ASCII-pinned (?-i:[Ii]) so Python re.IGNORECASE
# doesn't fold the dotted/dotless-I forms (U+0130/U+0131) that Rust regex never matches.
# Dialect-hardened for Rust-regex parity — see cc-notes doc "rust-regex-dialect-parity".
INTERRUPT_MARKER_GROUPS: tuple[tuple[str, str], ...] = (
    ("interrupt", r"^\s*\[Request (?-i:[Ii])nterrupted by user"),
)
STOP_HOOK_GROUPS: tuple[tuple[str, str], ...] = (("stop_hook", r"Stop hook feedback:"),)

# Raw CC-injected protocol strings carried in tool-result content, not user-authored text.
DENIAL_PREFIX = "The user doesn't want to proceed with this tool use. The tool use was rejected"
# Record-level ``toolDenialKind`` values: a human rejection versus a hook/guard block.
DENIAL_KIND_USER_REJECTED = "user-rejected"
DENIAL_KIND_PERMISSION_RULE = "permission-rule"
USER_SAID_MARKER = "To tell you how to proceed, the user said:\n"
USER_SAID_TRAILER = "Note: The user's next message"
ANSWERED_PREFIX = "Your questions have been answered: "
ANSWERED_TRAILER = ". You can now continue with these answers in mind."
# Harness notification-delivery markers: the task-notification wrapper and the tool-use-id tag it carries.
TASK_NOTIFICATION_MARKER = "<task-notification>"
TOOL_USE_ID_PREFIX = "<tool-use-id>"
TOOL_USE_ID_SUFFIX = "</tool-use-id>"

# Approve-and-advance directives advance the prior assistant turn rather than correct it — the opposite of
# pushback — so pushback consumers drop them; start-anchoring keeps a mid-correction "commit"/"push" from matching.
CONTINUATION_GROUPS: tuple[tuple[str, str], ...] = (
    (
        "continuation",
        r"^\s*(?:(?:yea+h?|yep|yup|sure|ok(?:ay)?|sounds good|looks good|lgtm|perfect)[\s,.!]+){0,2}"
        r"(?:go ahead\b|(?:go ahead and\s+)?(?:commit|push|rebase|merge|deploy)\b"
        r"|ship it\b|cut (?:a |the )?(?:new )?release\b|proceed\b)"
        r"|\byou must resume\b"
        r"|\b(?:resume|restart) (?:them|it|the (?:sub-?agents?|workflows?|agents?|tasks?))\b",
    ),
)

# Bash-mode (`!`) command echoes recorded as user turns — the command line and its
# captured stdout/stderr, not authored feedback. Start-anchored (\A\s*) so a mid-text
# mention of a bash tag is authored prose, not an echo — a real echo begins with the tag.
# Dialect-hardened for Rust-regex parity — see cc-notes doc "rust-regex-dialect-parity".
COMMAND_ECHO_GROUPS: tuple[tuple[str, str], ...] = (("command_echo", r"\A\s*<bash-(?:input|stdout|stderr)\b"),)

# Interrupt and stop-hook stay separate categories: they carry pushback and must never fold into structural noise.
JUNK_CATEGORIES: dict[str, tuple[tuple[str, str], ...]] = {
    "structural": STRUCTURAL_GROUPS,
    "agent_injection": AGENT_INJECTION_GROUPS,
    "interrupt": INTERRUPT_MARKER_GROUPS,
    "stop_hook": STOP_HOOK_GROUPS,
    "continuation": CONTINUATION_GROUPS,
    "command_echo": COMMAND_ECHO_GROUPS,
}

# Structural ∪ agent-injection, WITHOUT interrupt/stop-hook — those carry pushback and must never live here.
STRUCTURAL_NOISE_GROUPS: tuple[tuple[str, str], ...] = STRUCTURAL_GROUPS + AGENT_INJECTION_GROUPS

# The historical monolithic JUNK_USER_MESSAGE_RE plus bash-mode command echoes.
SENTIMENT_JUNK_GROUPS: tuple[tuple[str, str], ...] = (
    STRUCTURAL_GROUPS + INTERRUPT_MARKER_GROUPS + STOP_HOOK_GROUPS + COMMAND_ECHO_GROUPS
)

FRUSTRATION_GROUPS: tuple[tuple[str, str], ...] = (
    (
        "frustration",
        r"\b("
        r"wtf|wth|ffs|omfg|"
        r"fuck(?:ing)?\s*(?:broken|useless|stupid|terrible|awful|horrible|piece\s*of\s*shit)|"
        r"fuck\s*(?:you|this|it|off)|"
        r"screw\s*(?:you|this)|"
        r"piece\s*of\s*(?:shit|crap|junk)|"
        r"dumbass|"
        r"you'?re\s*(?:fucking\s*)?(?:useless|stupid|broken|terrible|awful)|"
        r"this\s*(?:is\s*)?(?:fucking\s*)?(?:terrible|awful|horrible|useless|garbage)|"
        r"stop\s+(?:guessing|making\s+(?:things|stuff|shit)\s*up|hallucinating|inventing|assuming"
        r"|pretending|being\s+lazy|making\s+excuses|lying)|"
        r"just\s+stop\s+(?:it|already)|"
        r"completely\s*useless|"
        r"i\s*give\s*up|giving\s*up"
        r")\b",
    ),
)

MILD_IMPATIENCE_GROUPS: tuple[tuple[str, str], ...] = (
    (
        "mild_impatience",
        r"\b("
        r"and\s+again|"
        r"yet\s+again|"
        r"once\s+again|"
        r"for\s+the\s+(?:second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth|umpteenth|hundredth|nth)\s+time"
        r")\b",
    ),
)

# Hedging cues that soften a correction; a mining demote stage drops confidence on a hit.
HEDGE_GROUPS: tuple[tuple[str, str], ...] = (
    ("hedged", r"\b(?:maybe|perhaps|possibly|might|not sure|i think|i guess|if you (?:want|prefer)|up to you)\b"),
)

RESUME_PHRASE_SET: frozenset[str] = frozenset(
    {
        "continue",
        "continues",
        "continue please",
        "please continue",
        "resume",
        "resume please",
        "please resume",
        "go ahead",
        "keep going",
        "carry on",
        "proceed",
        "go on",
        "keep at it",
        "ok continue",
        "ok resume",
        "ok go ahead",
        "okay continue",
        "okay resume",
        "okay go ahead",
        "continue from where you left off",
        "continue where you left off",
        "continue your previous task",
        "[context restored] resume",
        "[context restored] continue",
        "[context restored] pick up the conversation",
    }
)

TRIVIAL_ACK_SET: frozenset[str] = frozenset(
    {
        "ok",
        "okay",
        "k",
        "kk",
        "yes",
        "yep",
        "yeah",
        "yup",
        "sure",
        "thanks",
        "thank you",
        "thx",
        "ty",
        "great",
        "perfect",
        "nice",
        "cool",
        "awesome",
        "done",
        "good",
        "lgtm",
        "got it",
        "sounds good",
        "looks good",
        "makes sense",
        "approved",
    }
)

SHORT_MESSAGE_MAX_WORDS = 3

CONVERSATIONAL: frozenset[EventKind] = frozenset({"user", "assistant"})
USERS: frozenset[EventKind] = frozenset({"user"})
ASSISTANTS: frozenset[EventKind] = frozenset({"assistant"})


class Action(Enum):
    """What a matching :class:`Clause` does to an event."""

    DROP = "drop"
    TAG = "tag"


@dataclass(frozen=True, slots=True)
class KindIs:
    """Matches events whose kind is in ``kinds``."""

    kinds: frozenset[EventKind]


@dataclass(frozen=True, slots=True)
class MetaFlag:
    """Matches when an :class:`~cc_transcript.models.EntryMeta` boolean is set."""

    flag: MetaFlagName


@dataclass(frozen=True, slots=True)
class EntrypointIn:
    """Matches when ``meta.entrypoint`` is in ``entrypoints``."""

    entrypoints: frozenset[str]


@dataclass(frozen=True, slots=True)
class ModelIs:
    """Matches assistant events whose ``model`` is in ``models``."""

    models: frozenset[str]


@dataclass(frozen=True, slots=True)
class TextEmpty:
    """Matches events with blank text.

    Attributes:
        consider_tool_use: When true, an assistant event with a tool-use block
            is not considered empty even with blank text.
    """

    consider_tool_use: bool = True


@dataclass(frozen=True, slots=True)
class TextMatchesAny:
    """Matches when the event text matches any of the named regex ``groups``.

    Attributes:
        groups: Ordered ``(name, pattern)`` pairs; names label composable,
            individually includable building blocks.
        ignore_case: Whether to compile case-insensitively.
    """

    groups: tuple[tuple[str, str], ...]
    ignore_case: bool = True


@dataclass(frozen=True, slots=True)
class TextInSet:
    """Matches when the normalized event text is in ``phrases``.

    Normalization mirrors a bare-message check: strip, drop trailing
    punctuation, strip again, lowercase.
    """

    phrases: frozenset[str]
    strip_trailing: str = TRAILING_PUNCT


@dataclass(frozen=True, slots=True)
class WordCountAtMost:
    """Matches when the event text has at most ``n`` whitespace-split words."""

    n: int


Predicate = KindIs | MetaFlag | EntrypointIn | ModelIs | TextEmpty | TextMatchesAny | TextInSet | WordCountAtMost


@dataclass(frozen=True, slots=True)
class Clause:
    """One filter rule: when ``predicate`` holds, apply ``action``.

    Attributes:
        predicate: The condition tested against an event.
        action: ``DROP`` removes the event (first drop wins, stops evaluation);
            ``TAG`` records ``label`` on a surviving event and continues.
        applies_to: When non-empty, the clause is only evaluated for these kinds.
        negate: Invert the predicate match.
        label: The label recorded by a ``TAG`` clause.
    """

    predicate: Predicate
    action: Action = Action.DROP
    applies_to: frozenset[EventKind] = frozenset()
    negate: bool = False
    label: str | None = None


@dataclass(frozen=True, slots=True)
class FilterSpec:
    """An ordered list of :class:`Clause` rules applied to an event stream."""

    clauses: tuple[Clause, ...]


def group_pattern(groups: tuple[tuple[str, str], ...]) -> str:
    """Composes named regex groups into one non-capturing alternation."""
    return "|".join(f"(?:{pattern})" for _, pattern in groups)


@cache
def compile_groups(groups: tuple[tuple[str, str], ...], ignore_case: bool, *, multiline: bool = False) -> re.Pattern[str]:
    return re.compile(group_pattern(groups), (re.IGNORECASE if ignore_case else 0) | (re.MULTILINE if multiline else 0))


def event_kind(event: TranscriptEvent) -> EventKind:
    match event:
        case UserEvent():
            return "user"
        case AssistantEvent():
            return "assistant"
        case SystemEvent():
            return "system"
        case ModeEvent():
            return "mode"
        case OtherEvent():
            return "other"
        case AttachmentEvent():
            return "attachment"


def event_text(event: TranscriptEvent) -> str:
    match event:
        case UserEvent(text=text) | AssistantEvent(text=text):
            return text
        case _:
            return ""


def event_meta(event: TranscriptEvent) -> EntryMeta | None:
    match event:
        case UserEvent(meta=meta) | AssistantEvent(meta=meta) | SystemEvent(meta=meta) | AttachmentEvent(meta=meta):
            return meta
        case _:
            return None


def session_id_of(events: Sequence[TranscriptEvent]) -> SessionId | None:
    return next((meta.session_id for event in events if (meta := event_meta(event)) is not None), None)


def tool_uses(events: Sequence[TranscriptEvent]) -> dict[ToolUseId, ToolUseBlock]:
    return {
        block.id: block
        for event in events
        if isinstance(event, AssistantEvent)
        for block in event.blocks
        if isinstance(block, ToolUseBlock)
    }


def tool_names(events: Sequence[TranscriptEvent]) -> dict[ToolUseId, str]:
    return {tid: block.name for tid, block in tool_uses(events).items()}


def embedded_user_text(content: str) -> str | None:
    if (start := content.find(USER_SAID_MARKER)) == -1:
        return None
    return content[start + len(USER_SAID_MARKER) :].split(USER_SAID_TRAILER, 1)[0].strip()


def interrupt_marker(content: str) -> str | None:
    stripped = content.lstrip()
    if (match := INTERRUPT_MARKER_RE.match(stripped)) is None:
        return None
    end = stripped.find("]")
    return stripped[: end + 1] if end != -1 else match.group(0)


def is_bare_interrupt_marker(text: str) -> bool:
    return (marker := interrupt_marker(text)) is not None and not text.strip()[len(marker.strip()) :].strip()


def is_agent_injection(text: str) -> bool:
    return AGENT_INJECTION_RE.search(text) is not None


def normalize_bare(text: str, strip_trailing: str = TRAILING_PUNCT) -> str:
    return text.strip().rstrip(strip_trailing).strip().lower()


def predicate_matches(predicate: Predicate, event: TranscriptEvent, kind: EventKind) -> bool:
    match predicate:
        case KindIs(kinds):
            return kind in kinds
        case ModelIs(models):
            return isinstance(event, AssistantEvent) and event.model in models
        case TextEmpty(consider_tool_use=consider_tool_use):
            match event:
                case AssistantEvent() if consider_tool_use:
                    return not event.text.strip() and not any(isinstance(b, ToolUseBlock) for b in event.blocks)
                case UserEvent() | AssistantEvent():
                    return not event.text.strip()
                case _:
                    return False
        case TextMatchesAny(groups=groups, ignore_case=ignore_case):
            return compile_groups(groups, ignore_case).search(event_text(event)) is not None
        case TextInSet(phrases=phrases, strip_trailing=strip_trailing):
            return normalize_bare(event_text(event), strip_trailing) in phrases
        case WordCountAtMost(n):
            return len(event_text(event).split()) <= n
        case MetaFlag(flag):
            return (meta := event_meta(event)) is not None and meta_flag(meta, flag)
        case EntrypointIn(entrypoints):
            return (meta := event_meta(event)) is not None and meta.entrypoint in entrypoints


def meta_flag(meta: EntryMeta, flag: MetaFlagName) -> bool:
    match flag:
        case "is_sidechain":
            return meta.is_sidechain
        case "is_meta":
            return meta.is_meta
        case "is_compact_summary":
            return meta.is_compact_summary
        case "is_visible_in_transcript_only":
            return meta.is_visible_in_transcript_only


def clause_matches(clause: Clause, event: TranscriptEvent, kind: EventKind) -> bool:
    if clause.applies_to and kind not in clause.applies_to:
        return False
    return predicate_matches(clause.predicate, event, kind) is not clause.negate


def keep(event: TranscriptEvent, spec: FilterSpec) -> bool:
    """Returns whether ``event`` survives every ``DROP`` clause of ``spec``.

    Filters an already-materialized :class:`~cc_transcript.models.TranscriptEvent`;
    parse-time filtering runs in Rust before materialization via :func:`spec_to_json`.
    """
    kind = event_kind(event)
    return not any(clause.action is Action.DROP and clause_matches(clause, event, kind) for clause in spec.clauses)


def labels_for(event: TranscriptEvent, spec: FilterSpec) -> tuple[str, ...]:
    """Returns the TAG labels ``spec`` records for ``event``, in clause order."""
    kind = event_kind(event)
    return tuple(
        clause.label
        for clause in spec.clauses
        if clause.action is Action.TAG
        if clause.label is not None
        if clause_matches(clause, event, kind)
    )


def apply_spec(events: Iterable[TranscriptEvent], spec: FilterSpec) -> Iterator[TranscriptEvent]:
    """Yields the already-materialized events that survive every ``DROP`` clause of ``spec``."""
    return (event for event in events if keep(event, spec))


def annotate_spec(
    events: Iterable[TranscriptEvent], spec: FilterSpec
) -> Iterator[tuple[TranscriptEvent, tuple[str, ...]]]:
    """Yields ``(event, labels)`` for events surviving ``spec``, with TAG labels."""
    return ((event, labels_for(event, spec)) for event in events if keep(event, spec))


def spec_to_json(spec: FilterSpec) -> str:
    """Serializes ``spec`` to the JSON contract consumed by the Rust backend."""
    return orjson.dumps({"clauses": [clause_to_dict(clause) for clause in spec.clauses]}).decode()


def clause_to_dict(clause: Clause) -> dict[str, Any]:
    return {
        "predicate": predicate_to_dict(clause.predicate),
        "action": clause.action.value,
        "applies_to": sorted(clause.applies_to),
        "negate": clause.negate,
        "label": clause.label,
    }


def predicate_to_dict(predicate: Predicate) -> dict[str, Any]:
    match predicate:
        case KindIs(kinds):
            return {"kind": "KindIs", "kinds": sorted(kinds)}
        case MetaFlag(flag):
            return {"kind": "MetaFlag", "flag": flag}
        case EntrypointIn(entrypoints):
            return {"kind": "EntrypointIn", "entrypoints": sorted(entrypoints)}
        case ModelIs(models):
            return {"kind": "ModelIs", "models": sorted(models)}
        case TextEmpty(consider_tool_use=consider_tool_use):
            return {"kind": "TextEmpty", "consider_tool_use": consider_tool_use}
        case TextMatchesAny(groups=groups, ignore_case=ignore_case):
            return {"kind": "TextMatchesAny", "groups": [list(group) for group in groups], "ignore_case": ignore_case}
        case TextInSet(phrases=phrases, strip_trailing=strip_trailing):
            return {"kind": "TextInSet", "phrases": sorted(phrases), "strip_trailing": strip_trailing}
        case WordCountAtMost(n):
            return {"kind": "WordCountAtMost", "n": n}


STRUCTURAL_NOISE_RE = compile_groups(STRUCTURAL_NOISE_GROUPS, True)
AGENT_INJECTION_RE = compile_groups(AGENT_INJECTION_GROUPS, True)
INTERRUPT_MARKER_RE = compile_groups(INTERRUPT_MARKER_GROUPS, True)
JUNK_USER_MESSAGE_RE = compile_groups(SENTIMENT_JUNK_GROUPS, True)
