"""Golden parity: the native events-in replay reproduces Python ``Notifications``.

The golden (``testdata/notifications_golden.json``, regenerated by
``scripts/gen_notifications_golden.py``) freezes the ``queued``/``delivered``/
``enqueued`` replay for a curated battery of synthetic transcripts. This asserts the
native ``_native.notifications_from_events`` binding reproduces each replay exactly
and that the Python ``Notifications.from_events`` reference still does.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _native
from cc_transcript.notifications import Notifications
from scripts.gen_notifications_golden import to_bytes
from tests import testkit
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "notifications_golden.json").read_text(encoding="utf-8")
)
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_notifications_from_events_matches_golden(entry: dict) -> None:
    assert _native.notifications_from_events(testkit.parse_events(*entry["records"])) == entry["expected"]


@pytest.mark.parametrize("entry", CASES)
def test_python_notifications_match_golden(entry: dict) -> None:
    n = Notifications.from_events(testkit.parse_events(*entry["records"]))
    assert {"queued": list(n.queued), "delivered": list(n.delivered), "enqueued": list(n.enqueued)} == entry["expected"]


# Duplicate object keys can't be built from a Python dict; the parser keeps the last one.
DUP_KEY_RAW = [
    pytest.param(
        '{"type":"queue-operation","operation":"dequeue","operation":"enqueue","content":"a","content":"b"}',
        id="operation-and-content-last-wins",
    ),
]


@requires_rust
@pytest.mark.parametrize("raw", DUP_KEY_RAW)
def test_dup_keys_replay_last_wins(raw: str) -> None:
    events = testkit.parse_bytes(raw.encode())
    assert _native.notifications_from_events(events) == {"queued": ["b"], "delivered": [], "enqueued": ["b"]}
