"""Golden parity: the Rust facts port reproduces the Python facts.py analytics.

The golden (``testdata/facts_golden.json``, regenerated by ``scripts/gen_facts_golden.py``)
freezes, per file, the flattened ``ToolFact`` list plus the ordered ``command_prefix_counts`` and
``mcp_summary`` aggregates — over every corpus file plus hand-built synthetic transcripts. Events
are sourced through the Rust parser on both sides, so these assertions isolate the *facts*
projection: ``_parser_rs.tool_facts`` reproduces each file's projection, and the Python reference
still projects to the frozen golden. The aggregate lists are ordered, so tie-ordering is tested.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _parser_rs
from scripts.gen_facts_golden import CORPUS, MAX_EVENTS, SYNTHETIC_CASES, project_file
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "facts_golden.json").read_text(encoding="utf-8")
)
FILE_CASES = [pytest.param(rel, id=rel) for rel in GOLDEN["files"]]
SYNTHETIC = [pytest.param(name, id=name) for name in GOLDEN["synthetic"]]


@requires_rust
@pytest.mark.parametrize("rel", FILE_CASES)
def test_rust_facts_matches_golden(rel: str) -> None:
    assert _parser_rs.tool_facts([str(CORPUS / rel)], MAX_EVENTS)[0] == GOLDEN["files"][rel]


@requires_rust
@pytest.mark.parametrize("rel", FILE_CASES)
def test_python_facts_matches_golden(rel: str) -> None:
    assert project_file(CORPUS / rel) == GOLDEN["files"][rel]


@requires_rust
@pytest.mark.parametrize("name", SYNTHETIC)
def test_rust_synthetic_facts_matches_golden(name: str, tmp_path: Path) -> None:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(SYNTHETIC_CASES[name], encoding="utf-8")
    assert _parser_rs.tool_facts([str(path)], MAX_EVENTS)[0] == GOLDEN["synthetic"][name]


@requires_rust
@pytest.mark.parametrize("name", SYNTHETIC)
def test_python_synthetic_facts_matches_golden(name: str, tmp_path: Path) -> None:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(SYNTHETIC_CASES[name], encoding="utf-8")
    assert project_file(path) == GOLDEN["synthetic"][name]
