"""Golden parity: the flipped ``cc_transcript.command`` surface reproduces the v13.2 splice layer.

The golden (``testdata/splice_golden.json``, regenerated by ``scripts/gen_splice_golden.py``)
freezes the Python ``CommandLine`` splice surface — per-part ``Command.span``, ``Occurrence``
``prev_op``/``next_op``/``piped``, ``CommandLine.splice`` results, the parse-derived span-less
``ValueError`` message, and ``rewrite_occurrences``. This asserts the live surface (Python
today, the native views once P6 flips them) serializes to the frozen structure, over the
command-prefix pins, edge cases, and splice-specific shapes.

The out-of-order and overlap ``ValueError`` legs need hand-built spans and live as construction
tests in ``tests/test_command.py`` (``TestSplice``).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript.command import parse_command_line
from scripts.gen_splice_golden import line_to_dict

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "splice_golden.json").read_text(encoding="utf-8")
)
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@pytest.mark.parametrize("entry", CASES)
def test_splice_surface_matches_golden(entry: dict) -> None:
    assert line_to_dict(parse_command_line(entry["command"])) == entry["splice_layer"]
