"""Golden parity: the Rust ``WatchTailer`` reproduces the frozen tailer cursor.

The golden (``testdata/watch_golden.json``, regenerated by ``scripts/gen_watch_golden.py``)
freezes, per scenario step, the yields and cursor state a tailer produces over a scripted
sequence of filesystem states. ``test_rust_watch_matches_golden`` replays the same steps in
a fresh tmp tree against the Rust ``WatchTailer``, asserting the frozen golden — so the
assertions isolate the port from reference drift.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

from scripts.gen_watch_golden import SCENARIOS, run_scenario
from tests.support import requires_rust

if TYPE_CHECKING:
    pass

GOLDEN = json.loads((Path(__file__).resolve().parent / "testdata" / "watch_golden.json").read_text(encoding="utf-8"))
SCENARIO_NAMES = [pytest.param(name, id=name) for name in SCENARIOS]


@requires_rust
@pytest.mark.parametrize("name", SCENARIO_NAMES)
def test_rust_watch_matches_golden(name: str, tmp_path: Path) -> None:
    assert run_scenario(tmp_path, SCENARIOS[name]) == GOLDEN[name]
