"""Golden parity: the Rust ``WatchTailer`` reproduces the Python ``watch.tick`` cursor.

The golden (``testdata/watch_golden.json``, regenerated by ``scripts/gen_watch_golden.py``)
freezes, per scenario step, the yields and cursor state the Python tailer produces over a
scripted sequence of filesystem states. Each test replays the same steps in a fresh tmp
tree: ``test_rust_*`` drives the Rust ``WatchTailer`` and ``test_python_*`` re-drives the
Python reference, both asserting the frozen golden — so the Rust assertions isolate the
port and the Python assertions guard against reference drift.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

import anyio
import pytest

from cc_transcript import _parser_rs
from scripts.gen_watch_golden import (
    SCENARIOS,
    apply_ops,
    project_events,
    relativize_state,
    run_python_scenario,
)
from tests.support import requires_rust

if TYPE_CHECKING:
    from collections.abc import Sequence

GOLDEN = json.loads((Path(__file__).resolve().parent / "testdata" / "watch_golden.json").read_text(encoding="utf-8"))
SCENARIO_NAMES = [pytest.param(name, id=name) for name in SCENARIOS]


def run_rust_scenario(root: Path, scenario: dict[str, object]) -> list[dict[str, object]]:
    tailer = _parser_rs.WatchTailer()
    from_start = bool(scenario["from_start"])
    steps = scenario["steps"]
    assert isinstance(steps, list)
    results: list[dict[str, object]] = []
    for step in steps:
        apply_ops(root, step["ops"])
        events: Sequence[tuple] = [tuple(row) for row in tailer.tick([str(root)], from_start)]
        results.append(
            {
                "name": step["name"],
                "yields": project_events(root, events),
                "state": relativize_state(root, tailer.snapshot()),
            }
        )
    return results


@requires_rust
@pytest.mark.parametrize("name", SCENARIO_NAMES)
def test_rust_watch_matches_golden(name: str, tmp_path: Path) -> None:
    assert run_rust_scenario(tmp_path, SCENARIOS[name]) == GOLDEN[name]


@requires_rust
@pytest.mark.parametrize("name", SCENARIO_NAMES)
def test_python_watch_matches_golden(name: str, tmp_path: Path) -> None:
    assert anyio.run(run_python_scenario, tmp_path, SCENARIOS[name]) == GOLDEN[name]
