"""Golden pin: both native ``bucket_events`` entry points reproduce the frozen bucketing.

The golden (``testdata/buckets_golden.json``, regenerated by
``scripts/gen_buckets_golden.py``) freezes each scorable bucket's ``session_id``,
``bucket_index``, ``bucket_start_ms``, and member ``uuids`` for a curated battery of
synthetic transcripts. This asserts the raw-bytes ``_native.bucket_events`` reproduces
each bucketing exactly, that the events-in ``_native.bucket_events_from_events`` behind
``ConversationBucketer.bucket_events`` does too, and that ``extract_bucket_keys`` stays
consistent with it.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _native
from cc_transcript.parser import parse_events_from_bytes
from cc_transcript.sentiment.buckets import ConversationBucketer, extract_bucket_keys
from scripts.gen_buckets_golden import project, to_bytes
from tests import testkit
from tests.support import requires_rust

GOLDEN = json.loads((Path(__file__).resolve().parent / "testdata" / "buckets_golden.json").read_text(encoding="utf-8"))
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_bucket_events_matches_golden(entry: dict) -> None:
    assert _native.bucket_events(to_bytes(tuple(entry["records"]))) == entry["buckets"]


@pytest.mark.parametrize("entry", CASES)
def test_facade_bucket_events_matches_golden(entry: dict) -> None:
    # project() routes ConversationBucketer.bucket_events through the events-in native
    # binding + uuid rehydration, so this pins that path (not a Python reimpl) to golden.
    assert project(tuple(entry["records"])) == entry["buckets"]


def test_facade_rehydrates_shared_uuids_by_index_not_last_wins() -> None:
    # Finder F4: two parses share session "s" + uuids u1/a1/u2 with distinct content; a
    # last-wins (session_id, uuid) map dropped the A events and duplicated the B events.
    def side(tag: str, offset: int) -> list:
        lines = (
            testkit.user_line("u1", f"substantive prompt {tag} one", session_id="s", timestamp=testkit.BASE, secs=offset),
            testkit.assistant_line("a1", "working", session_id="s", timestamp=testkit.BASE, secs=offset + 1),
            testkit.user_line("u2", f"substantive prompt {tag} two", session_id="s", timestamp=testkit.BASE, secs=offset + 2),
        )
        return list(parse_events_from_bytes(to_bytes(lines)))

    a_events = side("A", 0)
    b_events = side("B", 10)
    all_events = a_events + b_events

    (bucket,) = ConversationBucketer.bucket_events(all_events)
    assert bucket.session_id == "s"
    returned = list(bucket.events)
    assert len(returned) == 6
    assert len({id(e) for e in returned}) == 6  # every object distinct: none dropped, none duplicated
    assert all(got is want for got, want in zip(returned, all_events, strict=True))  # timestamp order == input order


def test_facade_rehydrates_two_sessions_sharing_uuids_by_index() -> None:
    # Finder F7: two distinct sessions share uuids u1/a1/u2; a uuid-ONLY lookup would give s2's
    # bucket s1's events. Each session's bucket must rehydrate exactly its own three objects.
    def session(sid: str, tag: str) -> list:
        lines = (
            testkit.user_line("u1", f"substantive prompt {tag} one", session_id=sid, timestamp=testkit.BASE, secs=0),
            testkit.assistant_line("a1", "working", session_id=sid, timestamp=testkit.BASE, secs=1),
            testkit.user_line("u2", f"substantive prompt {tag} two", session_id=sid, timestamp=testkit.BASE, secs=2),
        )
        return list(parse_events_from_bytes(to_bytes(lines)))

    s1 = session("s1", "A")
    s2 = session("s2", "B")
    by_session = {b.session_id: b for b in ConversationBucketer.bucket_events(s1 + s2)}
    assert set(by_session) == {"s1", "s2"}
    assert all(got is want for got, want in zip(by_session["s1"].events, s1, strict=True))
    assert all(got is want for got, want in zip(by_session["s2"].events, s2, strict=True))


def test_bucketer_drops_combining_mark_hash_banner_via_rust_word_class() -> None:
    # Finder F6: Rust \w matches the combining mark U+0301 (Python re's \w did not), so the junk
    # filter reads this as a hash banner, drops the first user, and drops the sub-floor session.
    def with_first(first: str) -> list:
        lines = (
            testkit.user_line("u1", first, session_id="s", timestamp=testkit.BASE, secs=0),
            testkit.user_line("u2", "hello", session_id="s", timestamp=testkit.BASE, secs=1),
            testkit.assistant_line("a1", "ok", session_id="s", timestamp=testkit.BASE, secs=2),
        )
        return list(parse_events_from_bytes(to_bytes(lines)))

    banner = "### e\u0301 ### e\u0301 ### e\u0301 ###"  # decomposed e + combining acute
    assert ConversationBucketer.bucket_events(with_first(banner)) == []
    (bucket,) = ConversationBucketer.bucket_events(with_first("a normal substantive first prompt"))
    assert len(bucket.events) == 3  # non-banner first user: both turns count, one bucket


@pytest.mark.parametrize("entry", CASES)
def test_extract_bucket_keys_matches_buckets(entry: dict) -> None:
    keys = extract_bucket_keys(parse_events_from_bytes(to_bytes(tuple(entry["records"]))))
    assert [(k.session_id, k.bucket_index) for k in keys] == [(b["session_id"], b["bucket_index"]) for b in entry["buckets"]]
