"""Golden parity: the Rust query port reproduces the Python query.py ``Session`` battery.

The golden (``testdata/query_golden.json``, regenerated by ``scripts/gen_query_golden.py``)
freezes a deterministic battery — tool-call counts, touched/edited files, failures, commands,
prompts, ``has_*`` predicates, window event-lengths, and per-``FileRef`` ``is_test``/``suffix`` —
over every corpus file plus hand-built synthetic transcripts. Events are sourced through the Rust
parser on both sides, so these assertions isolate the *query*: ``_parser_rs.query_session``
reproduces each projection, and the Python reference still projects to the frozen golden.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _parser_rs
from scripts.gen_query_golden import CORPUS, MAX_EVENTS, SYNTHETIC_CASES, project_file
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "query_golden.json").read_text(encoding="utf-8")
)
QUERY_CASES = [pytest.param(rel, id=rel) for rel in GOLDEN["queries"]]
SYNTHETIC = [pytest.param(name, id=name) for name in GOLDEN["synthetic"]]


@requires_rust
@pytest.mark.parametrize("rel", QUERY_CASES)
def test_rust_query_matches_golden(rel: str) -> None:
    assert _parser_rs.query_session(str(CORPUS / rel), MAX_EVENTS) == GOLDEN["queries"][rel]


@requires_rust
@pytest.mark.parametrize("rel", QUERY_CASES)
def test_python_query_matches_golden(rel: str) -> None:
    assert project_file(CORPUS / rel) == GOLDEN["queries"][rel]


@requires_rust
@pytest.mark.parametrize("name", SYNTHETIC)
def test_rust_synthetic_matches_golden(name: str, tmp_path: Path) -> None:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(SYNTHETIC_CASES[name], encoding="utf-8")
    assert _parser_rs.query_session(str(path), MAX_EVENTS) == GOLDEN["synthetic"][name]


@requires_rust
@pytest.mark.parametrize("name", SYNTHETIC)
def test_python_synthetic_matches_golden(name: str, tmp_path: Path) -> None:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(SYNTHETIC_CASES[name], encoding="utf-8")
    assert project_file(path) == GOLDEN["synthetic"][name]
