from __future__ import annotations

import re
from datetime import UTC, datetime
from pathlib import Path

import pytest

from cc_transcript.filters import JUNK_USER_MESSAGE_RE, FilterConfig, apply_filters
from cc_transcript.models import (
    AssistantEvent,
    EntryMeta,
    EventUuid,
    ModeEvent,
    OtherEvent,
    SessionId,
    SystemEvent,
    ToolUseBlock,
    TranscriptEvent,
    UserEvent,
)
from cc_transcript.parser import parse_events_from_bytes
from tests.test_backend_parity import real_corpus

# The historical monolithic regex + predicate, vendored verbatim, so the
# group-composed JUNK_USER_MESSAGE_RE and the declarative FilterConfig lowering
# stay byte-for-byte identical to the old behavior on real data.
LEGACY_JUNK_RE = re.compile(
    r"<(?:system[_-](?:instruction|reminder)"
    r"|local-command-(?:stdout|caveat)"
    r"|command-(?:name|message|args)"
    r"|task-notification"
    r"|persisted-output"
    r"|output-file)\b"
    r"|Caveat: The messages below were generated by the user while running local commands\."
    r"|\[Request interrupted by user"
    r"|Stop hook feedback:"
    r"|REMAINING_TASKS_ACKNOWLEDGED"
    r"|<<[a-z][a-z0-9-]*>>"
    r"|^Base directory for this skill:"
    r"|(?:###\s+[\w][\w \-]{0,30}\s+){3,}###",
    re.IGNORECASE,
)

LEGACY_SENTIMENT = FilterConfig(
    keep_types=(UserEvent, AssistantEvent),
    drop_sidechain=True,
    drop_synthetic=True,
    drop_compacted=True,
    drop_empty=True,
    drop_ephemeral_entrypoints=frozenset({"sdk-cli"}),
    junk_pattern=LEGACY_JUNK_RE,
)

# The same config built from the group-composed regex cc-transcript ships.
SENTIMENT_CONFIG = FilterConfig(
    keep_types=(UserEvent, AssistantEvent),
    drop_sidechain=True,
    drop_synthetic=True,
    drop_compacted=True,
    drop_empty=True,
    drop_ephemeral_entrypoints=frozenset({"sdk-cli"}),
    junk_pattern=JUNK_USER_MESSAGE_RE,
)


def legacy_keep(event: TranscriptEvent, config: FilterConfig) -> bool:
    if config.keep_types is not None and not isinstance(event, config.keep_types):
        return False
    match event:
        case OtherEvent() | ModeEvent():
            return True
        case AssistantEvent() if config.drop_synthetic and event.model == "<synthetic>":
            return False
        case AssistantEvent() if (
            config.drop_empty
            and not event.text.strip()
            and not any(isinstance(block, ToolUseBlock) for block in event.blocks)
        ):
            return False
        case UserEvent() if config.drop_empty and not event.text.strip():
            return False
        case UserEvent() if config.junk_pattern is not None and config.junk_pattern.search(event.text):
            return False
        case UserEvent(meta=meta) | AssistantEvent(meta=meta) | SystemEvent(meta=meta):
            if config.drop_sidechain and meta.is_sidechain:
                return False
            if config.drop_compacted and (meta.is_compact_summary or meta.is_visible_in_transcript_only):
                return False
            return meta.entrypoint not in config.drop_ephemeral_entrypoints


def meta(
    *,
    is_sidechain: bool = False,
    is_meta: bool = False,
    is_compact_summary: bool = False,
    entrypoint: str | None = "cli",
) -> EntryMeta:
    return EntryMeta(
        uuid=EventUuid("u"),
        parent_uuid=None,
        session_id=SessionId("s"),
        timestamp=datetime(2026, 1, 1, tzinfo=UTC),
        cwd="/repo",
        git_branch="main",
        cc_version=None,
        is_sidechain=is_sidechain,
        is_meta=is_meta,
        entrypoint=entrypoint,
        is_compact_summary=is_compact_summary,
        is_visible_in_transcript_only=False,
    )


def user(text: str, **kw: bool | str | None) -> UserEvent:
    return UserEvent(meta=meta(**kw), text=text, blocks=(), interrupted=False)  # type: ignore[arg-type]


def assistant(model: str) -> AssistantEvent:
    return AssistantEvent(meta=meta(), model=model, text="hi", blocks=(), stop_reason=None)


@pytest.mark.parametrize(
    "event",
    [
        pytest.param(user("real prompt", is_sidechain=True), id="sidechain"),
        pytest.param(assistant("<synthetic>"), id="synthetic"),
        pytest.param(user("from sdk", entrypoint="sdk-cli"), id="sdk-cli"),
        pytest.param(user("<system-reminder>do this</system-reminder>"), id="system-reminder-junk"),
        pytest.param(
            user("Caveat: The messages below were generated by the user while running local commands."),
            id="local-command-caveat-junk",
        ),
        pytest.param(user("real but compacted", is_compact_summary=True), id="compact-summary"),
        pytest.param(user("   "), id="empty-user"),
        pytest.param(
            AssistantEvent(meta=meta(), model="claude-opus-4-7", text="", blocks=(), stop_reason=None),
            id="empty-assistant",
        ),
        pytest.param(OtherEvent(type="summary", raw={"type": "summary"}), id="summary-other"),
        pytest.param(OtherEvent(type="queue-operation", raw={"type": "queue-operation"}), id="queue-operation-other"),
        pytest.param(ModeEvent(session_id=SessionId("s"), channel="mode", value="normal"), id="mode"),
    ],
)
def test_sentiment_config_drops(event: TranscriptEvent) -> None:
    keeper = user("please refactor the parser")
    assert list(apply_filters([event, keeper], SENTIMENT_CONFIG)) == [keeper]


def test_sentiment_config_keeps_only_conversational_events() -> None:
    keepers: list[TranscriptEvent] = [user("please refactor"), assistant("claude-opus-4-7")]
    dropped: list[TranscriptEvent] = [
        OtherEvent(type="summary", raw={"type": "summary"}),
        ModeEvent(session_id=SessionId("s"), channel="mode", value="normal"),
    ]
    assert list(apply_filters(keepers + dropped, SENTIMENT_CONFIG)) == keepers


def test_sentiment_config_keeps_is_meta_user() -> None:
    keeper = user("a real prompt that happens to be flagged meta", is_meta=True)
    assert list(apply_filters([keeper], SENTIMENT_CONFIG)) == [keeper]


def test_default_config_passes_everything_through() -> None:
    events: list[TranscriptEvent] = [
        user("<system-reminder>x</system-reminder>"),
        user("sidechain", is_sidechain=True),
        assistant("<synthetic>"),
        user("from sdk", entrypoint="sdk-cli"),
    ]
    assert list(apply_filters(events, FilterConfig())) == events


def test_sentiment_config_matches_legacy() -> None:
    events: list[TranscriptEvent] = [
        user("please refactor the parser"),
        user("<system-reminder>x</system-reminder>"),
        user("[Request interrupted by user] do it differently"),
        user("Stop hook feedback: lint failed"),
        user("   "),
        user("a real prompt flagged meta", is_meta=True),
        user("<teammate-message>hi"),
        user("from sdk", entrypoint="sdk-cli"),
        AssistantEvent(
            meta=meta(is_sidechain=True), model="claude-opus-4-7", text="subagent reply", blocks=(), stop_reason=None
        ),
        assistant("<synthetic>"),
        assistant("claude-opus-4-7"),
        OtherEvent(type="summary", raw={"type": "summary"}),
        ModeEvent(session_id=SessionId("s"), channel="mode", value="normal"),
    ]
    assert list(apply_filters(events, SENTIMENT_CONFIG)) == [e for e in events if legacy_keep(e, LEGACY_SENTIMENT)]


@pytest.mark.parametrize("path", real_corpus(), ids=lambda p: f"{p.parent.name}/{p.name}")
def test_sentiment_config_legacy_parity_on_real_corpus(path: Path) -> None:
    events = parse_events_from_bytes(path.read_bytes())
    assert list(apply_filters(events, SENTIMENT_CONFIG)) == [e for e in events if legacy_keep(e, LEGACY_SENTIMENT)]
