from __future__ import annotations

from typing import TYPE_CHECKING

import orjson
import pytest

from cc_transcript.filterspec import (
    FRUSTRATION_GROUPS,
    INTERRUPT_MARKER_GROUPS,
    MILD_IMPATIENCE_GROUPS,
    PUSHBACK_SPEC,
    SENTIMENT_SPEC,
    STOP_HOOK_GROUPS,
    STRUCTURAL_NOISE_GROUPS,
    USERS,
    Clause,
    FilterSpec,
    TextMatchesAny,
    apply_spec,
    is_portable,
    spec_to_json,
)
from cc_transcript.parser import parse_events
from tests.test_backend_parity import fixture_bytes, real_corpus, requires_rust

if TYPE_CHECKING:
    from pathlib import Path

    from cc_transcript.models import TranscriptEvent

ALL_GROUPS_SPEC = FilterSpec(
    clauses=(
        Clause(
            TextMatchesAny(
                STRUCTURAL_NOISE_GROUPS
                + INTERRUPT_MARKER_GROUPS
                + STOP_HOOK_GROUPS
                + FRUSTRATION_GROUPS
                + MILD_IMPATIENCE_GROUPS
            ),
            applies_to=USERS,
        ),
    )
)

PRESETS = {"sentiment": SENTIMENT_SPEC, "pushback": PUSHBACK_SPEC, "all_groups": ALL_GROUPS_SPEC}

# One line per named group (positive), plus near-misses and case folds. The
# parity assertion is Rust == Python; whether each line matches is incidental.
BATTERY = [
    "<system-reminder>do this</system-reminder>",
    "<SYSTEM-REMINDER>uppercase</SYSTEM-REMINDER>",
    "<local-command-stdout>out",
    "<command-message>m",
    "<task-notification>n",
    "<teammate-message>hi",
    "<scheduled-task>auto",
    "<persisted-output>p",
    "<output-file>f",
    "Caveat: The messages below were generated by the user while running local commands.",
    "REMAINING_TASKS_ACKNOWLEDGED",
    "<<some-key>>",
    "Base directory for this skill: /x",
    "leading then Base directory for this skill: /x",  # ^-anchored: should NOT match
    "### Alpha ### ### Beta ### ### Gamma ###",
    "# Augment Agent",
    "this # Augment Agent not at start",  # ^-anchored
    "[Request interrupted by user]",
    "Stop hook feedback: ruff failed",
    "wtf this is broken",
    "stop guessing the imports",
    "you're useless",
    "and again it broke",
    "for the third time, fix it",
    "please refactor the parser carefully",  # clean keeper
    "system reminder without brackets",  # near-miss, no <
    "interrupted by user without the bracket",  # near-miss
    "héllo 🤖 漢字 unicode",
]


def battery_bytes() -> bytes:
    def line(text: str) -> bytes:
        return orjson.dumps(
            {
                "type": "user",
                "uuid": "u",
                "sessionId": "s",
                "timestamp": "2026-01-01T00:00:00Z",
                "message": {"role": "user", "content": text},
            }
        )

    return b"\n".join(line(text) for text in BATTERY)


def rust_filtered(path: Path, spec: FilterSpec) -> list[TranscriptEvent]:
    from cc_transcript import _parser_rs

    out = _parser_rs.stream_parse([(str(path), 1.0)], 1, spec_to_json(spec)).recv()
    return [] if out is None else out[2]


def py_filtered(path: Path, spec: FilterSpec) -> list[TranscriptEvent]:
    return list(apply_spec(parse_events(path), spec))


def test_presets_are_portable() -> None:
    assert all(is_portable(spec) for spec in PRESETS.values())


@requires_rust
@pytest.mark.parametrize("preset", PRESETS, ids=list(PRESETS))
def test_battery_parity(tmp_path: Path, preset: str) -> None:
    path = tmp_path / "battery.jsonl"
    path.write_bytes(battery_bytes())
    assert rust_filtered(path, PRESETS[preset]) == py_filtered(path, PRESETS[preset])


@requires_rust
@pytest.mark.parametrize("preset", PRESETS, ids=list(PRESETS))
def test_fixture_parity(tmp_path: Path, preset: str) -> None:
    path = tmp_path / "fixture.jsonl"
    path.write_bytes(fixture_bytes())
    assert rust_filtered(path, PRESETS[preset]) == py_filtered(path, PRESETS[preset])


@requires_rust
@pytest.mark.parametrize("path", real_corpus(), ids=lambda p: f"{p.parent.name}/{p.name}")
def test_real_corpus_parity(path: Path) -> None:
    for spec in PRESETS.values():
        assert rust_filtered(path, spec) == py_filtered(path, spec), f"diverged on {path}"
