"""Golden parity: the Rust activity lift reproduces the Python ``SessionActivity.from_events``.

The golden (``testdata/activity_golden.json``, regenerated by ``scripts/gen_activity_golden.py``)
freezes the Python lift's projection over the first ``MAX_EVENTS`` events of every corpus file —
turn boundaries, tool-use records, edit records, result indexing, and same-file hunk overlaps —
plus batteries of hand-built ``hunk_overlap`` and ``overlap_between`` cases. Events are sourced
through the Rust parser on both sides, so these assertions isolate the *lift*:
``_native.activity_lift`` reproduces each file's projection, the native overlap functions reproduce
each overlap case, and the Python references still project to the frozen golden.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _native
from cc_transcript.activity import hunk_overlap
from cc_transcript.evidence import overlap_between
from cc_transcript.tools import Hunk
from scripts.gen_activity_golden import CORPUS, MAX_EVENTS, SYNTHETIC_CASES, project_file
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "activity_golden.json").read_text(encoding="utf-8")
)
LIFT_CASES = [pytest.param(rel, id=rel) for rel in GOLDEN["lifts"]]
SYNTHETIC = [pytest.param(name, id=name) for name in GOLDEN["synthetic"]]
HUNK_CASES = [pytest.param(case, id=f"hunk-{index}") for index, case in enumerate(GOLDEN["hunk_overlap_cases"])]
OVERLAP_BETWEEN_CASES = [
    pytest.param(case, id=f"overlap-between-{index}")
    for index, case in enumerate(GOLDEN["overlap_between_cases"])
]


@requires_rust
@pytest.mark.parametrize("rel", LIFT_CASES)
def test_rust_activity_lift_matches_golden(rel: str) -> None:
    assert _native.activity_lift(str(CORPUS / rel), MAX_EVENTS) == GOLDEN["lifts"][rel]


@requires_rust
@pytest.mark.parametrize("rel", LIFT_CASES)
def test_python_activity_lift_matches_golden(rel: str) -> None:
    assert project_file(CORPUS / rel) == GOLDEN["lifts"][rel]


@requires_rust
@pytest.mark.parametrize("name", SYNTHETIC)
def test_rust_synthetic_matches_golden(name: str, tmp_path: Path) -> None:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(SYNTHETIC_CASES[name], encoding="utf-8")
    assert _native.activity_lift(str(path), MAX_EVENTS) == GOLDEN["synthetic"][name]


@requires_rust
@pytest.mark.parametrize("name", SYNTHETIC)
def test_python_synthetic_matches_golden(name: str, tmp_path: Path) -> None:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(SYNTHETIC_CASES[name], encoding="utf-8")
    assert project_file(path) == GOLDEN["synthetic"][name]


@requires_rust
@pytest.mark.parametrize("case", HUNK_CASES)
def test_rust_hunk_overlap_matches_golden(case: dict) -> None:
    assert (
        _native.activity_hunk_overlap(case["a_old"], case["a_new"], case["b_old"], case["b_new"])
        == case["overlap"]
    )


@pytest.mark.parametrize("case", HUNK_CASES)
def test_python_hunk_overlap_matches_golden(case: dict) -> None:
    assert hunk_overlap(Hunk(case["a_old"], case["a_new"]), Hunk(case["b_old"], case["b_new"])) == case["overlap"]


@requires_rust
@pytest.mark.parametrize("case", OVERLAP_BETWEEN_CASES)
def test_overlap_between_matches_golden(case: dict) -> None:
    incorrect = tuple(Hunk(hunk["old"], hunk["new"]) for hunk in case["incorrect"])
    correction = tuple(Hunk(hunk["old"], hunk["new"]) for hunk in case["correction"])
    assert (
        _native.activity_overlap_between(
            [(hunk.old, hunk.new) for hunk in incorrect],
            [(hunk.old, hunk.new) for hunk in correction],
        )
        == case["overlap"]
    )
    assert overlap_between(incorrect, correction) == case["overlap"]
