from __future__ import annotations

import pytest

from cc_transcript.builders import (
    build_spec,
    drop_compacted,
    drop_empty,
    drop_entrypoints,
    drop_junk,
    drop_sidechain,
    drop_synthetic,
    keep_only,
)
from cc_transcript.filterspec import ASSISTANTS, USERS, apply_spec
from cc_transcript.models import (
    AssistantEvent,
    TranscriptEvent,
    UserEvent,
)
from tests import testkit

SENTIMENT_SPEC = build_spec(
    keep_only("user", "assistant"),
    drop_synthetic(),
    drop_empty(only_from=ASSISTANTS),
    drop_empty(only_from=USERS),
    drop_junk("structural", "interrupt", "stop_hook"),
    drop_sidechain(except_assistants=True),
    drop_compacted(),
    drop_entrypoints({"sdk-cli"}),
)


def user(text: str, **kw: bool | str | None) -> UserEvent:
    event = testkit.parse_event(testkit.user_line("u", text, session_id="s", **kw))
    assert isinstance(event, UserEvent)
    return event


def assistant(model: str, text: str = "hi") -> AssistantEvent:
    event = testkit.parse_event(testkit.assistant_line("a", text, model=model, session_id="s"))
    assert isinstance(event, AssistantEvent)
    return event


@pytest.mark.parametrize(
    "event",
    [
        pytest.param(user("real prompt", is_sidechain=True), id="sidechain"),
        pytest.param(assistant("<synthetic>"), id="synthetic"),
        pytest.param(user("from sdk", entrypoint="sdk-cli"), id="sdk-cli"),
        pytest.param(user("<system-reminder>do this</system-reminder>"), id="system-reminder-junk"),
        pytest.param(
            user("Caveat: The messages below were generated by the user while running local commands."),
            id="local-command-caveat-junk",
        ),
        pytest.param(user("[Request interrupted by user]"), id="interrupt-marker-junk"),
        pytest.param(user("  [request INTERRUPTED by user for tool use]"), id="interrupt-marker-casefolded-junk"),
        pytest.param(user("real but compacted", is_compact_summary=True), id="compact-summary"),
        pytest.param(user("   "), id="empty-user"),
        pytest.param(assistant("claude-opus-4-7", text=""), id="empty-assistant"),
        pytest.param(testkit.parse_event(testkit.other_line("summary")), id="summary-other"),
        pytest.param(testkit.parse_event(testkit.other_line("queue-operation")), id="queue-operation-other"),
        pytest.param(testkit.parse_event(testkit.mode_line("normal", session_id="s")), id="mode"),
    ],
)
def test_sentiment_spec_drops(event: TranscriptEvent) -> None:
    keeper = user("please refactor the parser")
    assert list(apply_spec([event, keeper], SENTIMENT_SPEC)) == [keeper]


def test_sentiment_spec_keeps_only_conversational_events() -> None:
    keepers: list[TranscriptEvent] = [user("please refactor"), assistant("claude-opus-4-7")]
    dropped: list[TranscriptEvent] = [
        testkit.parse_event(testkit.other_line("summary")),
        testkit.parse_event(testkit.mode_line("normal", session_id="s")),
    ]
    assert list(apply_spec(keepers + dropped, SENTIMENT_SPEC)) == keepers


def test_sentiment_spec_keeps_is_meta_user() -> None:
    keeper = user("a real prompt that happens to be flagged meta", is_meta=True)
    assert list(apply_spec([keeper], SENTIMENT_SPEC)) == [keeper]


def test_sentiment_spec_keeps_mid_text_interrupt_mention() -> None:
    keeper = user("the transcript quoted [Request interrupted by user] mid-sentence")
    assert list(apply_spec([keeper], SENTIMENT_SPEC)) == [keeper]


def test_empty_spec_passes_everything_through() -> None:
    events: list[TranscriptEvent] = [
        user("<system-reminder>x</system-reminder>"),
        user("sidechain", is_sidechain=True),
        assistant("<synthetic>"),
        user("from sdk", entrypoint="sdk-cli"),
    ]
    assert list(apply_spec(events, build_spec())) == events
