"""Golden parity: the Rust ``discovery_*`` ports reproduce the Python discovery walk.

The golden (``testdata/discovery_golden.json``, regenerated by
``scripts/gen_discovery_golden.py``) freezes, per synthesized project-dir tree, what each
Python discovery function returns. Each test rebuilds the tree in a fresh tmp dir:
``test_rust_*`` drives the Rust ``discovery_*`` pyfunctions and ``test_python_*`` re-drives
the Python reference, both asserting the frozen golden — so the Rust assertions isolate the
port and the Python assertions guard against reference drift.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _parser_rs
from scripts.gen_discovery_golden import (
    DISCOVERY_SCENARIOS,
    IS_SUBAGENT_CASES,
    build_tree,
    rel,
    run_python,
)
from tests.support import requires_rust

GOLDEN = json.loads((Path(__file__).resolve().parent / "testdata" / "discovery_golden.json").read_text(encoding="utf-8"))
SCENARIO_NAMES = [pytest.param(name, id=name) for name in DISCOVERY_SCENARIOS]


def run_rust(root: Path, scenario: dict[str, object]) -> dict[str, object]:
    build_tree(root, scenario["tree"])  # type: ignore[arg-type]
    args = scenario["args"]
    assert isinstance(args, dict)
    match scenario["func"]:
        case "find_transcripts":
            return {"transcripts": [rel(root, path) for path in _parser_rs.discovery_find_transcripts(str(root))]}
        case "find_in":
            directory = root / str(args["directory"])
            known = {str(root / key): value for key, value in (args.get("known_mtimes") or {}).items()} or None
            result = _parser_rs.discovery_find_in(str(directory), args.get("name_contains"), args.get("limit"), known)
            return {"found": [[rel(root, path), mtime] for path, mtime in result]}
        case "find_transcript":
            hit = _parser_rs.discovery_find_transcript(str(root), str(args["session_id"]))
            return {"hit": None if hit is None else rel(root.resolve(), hit)}
        case "subagents":
            path = root / str(args["path"])
            return {
                "paths": [rel(root, p) for p in _parser_rs.discovery_subagent_paths(str(path))],
                "transcripts": {tid: rel(root, p) for tid, p in _parser_rs.discovery_subagent_transcripts(str(path)).items()},
            }
        case func:
            raise ValueError(f"unknown discovery func {func!r}")


@requires_rust
@pytest.mark.parametrize("name", SCENARIO_NAMES)
def test_rust_discovery_matches_golden(name: str, tmp_path: Path) -> None:
    assert run_rust(tmp_path, DISCOVERY_SCENARIOS[name]) == GOLDEN["scenarios"][name]


@requires_rust
@pytest.mark.parametrize("name", SCENARIO_NAMES)
def test_python_discovery_matches_golden(name: str, tmp_path: Path) -> None:
    assert run_python(tmp_path, DISCOVERY_SCENARIOS[name]) == GOLDEN["scenarios"][name]


@requires_rust
@pytest.mark.parametrize("case", [pytest.param(case, id=case["path"]) for case in GOLDEN["is_subagent_path"]])
def test_rust_is_subagent_path_matches_golden(case: dict) -> None:
    assert _parser_rs.discovery_is_subagent_path(case["path"]) == case["result"]


@pytest.mark.parametrize("path, expected", IS_SUBAGENT_CASES)
def test_python_is_subagent_path_matches_expected(path: str, expected: bool) -> None:
    from cc_transcript.discovery import is_subagent_path

    assert is_subagent_path(Path(path)) is expected
