"""Golden parity: the Rust ``command_parse`` port reproduces the frozen ``CommandLine`` structure.

The golden (``testdata/command_golden.json``, regenerated by
``scripts/gen_command_golden.py``) freezes the ``CommandLine`` structure for the
command-prefix pins, every distinct corpus ``Bash`` command, and hand-built edge cases.
This asserts the Rust ``_native.command_parse`` reproduces each entry exactly — the
grammar-lockstep gate between the tree-sitter-bash wheel and crate.

Three pathological shapes are deliberately excluded, where Rust and Python diverge and no
real transcript reaches them (see the commit body for details): a non-ASCII wrapper
"assignment" arg — ``env ²=x cmd`` / ``env ‿=x cmd`` — where Python ``re`` and the Rust
``regex`` crate classify the char differently in the ``^\\w+=`` unwrap skip; and a file
descriptor above ``i64::MAX`` — ``9223372036854775808>out`` — where Python keeps the
arbitrary-precision int and Rust yields ``None``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _native
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "command_golden.json").read_text(encoding="utf-8")
)
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_command_parse_matches_golden(entry: dict) -> None:
    assert _native.command_parse(entry["command"]) == entry["parsed"]
