"""Golden pin: the native ``cost_of_json`` aggregator reproduces the frozen breakdown.

The golden (``testdata/cost_golden.json``, regenerated by
``scripts/gen_cost_golden.py``) freezes the ``CostBreakdown`` for every distinct
corpus usage block and the hand-built edge cases. This asserts
``_native.cost_of_json`` reproduces each breakdown exactly, that an unresolvable
model raises ``KeyError``, and that the raw-JSON edge cases (an f64-overflowing
token, a truthy non-object ``cache_creation``) raise on the native reader.
"""

from __future__ import annotations

import json
from pathlib import Path

import orjson
import pytest

from cc_transcript import _native
from tests.support import requires_rust

GOLDEN = json.loads((Path(__file__).resolve().parent / "testdata" / "cost_golden.json").read_text(encoding="utf-8"))
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_cost_of_json_matches_golden(entry: dict) -> None:
    assert _native.cost_of_json(json.dumps(entry["usage"]), entry["model"]) == entry["breakdown"]


@requires_rust
def test_unresolvable_model_raises_key_error() -> None:
    usage = {"input_tokens": 1, "output_tokens": 1, "cache_read_input_tokens": 0, "cache_creation_input_tokens": 0}
    with pytest.raises(KeyError):
        _native.cost_of_json(json.dumps(usage), "gpt-5")


@requires_rust
def test_f64_overflow_token_raises_on_both_backends() -> None:
    # A token that overflows f64: orjson refuses to load it, and the Rust reader raises.
    raw = f'{{"input_tokens":1{"0" * 400},"output_tokens":0,"cache_read_input_tokens":0,"cache_creation_input_tokens":0}}'
    with pytest.raises(ValueError):
        _native.cost_of_json(raw, "claude-opus-4-8")
    with pytest.raises(orjson.JSONDecodeError):
        orjson.loads(raw)


@requires_rust
def test_truthy_non_object_cache_creation_raises_type_error() -> None:
    raw = (
        '{"input_tokens":0,"output_tokens":0,"cache_read_input_tokens":0,'
        '"cache_creation_input_tokens":0,"cache_creation":[1]}'
    )
    with pytest.raises(TypeError):
        _native.cost_of_json(raw, "claude-opus-4-8")
