"""Golden parity: the Rust ``bucket_events`` port reproduces the Python bucketer.

The golden (``testdata/buckets_golden.json``, regenerated by
``scripts/gen_buckets_golden.py``) freezes each scorable bucket's ``session_id``,
``bucket_index``, ``bucket_start_ms``, and member ``uuids`` for a curated battery of
synthetic transcripts. This asserts the Rust ``_parser_rs.bucket_events`` reproduces
each bucketing exactly, that the Python ``ConversationBucketer.bucket_events``
reference still does, and that ``extract_bucket_keys`` stays consistent with it.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _parser_rs
from cc_transcript.parser import parse_events_from_bytes
from cc_transcript.sentiment.buckets import extract_bucket_keys
from scripts.gen_buckets_golden import project, to_bytes
from tests.support import requires_rust

GOLDEN = json.loads((Path(__file__).resolve().parent / "testdata" / "buckets_golden.json").read_text(encoding="utf-8"))
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_bucket_events_matches_golden(entry: dict) -> None:
    assert _parser_rs.bucket_events(to_bytes(tuple(entry["records"]))) == entry["buckets"]


@pytest.mark.parametrize("entry", CASES)
def test_python_bucket_events_matches_golden(entry: dict) -> None:
    assert project(tuple(entry["records"])) == entry["buckets"]


@pytest.mark.parametrize("entry", CASES)
def test_extract_bucket_keys_matches_buckets(entry: dict) -> None:
    keys = extract_bucket_keys(parse_events_from_bytes(to_bytes(tuple(entry["records"]))))
    assert [(k.session_id, k.bucket_index) for k in keys] == [(b["session_id"], b["bucket_index"]) for b in entry["buckets"]]
