"""Golden parity: the Rust ``cost_of_json`` port reproduces the Python ``cost_of``.

The golden (``testdata/cost_golden.json``, regenerated by
``scripts/gen_cost_golden.py``) freezes the Python ``CostBreakdown`` for every
distinct corpus usage block and the hand-built edge cases. This asserts the Rust
``_parser_rs.cost_of_json`` reproduces each breakdown exactly and that the Python
reference still costs to the frozen golden, plus that an unresolvable model raises
``KeyError`` on both backends.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

import pytest

from cc_transcript import _parser_rs
from cc_transcript.cost import cost_of
from scripts.gen_cost_golden import usage_from_dict
from tests.support import requires_rust

GOLDEN = json.loads((Path(__file__).resolve().parent / "testdata" / "cost_golden.json").read_text(encoding="utf-8"))
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_cost_of_json_matches_golden(entry: dict) -> None:
    assert _parser_rs.cost_of_json(json.dumps(entry["usage"]), entry["model"]) == entry["breakdown"]


@pytest.mark.parametrize("entry", CASES)
def test_python_cost_of_matches_golden(entry: dict) -> None:
    assert asdict(cost_of(usage_from_dict(entry["usage"]), entry["model"])) == entry["breakdown"]


@requires_rust
def test_unresolvable_model_raises_key_error() -> None:
    usage = {"input_tokens": 1, "output_tokens": 1, "cache_read_input_tokens": 0, "cache_creation_input_tokens": 0}
    with pytest.raises(KeyError):
        _parser_rs.cost_of_json(json.dumps(usage), "gpt-5")
    with pytest.raises(KeyError):
        cost_of(usage_from_dict(usage), "gpt-5")
