from __future__ import annotations

from datetime import UTC, datetime

import pytest

from cc_transcript.builders import (
    build_spec,
    drop_compacted,
    drop_empty,
    drop_entrypoints,
    drop_junk,
    drop_sidechain,
    drop_synthetic,
    keep_only,
)
from cc_transcript.filterspec import ASSISTANTS, USERS, apply_spec
from cc_transcript.models import (
    AssistantEvent,
    EntryMeta,
    EventUuid,
    ModeEvent,
    OtherEvent,
    SessionId,
    TranscriptEvent,
    UserEvent,
)

SENTIMENT_SPEC = build_spec(
    keep_only("user", "assistant"),
    drop_synthetic(),
    drop_empty(only_from=ASSISTANTS),
    drop_empty(only_from=USERS),
    drop_junk("structural", "interrupt", "stop_hook"),
    drop_sidechain(except_assistants=True),
    drop_compacted(),
    drop_entrypoints({"sdk-cli"}),
)


def meta(
    *,
    is_sidechain: bool = False,
    is_meta: bool = False,
    is_compact_summary: bool = False,
    entrypoint: str | None = "cli",
) -> EntryMeta:
    return EntryMeta(
        uuid=EventUuid("u"),
        parent_uuid=None,
        session_id=SessionId("s"),
        timestamp=datetime(2026, 1, 1, tzinfo=UTC),
        cwd="/repo",
        git_branch="main",
        cc_version=None,
        is_sidechain=is_sidechain,
        is_meta=is_meta,
        entrypoint=entrypoint,
        is_compact_summary=is_compact_summary,
        is_visible_in_transcript_only=False,
    )


def user(text: str, **kw: bool | str | None) -> UserEvent:
    return UserEvent(meta=meta(**kw), text=text, blocks=(), interrupted=False)  # type: ignore[arg-type]


def assistant(model: str) -> AssistantEvent:
    return AssistantEvent(meta=meta(), model=model, text="hi", blocks=(), stop_reason=None, usage=None)


@pytest.mark.parametrize(
    "event",
    [
        pytest.param(user("real prompt", is_sidechain=True), id="sidechain"),
        pytest.param(assistant("<synthetic>"), id="synthetic"),
        pytest.param(user("from sdk", entrypoint="sdk-cli"), id="sdk-cli"),
        pytest.param(user("<system-reminder>do this</system-reminder>"), id="system-reminder-junk"),
        pytest.param(
            user("Caveat: The messages below were generated by the user while running local commands."),
            id="local-command-caveat-junk",
        ),
        pytest.param(user("real but compacted", is_compact_summary=True), id="compact-summary"),
        pytest.param(user("   "), id="empty-user"),
        pytest.param(
            AssistantEvent(meta=meta(), model="claude-opus-4-7", text="", blocks=(), stop_reason=None, usage=None),
            id="empty-assistant",
        ),
        pytest.param(OtherEvent(type="summary", raw={"type": "summary"}), id="summary-other"),
        pytest.param(OtherEvent(type="queue-operation", raw={"type": "queue-operation"}), id="queue-operation-other"),
        pytest.param(ModeEvent(session_id=SessionId("s"), channel="mode", value="normal"), id="mode"),
    ],
)
def test_sentiment_spec_drops(event: TranscriptEvent) -> None:
    keeper = user("please refactor the parser")
    assert list(apply_spec([event, keeper], SENTIMENT_SPEC)) == [keeper]


def test_sentiment_spec_keeps_only_conversational_events() -> None:
    keepers: list[TranscriptEvent] = [user("please refactor"), assistant("claude-opus-4-7")]
    dropped: list[TranscriptEvent] = [
        OtherEvent(type="summary", raw={"type": "summary"}),
        ModeEvent(session_id=SessionId("s"), channel="mode", value="normal"),
    ]
    assert list(apply_spec(keepers + dropped, SENTIMENT_SPEC)) == keepers


def test_sentiment_spec_keeps_is_meta_user() -> None:
    keeper = user("a real prompt that happens to be flagged meta", is_meta=True)
    assert list(apply_spec([keeper], SENTIMENT_SPEC)) == [keeper]


def test_empty_spec_passes_everything_through() -> None:
    events: list[TranscriptEvent] = [
        user("<system-reminder>x</system-reminder>"),
        user("sidechain", is_sidechain=True),
        assistant("<synthetic>"),
        user("from sdk", entrypoint="sdk-cli"),
    ]
    assert list(apply_spec(events, build_spec())) == events
