"""Golden parity: the Rust ``notifications_replay`` port reproduces Python ``Notifications``.

The golden (``testdata/notifications_golden.json``, regenerated by
``scripts/gen_notifications_golden.py``) freezes the ``queued``/``delivered``/
``enqueued`` replay for a curated battery of synthetic transcripts. This asserts the
Rust ``_parser_rs.notifications_replay`` reproduces each replay exactly and that the
Python ``Notifications.from_events`` reference still does.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _parser_rs
from cc_transcript.models import OtherEvent, UserEvent
from cc_transcript.notifications import Notifications
from cc_transcript.parser import parse_events_from_bytes
from scripts.gen_notifications_golden import to_bytes
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "notifications_golden.json").read_text(encoding="utf-8")
)
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_notifications_replay_matches_golden(entry: dict) -> None:
    assert _parser_rs.notifications_replay(to_bytes(tuple(entry["records"]))) == entry["expected"]


@pytest.mark.parametrize("entry", CASES)
def test_python_notifications_match_golden(entry: dict) -> None:
    n = Notifications.from_events(parse_events_from_bytes(to_bytes(tuple(entry["records"]))))
    assert {"queued": list(n.queued), "delivered": list(n.delivered), "enqueued": list(n.enqueued)} == entry["expected"]


# Duplicate object keys can't be built from a Python dict — orjson (the Python parser)
# keeps the last occurrence, so the Rust replay must too. Python is the oracle here.
DUP_KEY_RAW = [
    pytest.param(
        '{"type":"queue-operation","operation":"dequeue","operation":"enqueue","content":"a","content":"b"}',
        id="operation-and-content-last-wins",
    ),
]


@requires_rust
@pytest.mark.parametrize("raw", DUP_KEY_RAW)
def test_dup_keys_replay_last_wins(raw: str) -> None:
    n = Notifications.from_events(parse_events_from_bytes(raw.encode()))
    expected = {"queued": list(n.queued), "delivered": list(n.delivered), "enqueued": list(n.enqueued)}
    assert _parser_rs.notifications_replay(raw.encode()) == expected


# The Python reference dispatches a duplicate top-level "type" to the LAST occurrence (orjson
# dedups before parsing); the Rust fast path diverges to first-wins (accepted, e0ab2411 item 9).
DUP_TYPE_DISPATCH = [
    pytest.param(
        b'{"type":"queue-operation","operation":"enqueue","type":"user","uuid":"u","sessionId":"s",'
        b'"timestamp":"2026-01-02T03:04:05Z","message":{"role":"user","content":"hi"}}',
        UserEvent,
        id="queue-op-then-user",
    ),
    pytest.param(
        b'{"type":"user","uuid":"u","sessionId":"s","timestamp":"2026-01-02T03:04:05Z",'
        b'"message":{"role":"user","content":"hi"},"type":"queue-operation","operation":"enqueue"}',
        OtherEvent,
        id="user-then-queue-op",
    ),
]


@pytest.mark.parametrize(("raw", "expected"), DUP_TYPE_DISPATCH)
def test_python_parser_dispatches_dup_type_last_wins(raw: bytes, expected: type) -> None:
    (event,) = parse_events_from_bytes(raw)
    assert isinstance(event, expected)
