from __future__ import annotations

from typing import TYPE_CHECKING

import orjson
import pytest

from cc_transcript.builders import (
    NOISE_SPEC,
    build_spec,
    drop_compacted,
    drop_empty,
    drop_entrypoints,
    drop_junk,
    drop_meta_flag,
    drop_phrases,
    drop_short,
    drop_sidechain,
    drop_synthetic,
    keep_only,
)
from cc_transcript.filterspec import (
    ASSISTANTS,
    COMMAND_ECHO_GROUPS,
    CONTINUATION_GROUPS,
    FRUSTRATION_GROUPS,
    INTERRUPT_MARKER_GROUPS,
    MILD_IMPATIENCE_GROUPS,
    RESUME_PHRASE_SET,
    STOP_HOOK_GROUPS,
    STRUCTURAL_NOISE_GROUPS,
    TRIVIAL_ACK_SET,
    USERS,
    Clause,
    FilterSpec,
    TextMatchesAny,
    apply_spec,
    is_portable,
    spec_to_json,
)
from cc_transcript.models import AttachmentEvent
from cc_transcript.parser import parse_events_from_bytes
from tests.support import fixture_bytes, real_corpus, requires_rust

if TYPE_CHECKING:
    from pathlib import Path

    from cc_transcript.models import TranscriptEvent

ALL_GROUPS_SPEC = FilterSpec(
    clauses=(
        Clause(
            TextMatchesAny(
                STRUCTURAL_NOISE_GROUPS
                + INTERRUPT_MARKER_GROUPS
                + STOP_HOOK_GROUPS
                + CONTINUATION_GROUPS
                + COMMAND_ECHO_GROUPS
                + FRUSTRATION_GROUPS
                + MILD_IMPATIENCE_GROUPS
            ),
            applies_to=USERS,
        ),
    )
)

# The consumer specs are rebuilt here from the public builders so the Rust↔Python
# parity guarantee keeps covering their real shapes after they moved to consumers.
SENTIMENT_SPEC = build_spec(
    keep_only("user", "assistant"),
    drop_synthetic(),
    drop_empty(only_from=ASSISTANTS),
    drop_empty(only_from=USERS),
    drop_junk("structural", "interrupt", "stop_hook"),
    drop_sidechain(except_assistants=True),
    drop_compacted(),
    drop_entrypoints({"sdk-cli"}),
)

PUSHBACK_SPEC = build_spec(
    keep_only("user"),
    drop_sidechain(),
    drop_meta_flag("is_meta"),
    drop_compacted(),
    drop_empty(only_from=USERS),
    drop_junk("structural", "agent_injection", "stop_hook", "continuation", "command_echo"),
    drop_phrases(TRIVIAL_ACK_SET | RESUME_PHRASE_SET),
    drop_short(2),
)

# Positive attachment coverage: keep_only("attachment") exercises Kind::Attachment
# through parse_kind, and an unscoped MetaFlag reaches attachment envelopes.
ATTACHMENTS_ONLY_SPEC = build_spec(keep_only("attachment"))
SIDECHAIN_DROP_SPEC = build_spec(drop_sidechain())

PRESETS = {
    "sentiment": SENTIMENT_SPEC,
    "pushback": PUSHBACK_SPEC,
    "all_groups": ALL_GROUPS_SPEC,
    "noise": NOISE_SPEC,
    "attachments_only": ATTACHMENTS_ONLY_SPEC,
    "sidechain_drop": SIDECHAIN_DROP_SPEC,
}

# One line per named group (positive), plus near-misses and case folds. The
# parity assertion is Rust == Python; whether each line matches is incidental.
BATTERY = [
    "<system-reminder>do this</system-reminder>",
    "<SYSTEM-REMINDER>uppercase</SYSTEM-REMINDER>",
    "<local-command-stdout>out",
    "<command-message>m",
    "<task-notification>n",
    "<teammate-message>hi",
    "<scheduled-task>auto",
    "  <teammate-message>indented banner",  # leading whitespace tolerated: still a banner
    "why does the transcript mention <teammate-message x> here",  # mid-text mention: authored, not a banner
    "<teammate-message\u0301>",  # combining mark (U+0301) after the tag name: not a portable boundary, not a banner
    "[Role Rem\u0131nder: dotless-i lookalike",  # dotless-I (U+0131): ASCII-pinned, not a banner
    "<persisted-output>p",
    "<output-file>f",
    "Caveat: The messages below were generated by the user while running local commands.",
    "REMAINING_TASKS_ACKNOWLEDGED",
    "<<some-key>>",
    "Base directory for this skill: /x",
    "leading then Base directory for this skill: /x",  # ^-anchored: should NOT match
    "### Alpha ### ### Beta ### ### Gamma ###",
    "# Augment Agent",
    "this # Augment Agent not at start",  # ^-anchored
    "[Request interrupted by user]",
    "  [request INTERRUPTED by user for tool use]",  # leading whitespace + case fold: still matches
    "she quoted [Request interrupted by user] mid-text",  # ^-anchored: mid-text marker kept
    "[Request ınterrupted by user]",  # dotless-I (U+0131) leading i: ASCII-pinned, no fold either backend
    "Stop hook feedback: ruff failed",
    "[Role Reminder: You are a Coordinator. You NEVER edit files directly.",
    "go ahead and commit and push all the repos",
    "ok push the branch",
    "we hit rate limits, you must resume them",
    "restart the subagents please",
    "<bash-input>uv run pytest</bash-input>",
    "<bash-stdout>123 passed</bash-stdout>",
    "why does <bash-input>uv run pytest</bash-input> show up here",  # \A-anchored: mid-text mention kept
    "we need to force-push, you should have rebased first",  # near-miss: 'push' mid-sentence, NOT continuation
    "wtf this is broken",
    "stop guessing the imports",
    "you're useless",
    "and again it broke",
    "for the third time, fix it",
    "please refactor the parser carefully",  # clean keeper
    "system reminder without brackets",  # near-miss, no <
    "interrupted by user without the bracket",  # near-miss
    "héllo 🤖 漢字 unicode",
]


def battery_bytes() -> bytes:
    def line(text: str) -> bytes:
        return orjson.dumps(
            {
                "type": "user",
                "uuid": "u",
                "sessionId": "s",
                "timestamp": "2026-01-01T00:00:00Z",
                "message": {"role": "user", "content": text},
            }
        )

    return b"\n".join(line(text) for text in BATTERY)


def rust_filtered(path: Path, spec: FilterSpec) -> list[TranscriptEvent]:
    from cc_transcript import _parser_rs

    out = _parser_rs.stream_parse([(str(path), 1.0)], 1, spec_to_json(spec)).recv()
    return [] if out is None else out[2]


def py_filtered(path: Path, spec: FilterSpec) -> list[TranscriptEvent]:
    return list(apply_spec(parse_events_from_bytes(path.read_bytes()), spec))


def test_presets_are_portable() -> None:
    assert all(is_portable(spec) for spec in PRESETS.values())


@requires_rust
@pytest.mark.parametrize("preset", PRESETS, ids=list(PRESETS))
def test_battery_parity(tmp_path: Path, preset: str) -> None:
    path = tmp_path / "battery.jsonl"
    path.write_bytes(battery_bytes())
    assert rust_filtered(path, PRESETS[preset]) == py_filtered(path, PRESETS[preset])


@requires_rust
@pytest.mark.parametrize("preset", PRESETS, ids=list(PRESETS))
def test_fixture_parity(tmp_path: Path, preset: str) -> None:
    path = tmp_path / "fixture.jsonl"
    path.write_bytes(fixture_bytes())
    assert rust_filtered(path, PRESETS[preset]) == py_filtered(path, PRESETS[preset])


@requires_rust
def test_attachment_positive_parity(tmp_path: Path) -> None:
    """KindIs("attachment") keeps attachments and MetaFlag drops sidechain ones, identically on both backends."""
    path = tmp_path / "fixture.jsonl"
    path.write_bytes(fixture_bytes())
    kept = py_filtered(path, ATTACHMENTS_ONLY_SPEC)
    assert kept == rust_filtered(path, ATTACHMENTS_ONLY_SPEC)
    assert kept
    assert all(isinstance(event, AttachmentEvent) for event in kept)
    assert any(event.meta.is_sidechain for event in kept)
    survivors = py_filtered(path, SIDECHAIN_DROP_SPEC)
    assert survivors == rust_filtered(path, SIDECHAIN_DROP_SPEC)
    assert any(isinstance(event, AttachmentEvent) for event in survivors)
    assert not any(isinstance(event, AttachmentEvent) and event.meta.is_sidechain for event in survivors)


@requires_rust
@pytest.mark.parametrize("path", real_corpus(), ids=lambda p: f"{p.parent.name}/{p.name}")
def test_real_corpus_parity(path: Path) -> None:
    for spec in PRESETS.values():
        assert rust_filtered(path, spec) == py_filtered(path, spec), f"diverged on {path}"
