"""Golden parity: the Rust ``notifications_replay`` port reproduces Python ``Notifications``.

The golden (``testdata/notifications_golden.json``, regenerated by
``scripts/gen_notifications_golden.py``) freezes the ``queued``/``delivered``/
``enqueued`` replay for a curated battery of synthetic transcripts. This asserts the
Rust ``_parser_rs.notifications_replay`` reproduces each replay exactly and that the
Python ``Notifications.from_events`` reference still does.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _parser_rs
from cc_transcript.notifications import Notifications
from cc_transcript.parser import parse_events_from_bytes
from scripts.gen_notifications_golden import to_bytes
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "notifications_golden.json").read_text(encoding="utf-8")
)
CASES = [pytest.param(entry, id=entry["id"]) for entry in GOLDEN]


@requires_rust
@pytest.mark.parametrize("entry", CASES)
def test_rust_notifications_replay_matches_golden(entry: dict) -> None:
    assert _parser_rs.notifications_replay(to_bytes(tuple(entry["records"]))) == entry["expected"]


@pytest.mark.parametrize("entry", CASES)
def test_python_notifications_match_golden(entry: dict) -> None:
    n = Notifications.from_events(parse_events_from_bytes(to_bytes(tuple(entry["records"]))))
    assert {"queued": list(n.queued), "delivered": list(n.delivered), "enqueued": list(n.enqueued)} == entry["expected"]
