"""Golden pins: the native facts aggregator reproduces the frozen projection.

The golden (``testdata/facts_golden.json``, regenerated by ``scripts/gen_facts_golden.py``)
freezes, per file, the flattened ``ToolFact`` list plus the ordered ``command_prefix_counts`` and
``mcp_summary`` aggregates — over every corpus file plus hand-built synthetic transcripts. These
assertions pin the native ``_native.tool_facts`` projection against the frozen golden, over both
the corpus and the synthetic cases. The aggregate lists are ordered, so tie-ordering is tested.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cc_transcript import _native
from scripts.gen_facts_golden import CORPUS, MAX_EVENTS, SYNTHETIC_CASES
from tests.support import requires_rust

GOLDEN = json.loads(
    (Path(__file__).resolve().parent / "testdata" / "facts_golden.json").read_text(encoding="utf-8")
)
FILE_CASES = [pytest.param(rel, id=rel) for rel in GOLDEN["files"]]
SYNTHETIC = [pytest.param(name, id=name) for name in GOLDEN["synthetic"]]


@requires_rust
@pytest.mark.parametrize("rel", FILE_CASES)
def test_rust_facts_matches_golden(rel: str) -> None:
    assert _native.tool_facts([str(CORPUS / rel)], MAX_EVENTS)[0] == GOLDEN["files"][rel]


@requires_rust
@pytest.mark.parametrize("name", SYNTHETIC)
def test_rust_synthetic_facts_matches_golden(name: str, tmp_path: Path) -> None:
    path = tmp_path / f"{name}.jsonl"
    path.write_text(SYNTHETIC_CASES[name], encoding="utf-8")
    assert _native.tool_facts([str(path)], MAX_EVENTS)[0] == GOLDEN["synthetic"][name]
