//! CC-protocol marker strings and the flattened interrupt / agent-injection / junk
//! alternations. Hand-owned; mirrored to Python via `_native.embedded_literals()`.

pub const DENIAL_PREFIX: &str =
    "The user doesn't want to proceed with this tool use. The tool use was rejected";
pub const DENIAL_KIND_USER_REJECTED: &str = "user-rejected";
pub const DENIAL_KIND_PERMISSION_RULE: &str = "permission-rule";
pub const USER_SAID_MARKER: &str = "To tell you how to proceed, the user said:\n";
pub const USER_SAID_TRAILER: &str = "Note: The user's next message";
pub const ANSWERED_PREFIX: &str = "Your questions have been answered: ";
pub const ANSWERED_TRAILER: &str = ". You can now continue with these answers in mind.";
pub const INTERRUPT_MARKER_PATTERN: &str = "(?:^\\s*\\[Request (?-i:[Ii])nterrupted by user)";
pub const AGENT_INJECTION_PATTERN: &str = "(?:\\A\\s*<(?:teammate-message|scheduled-task|agent-message|cross-session-message)(?:[\\s/>]|$))|(?:\\A\\s*Another Claude sess(?-i:[Ii])on sent a message:)|(?:\\A\\s*# Augment Agent(?:\\s|$))|(?:\\A\\s*\\[Role Rem(?-i:[Ii])nder(?:[\\s:\\]]|$))";
pub const TASK_NOTIFICATION_MARKER: &str = "<task-notification>";
pub const TOOL_USE_ID_PREFIX: &str = "<tool-use-id>";
pub const TOOL_USE_ID_SUFFIX: &str = "</tool-use-id>";
pub const SENTIMENT_JUNK_PATTERN: &str = "(?:<(?:system[_-](?:instruction|reminder)|local-command-(?:stdout|stderr|caveat)|command-(?:name|message|args)|task-notification|persisted-output|output-file)\\b)|(?:Caveat: The messages below were generated by the user while running local commands\\.)|(?:REMAINING_TASKS_ACKNOWLEDGED)|(?:<<[a-z][a-z0-9-]*>>)|(?:^Base directory for this skill:)|(?:(?:###\\s+[\\w][\\w \\-]{0,30}\\s+){3,}###)|(?:^\\s*\\[Request (?-i:[Ii])nterrupted by user)|(?:Stop hook feedback:)|(?:\\A\\s*<bash-(?:input|stdout|stderr)\\b)";
