"""Generate the Rust-embedded protocol literals from the canonical Python source.

Rust can't import `cc_transcript.filterspec` at compile time, so it embeds a copy
of the CC-protocol marker strings and the flattened interrupt/agent-injection
alternations, rendered here into `rust/src/generated/`. `filterspec.py` stays the
canonical source; this only mirrors it for the Rust build. `render()` is a pure
function so `tests/test_literals_parity.py` can reuse it to assert the committed
files still match byte-for-byte (drift guard).

Run: ``uv run python scripts/build_rust_literals.py``
"""

from __future__ import annotations

import math
from pathlib import Path

from cc_transcript.filterspec import (
    AGENT_INJECTION_GROUPS,
    ANSWERED_PREFIX,
    ANSWERED_TRAILER,
    DENIAL_PREFIX,
    INTERRUPT_MARKER_GROUPS,
    USER_SAID_MARKER,
    USER_SAID_TRAILER,
    group_pattern,
)
from cc_transcript.mining.confidence import LOW, NONE
from cc_transcript.mining.signals import ANSWER_NOTES_SEP, ANSWER_PREVIEW_SEP, NO_OPTION_SELECTED
from cc_transcript.mining.sourcekind import (
    INTERRUPT_REJECTION,
    PLAN_REVIEW,
    QUESTION_ANSWER,
    REVIEW_COMMENT,
    TRANSCRIPT_MESSAGE,
)
from cc_transcript.mining.spec import (
    ASK_USER_QUESTION_DETECTOR,
    DENIAL_DETECTOR,
    EXIT_PLAN_REJECTION_DETECTOR,
    INTERRUPT_DETECTOR,
    PLAN_REENTRY_DETECTOR,
    REVIEW_COMMENT_DETECTOR,
    TRANSCRIPT_MESSAGE_DETECTOR,
)

ROOT = Path(__file__).resolve().parent.parent
HEADER = "// @generated by scripts/build_rust_literals.py — do not edit; regenerate: uv run python scripts/build_rust_literals.py"
MAX_WIDTH = 100


def rust_str(value: str) -> str:
    def encode(char: str) -> str:
        match char:
            case "\\":
                return "\\\\"
            case '"':
                return '\\"'
            case "\n":
                return "\\n"
            case "\r":
                return "\\r"
            case "\t":
                return "\\t"
            case _ if " " <= char <= "~":
                return char
            case _:
                raise ValueError(f"non-printable-ASCII char U+{ord(char):04X} in Rust literal: {value!r}")

    return f'"{"".join(encode(char) for char in value)}"'


def const(name: str, value: str) -> str:
    # rustfmt breaks the `=` onto its own line only when the one-liner overflows
    # MAX_WIDTH and the continuation would fit; an unbreakable long literal stays inline.
    literal = rust_str(value)
    one_line = f"pub const {name}: &str = {literal};"
    return (
        f"pub const {name}: &str =\n    {literal};"
        if MAX_WIDTH < len(one_line) and len(literal) + 5 <= MAX_WIDTH
        else one_line
    )


def float_const(name: str, value: float) -> str:
    if not math.isfinite(value):
        raise ValueError(f"non-finite f64 in Rust literal: {name} = {value!r}")
    return f"pub const {name}: f64 = {value!r};"


def protocol_rs() -> str:
    consts = (
        ("DENIAL_PREFIX", DENIAL_PREFIX),
        ("USER_SAID_MARKER", USER_SAID_MARKER),
        ("USER_SAID_TRAILER", USER_SAID_TRAILER),
        ("ANSWERED_PREFIX", ANSWERED_PREFIX),
        ("ANSWERED_TRAILER", ANSWERED_TRAILER),
        ("INTERRUPT_MARKER_PATTERN", group_pattern(INTERRUPT_MARKER_GROUPS)),
        ("AGENT_INJECTION_PATTERN", group_pattern(AGENT_INJECTION_GROUPS)),
    )
    return "\n".join((HEADER, "", *(const(name, value) for name, value in consts))) + "\n"


def mining_rs() -> str:
    str_consts = (
        ("TRANSCRIPT_MESSAGE", TRANSCRIPT_MESSAGE),
        ("PLAN_REVIEW", PLAN_REVIEW),
        ("INTERRUPT_REJECTION", INTERRUPT_REJECTION),
        ("REVIEW_COMMENT", REVIEW_COMMENT),
        ("QUESTION_ANSWER", QUESTION_ANSWER),
        ("DETECTOR_TRANSCRIPT_MESSAGE", TRANSCRIPT_MESSAGE_DETECTOR),
        ("DETECTOR_EXIT_PLAN_REJECTION", EXIT_PLAN_REJECTION_DETECTOR),
        ("DETECTOR_PLAN_REENTRY", PLAN_REENTRY_DETECTOR),
        ("DETECTOR_DENIAL", DENIAL_DETECTOR),
        ("DETECTOR_INTERRUPT", INTERRUPT_DETECTOR),
        ("DETECTOR_REVIEW_COMMENT", REVIEW_COMMENT_DETECTOR),
        ("DETECTOR_ASK_USER_QUESTION", ASK_USER_QUESTION_DETECTOR),
        ("ANSWER_PREVIEW_SEP", ANSWER_PREVIEW_SEP),
        ("ANSWER_NOTES_SEP", ANSWER_NOTES_SEP),
        ("NO_OPTION_SELECTED", NO_OPTION_SELECTED),
    )
    float_consts = (("NONE", NONE), ("LOW", LOW))
    return (
        "\n".join(
            (
                HEADER,
                "",
                *(const(name, value) for name, value in str_consts),
                *(float_const(name, value) for name, value in float_consts),
            )
        )
        + "\n"
    )


def mod_rs() -> str:
    return "\n".join((HEADER, "", "pub mod mining;", "pub mod protocol;")) + "\n"


def render() -> dict[str, str]:
    return {
        "rust/src/generated/mod.rs": mod_rs(),
        "rust/src/generated/mining.rs": mining_rs(),
        "rust/src/generated/protocol.rs": protocol_rs(),
    }


def main() -> None:
    rendered = render()
    for relpath, content in rendered.items():
        path = ROOT / relpath
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {' + '.join(rendered)}")


if __name__ == "__main__":
    main()
