"""Generate the Rust-embedded protocol literals from the canonical Python source.

Rust can't import `cc_transcript.filterspec` at compile time, so it embeds a copy
of the CC-protocol marker strings and the flattened interrupt/agent-injection
alternations, rendered here into `rust/crates/core/src/generated/`. `filterspec.py` stays the
canonical source; this only mirrors it for the Rust build. `literals()` is the single
manifest keyed `"domain.NAME"`: `render()` emits the Rust files purely from it, and
`tests/test_literals_parity.py` derives both its byte-for-byte drift guard and its
`_parser_rs.embedded_literals()` parity expectation from it — so a constant added here
but missing from `python.rs`'s accessor fails the parity test automatically.

Run: ``uv run python scripts/build_rust_literals.py``
"""

from __future__ import annotations

import math
from pathlib import Path

from cc_transcript.command import ASSIGNMENT_RE, COMPOUND_OPS, MULTI_LEVEL_TOOLS, WRAPPER_COMMANDS
from cc_transcript.corrections import CORRECTIONS_DDL
from cc_transcript.filterspec import (
    AGENT_INJECTION_GROUPS,
    ANSWERED_PREFIX,
    ANSWERED_TRAILER,
    DENIAL_KIND_PERMISSION_RULE,
    DENIAL_KIND_USER_REJECTED,
    DENIAL_PREFIX,
    INTERRUPT_MARKER_GROUPS,
    USER_SAID_MARKER,
    USER_SAID_TRAILER,
    group_pattern,
)
from cc_transcript.mining.confidence import LOW, NONE
from cc_transcript.mining.signals import ANSWER_NOTES_SEP, ANSWER_PREVIEW_SEP, NO_OPTION_SELECTED
from cc_transcript.mining.sourcekind import (
    INTERRUPT_REJECTION,
    PLAN_REVIEW,
    QUESTION_ANSWER,
    REVIEW_COMMENT,
    TRANSCRIPT_MESSAGE,
)
from cc_transcript.mining.spec import (
    ASK_USER_QUESTION_DETECTOR,
    DENIAL_DETECTOR,
    EXIT_PLAN_REJECTION_DETECTOR,
    INTERRUPT_DETECTOR,
    PLAN_REENTRY_DETECTOR,
    REVIEW_COMMENT_DETECTOR,
    TRANSCRIPT_MESSAGE_DETECTOR,
)

ROOT = Path(__file__).resolve().parent.parent
HEADER = "// @generated by scripts/build_rust_literals.py — do not edit; regenerate: uv run python scripts/build_rust_literals.py"
MAX_WIDTH = 100


def rust_str(value: str) -> str:
    def encode(char: str) -> str:
        match char:
            case "\\":
                return "\\\\"
            case '"':
                return '\\"'
            case "\n":
                return "\\n"
            case "\r":
                return "\\r"
            case "\t":
                return "\\t"
            case _ if " " <= char <= "~":
                return char
            case _:
                raise ValueError(f"non-printable-ASCII char U+{ord(char):04X} in Rust literal: {value!r}")

    return f'"{"".join(encode(char) for char in value)}"'


def const(name: str, value: str) -> str:
    # rustfmt breaks the `=` onto its own line only when the one-liner overflows
    # MAX_WIDTH and the continuation would fit; an unbreakable long literal stays inline.
    literal = rust_str(value)
    one_line = f"pub const {name}: &str = {literal};"
    return (
        f"pub const {name}: &str =\n    {literal};"
        if MAX_WIDTH < len(one_line) and len(literal) + 5 <= MAX_WIDTH
        else one_line
    )


def float_const(name: str, value: float) -> str:
    if not math.isfinite(value):
        raise ValueError(f"non-finite f64 in Rust literal: {name} = {value!r}")
    return f"pub const {name}: f64 = {value!r};"


def str_slice_const(name: str, values: tuple[str, ...]) -> str:
    # rustfmt: one line if it fits, else a single block-indented line, else one item per
    # line — it never packs multiple items onto a continuation line.
    items = [rust_str(value) for value in sorted(values)]
    if len(one_line := f"pub const {name}: &[&str] = &[{', '.join(items)}];") <= MAX_WIDTH:
        return one_line
    body = (
        f"    {inner},"
        if 5 + len(inner := ", ".join(items)) <= MAX_WIDTH
        else "\n".join(f"    {item}," for item in items)
    )
    return f"pub const {name}: &[&str] = &[\n{body}\n];"


def render_const(name: str, value: str | float | tuple[str, ...]) -> str:
    match value:
        case str():
            return const(name, value)
        case float():
            return float_const(name, value)
        case tuple():
            return str_slice_const(name, value)


def literals() -> dict[str, str | float | tuple[str, ...]]:
    return {
        "protocol.DENIAL_PREFIX": DENIAL_PREFIX,
        "protocol.DENIAL_KIND_USER_REJECTED": DENIAL_KIND_USER_REJECTED,
        "protocol.DENIAL_KIND_PERMISSION_RULE": DENIAL_KIND_PERMISSION_RULE,
        "protocol.USER_SAID_MARKER": USER_SAID_MARKER,
        "protocol.USER_SAID_TRAILER": USER_SAID_TRAILER,
        "protocol.ANSWERED_PREFIX": ANSWERED_PREFIX,
        "protocol.ANSWERED_TRAILER": ANSWERED_TRAILER,
        "protocol.INTERRUPT_MARKER_PATTERN": group_pattern(INTERRUPT_MARKER_GROUPS),
        "protocol.AGENT_INJECTION_PATTERN": group_pattern(AGENT_INJECTION_GROUPS),
        "mining.TRANSCRIPT_MESSAGE": TRANSCRIPT_MESSAGE,
        "mining.PLAN_REVIEW": PLAN_REVIEW,
        "mining.INTERRUPT_REJECTION": INTERRUPT_REJECTION,
        "mining.REVIEW_COMMENT": REVIEW_COMMENT,
        "mining.QUESTION_ANSWER": QUESTION_ANSWER,
        "mining.DETECTOR_TRANSCRIPT_MESSAGE": TRANSCRIPT_MESSAGE_DETECTOR,
        "mining.DETECTOR_EXIT_PLAN_REJECTION": EXIT_PLAN_REJECTION_DETECTOR,
        "mining.DETECTOR_PLAN_REENTRY": PLAN_REENTRY_DETECTOR,
        "mining.DETECTOR_DENIAL": DENIAL_DETECTOR,
        "mining.DETECTOR_INTERRUPT": INTERRUPT_DETECTOR,
        "mining.DETECTOR_REVIEW_COMMENT": REVIEW_COMMENT_DETECTOR,
        "mining.DETECTOR_ASK_USER_QUESTION": ASK_USER_QUESTION_DETECTOR,
        "mining.ANSWER_PREVIEW_SEP": ANSWER_PREVIEW_SEP,
        "mining.ANSWER_NOTES_SEP": ANSWER_NOTES_SEP,
        "mining.NO_OPTION_SELECTED": NO_OPTION_SELECTED,
        "mining.NONE": NONE,
        "mining.LOW": LOW,
        "command.WRAPPER_COMMANDS": tuple(sorted(WRAPPER_COMMANDS)),
        "command.MULTI_LEVEL_TOOLS": tuple(sorted(MULTI_LEVEL_TOOLS)),
        "command.COMPOUND_OPS": tuple(sorted(COMPOUND_OPS)),
        "command.ASSIGNMENT_PATTERN": ASSIGNMENT_RE.pattern,
        "corrections.DDL": CORRECTIONS_DDL,
    }


def render_domain(domain: str, manifest: dict[str, str | float | tuple[str, ...]]) -> str:
    lines = (
        render_const(name.partition(".")[2], value)
        for name, value in manifest.items()
        if name.partition(".")[0] == domain
    )
    return "\n".join((HEADER, "", *lines)) + "\n"


def mod_rs() -> str:
    mods = ("pub mod command;", "pub mod corrections;", "pub mod mining;", "pub mod protocol;")
    return "\n".join((HEADER, "", *mods)) + "\n"


def render() -> dict[str, str]:
    manifest = literals()
    return {"rust/crates/core/src/generated/mod.rs": mod_rs()} | {
        f"rust/crates/core/src/generated/{domain}.rs": render_domain(domain, manifest)
        for domain in dict.fromkeys(name.partition(".")[0] for name in manifest)
    }


def main() -> None:
    rendered = render()
    for relpath, content in rendered.items():
        path = ROOT / relpath
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {' + '.join(rendered)}")


if __name__ == "__main__":
    main()
