"""Generate the typed package-root export surface from ``EXPORTS``.

Run: ``uv run --no-sync python scripts/gen_export_stub.py``
Check: ``uv run --no-sync python scripts/gen_export_stub.py --check``
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from cc_transcript import EXPORTS  # noqa: E402

STUB = REPO_ROOT / "cc_transcript" / "__init__.pyi"


def render() -> str:
    by_module: dict[str, list[str]] = {}
    for name, module in EXPORTS.items():
        by_module.setdefault(module, []).append(name)

    lines = ["# Generated by scripts/gen_export_stub.py. Do not edit.", "# isort: off", ""]
    for module in sorted(by_module):
        lines.append(f"from {module} import (")
        lines.extend(f"    {name} as {name}," for name in sorted(by_module[module]))
        lines.extend((")", ""))

    lines.extend(("# isort: on", "", "EXPORTS: dict[str, str]", "", "__all__ = ["))
    lines.extend(f'    "{name}",' for name in sorted(EXPORTS))
    lines.extend(("]", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = render().encode()
    if args.check:
        if not STUB.exists() or STUB.read_bytes() != rendered:
            print(f"{STUB.relative_to(REPO_ROOT)} is out of date; run scripts/gen_export_stub.py", file=sys.stderr)
            return 1
        return 0

    STUB.write_bytes(rendered)
    print(f"wrote {STUB.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
