// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct SessionActivity SessionActivity;
void __swift_bridge__$SessionActivity$_free(void* self);

void* __swift_bridge__$Vec_SessionActivity$new(void);
void __swift_bridge__$Vec_SessionActivity$drop(void* vec_ptr);
void __swift_bridge__$Vec_SessionActivity$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_SessionActivity$pop(void* vec_ptr);
void* __swift_bridge__$Vec_SessionActivity$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_SessionActivity$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_SessionActivity$len(void* vec_ptr);
void* __swift_bridge__$Vec_SessionActivity$as_ptr(void* vec_ptr);

typedef struct PendingItem PendingItem;
void __swift_bridge__$PendingItem$_free(void* self);

void* __swift_bridge__$Vec_PendingItem$new(void);
void __swift_bridge__$Vec_PendingItem$drop(void* vec_ptr);
void __swift_bridge__$Vec_PendingItem$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_PendingItem$pop(void* vec_ptr);
void* __swift_bridge__$Vec_PendingItem$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_PendingItem$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_PendingItem$len(void* vec_ptr);
void* __swift_bridge__$Vec_PendingItem$as_ptr(void* vec_ptr);

bool __swift_bridge__$SessionActivity$is_waiting(void* self);
bool __swift_bridge__$SessionActivity$mid_tool(void* self);
struct __private__OptionI64 __swift_bridge__$SessionActivity$last_event_epoch(void* self);
void* __swift_bridge__$SessionActivity$pending(void* self);
void* __swift_bridge__$PendingItem$tool_use_id(void* self);
struct RustStr __swift_bridge__$PendingItem$name(void* self);
struct RustStr __swift_bridge__$PendingItem$kind(void* self);
struct __private__ResultPtrAndPtr __swift_bridge__$session_activity(void* path, void* waiting_tools, void* human_facing_tools);
